import {initializeApp} from "https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import {getAuth,onAuthStateChanged,signInWithEmailAndPassword,sendPasswordResetEmail,signOut} from "https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import {getFirestore,collection,addDoc,getDocs,updateDoc,deleteDoc,doc,setDoc,getDoc,serverTimestamp,query,orderBy} from "https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
const firebaseConfig={apiKey:"AIzaSyBMsuR0320Nz3asVRj5axXFvKJ5Ftz9COQ",authDomain:"jogadores-de-volei.firebaseapp.com",projectId:"jogadores-de-volei",storageBucket:"jogadores-de-volei.firebasestorage.app",messagingSenderId:"48728914064",appId:"1:48728914064:web:1dd7aeb705319886f74015",measurementId:"G-K033D1K41Y"};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
const $=id=>document.getElementById(id);const loginSection=$("loginSection"),adminSection=$("adminSection"),loginForm=$("loginForm"),loginStatus=$("loginStatus"),adminStatus=$("adminStatus"),atletaForm=$("atletaForm"),atletaId=$("atletaId"),foto=$("foto"),fotoPreview=$("fotoPreview"),historicoContainer=$("historicoContainer"),atletasAdmin=$("atletasAdmin");
let atletas=[],fotoAtual="";
function status(el,msg,t="ok"){el.textContent=msg;el.className=`status ${t}`}function clear(el){el.textContent="";el.className="status"}function esc(v){const d=document.createElement("div");d.textContent=v??"";return d.innerHTML}
function addHistorico(equipe="",categoria="",ano=""){const d=document.createElement("div");d.className="historico-item";d.innerHTML=`<input class="histEquipe" placeholder="Equipe" value="${esc(equipe)}"><input class="histCategoria" placeholder="Categoria" value="${esc(categoria)}"><input class="histAno" type="number" min="1900" max="2100" placeholder="Ano" value="${esc(ano)}"><button type="button" class="btn-danger">❌</button>`;d.querySelector("button").onclick=()=>d.remove();historicoContainer.appendChild(d)}
function getHistorico(){return [...historicoContainer.querySelectorAll(".historico-item")].map(d=>({equipe:d.querySelector(".histEquipe").value.trim(),categoria:d.querySelector(".histCategoria").value.trim(),ano:d.querySelector(".histAno").value.trim()})).filter(x=>x.equipe)}
function resetForm(){atletaForm.reset();atletaId.value="";fotoAtual="";foto.value="";fotoPreview.src="";fotoPreview.style.display="none";historicoContainer.innerHTML="";addHistorico();$("btnSalvar").textContent="Cadastrar atleta";$("btnCancelar").classList.add("hidden")}
async function privateData(id){try{const s=await getDoc(doc(db,"atletas",id,"privado","dados"));return s.exists()?s.data():{}}catch(e){console.error(e);return {}}}
async function load(){try{let s;try{s=await getDocs(query(collection(db,"atletas"),orderBy("criadoEm","desc")))}catch{s=await getDocs(collection(db,"atletas"))}const base=s.docs.map(x=>({id:x.id,...x.data()}));atletas=await Promise.all(base.map(async a=>({...a,privado:await privateData(a.id)})));render()}catch(e){console.error(e);status(adminStatus,`Erro ao carregar atletas (${e.code||"erro"}).`,"erro")}}
function render(){atletasAdmin.innerHTML="";if(!atletas.length){atletasAdmin.innerHTML='<p class="subtitulo">Nenhum atleta cadastrado.</p>';return}atletas.forEach(a=>{const d=document.createElement("div");d.className="atleta-admin";d.innerHTML=`<div class="atleta-info"><strong>${esc(a.nome||"Sem nome")}</strong><span>${esc(a.time||"Sem time")} · ${esc(a.categoria||"Sem categoria")} · ${a.status==="inativo"?"🔴 Inativo":"🟢 Ativo"}</span><small>🔒 ${esc(a.privado?.contato||"Sem contato cadastrado")}</small></div><div class="atleta-actions"><button class="btn-secondary editar" type="button">Editar</button><button class="btn-danger excluir" type="button">Excluir</button></div>`;d.querySelector(".editar").onclick=()=>edit(a.id);d.querySelector(".excluir").onclick=()=>remove(a.id);atletasAdmin.appendChild(d)})}
async function edit(id){const a=atletas.find(x=>x.id===id);if(!a)return;$("nome").value=a.nome||"";$("nascimento").value=a.nascimento||"";$("cidade").value=a.cidade||"";$("posicao").value=a.posicao||"";$("categoria").value=a.categoria||"";$("time").value=a.time||"";$("status").value=a.status||"ativo";$("observacoes").value=a.observacoes||"";$("contato").value=a.privado?.contato||"";atletaId.value=id;fotoAtual=a.foto||"";if(fotoAtual){fotoPreview.src=fotoAtual;fotoPreview.style.display="block"}historicoContainer.innerHTML="";(a.historicoEquipes||[]).forEach(h=>addHistorico(h.equipe,h.categoria,h.ano));if(!historicoContainer.children.length)addHistorico();$("btnSalvar").textContent="Salvar alterações";$("btnCancelar").classList.remove("hidden");atletaForm.scrollIntoView({behavior:"smooth"})}
async function remove(id){const a=atletas.find(x=>x.id===id);if(!a||!confirm(`Excluir "${a.nome}"?`))return;try{await deleteDoc(doc(db,"atletas",id));await deleteDoc(doc(db,"atletas",id,"privado","dados")).catch(()=>{});status(adminStatus,"Atleta excluído com sucesso.");await load()}catch(e){status(adminStatus,`Erro ao excluir (${e.code||"erro"}).`,"erro")}}
function compress(file){return new Promise((resolve,reject)=>{if(!file)return resolve("");const r=new FileReader();r.onload=e=>{const i=new Image();i.onload=()=>{const s=Math.min(1,900/Math.max(i.width,i.height)),c=document.createElement("canvas");c.width=Math.max(1,i.width*s);c.height=Math.max(1,i.height*s);c.getContext("2d").drawImage(i,0,0,c.width,c.height);resolve(c.toDataURL("image/jpeg",.82))};i.onerror=reject;i.src=e.target.result};r.onerror=reject;r.readAsDataURL(file)})}
foto.onchange=async()=>{try{const v=await compress(foto.files[0]);if(v){fotoPreview.src=v;fotoPreview.style.display="block"}}catch{status(adminStatus,"Erro ao processar a foto.","erro")}};
loginForm.onsubmit=async e=>{e.preventDefault();clear(loginStatus);try{await signInWithEmailAndPassword(auth,$("loginEmail").value.trim().toLowerCase(),$("loginPassword").value)}catch(err){let m=err.code==="auth/invalid-credential"?"E-mail ou senha incorretos.":err.code==="auth/unauthorized-domain"?"Domínio não autorizado no Firebase.":`Erro no login (${err.code||"desconhecido"}).`;status(loginStatus,m,"erro")}};
const forgot=document.createElement("button");forgot.type="button";forgot.textContent="Esqueci minha senha";forgot.style.cssText="background:none;border:0;color:#93c5fd;cursor:pointer;text-decoration:underline;padding:8px 0";loginForm.appendChild(forgot);forgot.onclick=async()=>{const e=$("loginEmail").value.trim();if(!e)return status(loginStatus,"Digite seu e-mail primeiro.","erro");try{await sendPasswordResetEmail(auth,e);status(loginStatus,"Link de redefinição enviado.")}catch(err){status(loginStatus,`Erro (${err.code||"desconhecido"}).`,"erro")}};
$("btnSair").onclick=()=>signOut(auth);$("btnAdicionarHistorico").onclick=()=>addHistorico();$("btnCancelar").onclick=resetForm;
atletaForm.onsubmit=async e=>{e.preventDefault();clear(adminStatus);const nome=$("nome").value.trim(),time=$("time").value.trim();if(!nome||!time)return status(adminStatus,"Preencha nome completo e time atual.","erro");$("btnSalvar").disabled=true;try{let f=fotoAtual;if(foto.files[0])f=await compress(foto.files[0]);const data={nome,nascimento:$("nascimento").value,cidade:$("cidade").value.trim(),posicao:$("posicao").value,categoria:$("categoria").value.trim(),time,status:$("status").value,historicoEquipes:getHistorico(),observacoes:$("observacoes").value.trim(),foto:f,atualizadoEm:serverTimestamp()};let id=atletaId.value;if(id){await updateDoc(doc(db,"atletas",id),data)}else{id=(await addDoc(collection(db,"atletas"),{...data,criadoEm:serverTimestamp()})).id}await setDoc(doc(db,"atletas",id,"privado","dados"),{contato:$("contato").value.trim(),atualizadoEm:serverTimestamp()},{merge:true});status(adminStatus,atletaId.value?"Atleta atualizado com sucesso.":"Atleta cadastrado com sucesso.");resetForm();await load()}catch(err){console.error(err);status(adminStatus,`Não foi possível salvar (${err.code||"erro"}). Verifique as regras do Firestore.` ,"erro")}finally{$("btnSalvar").disabled=false}};
onAuthStateChanged(auth,async u=>{if(u){loginSection.classList.add("hidden");adminSection.classList.remove("hidden");$("usuarioLogado").textContent=`Administrador conectado: ${u.email}`;resetForm();await load()}else{loginSection.classList.remove("hidden");adminSection.classList.add("hidden")}});