// Rastreamento próprio + Google Analytics 4
import{initializeApp}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import{getFirestore,collection,addDoc,serverTimestamp}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
const GA_ID="G-K033D1K41Y";
const firebaseConfig={apiKey:"AIzaSyBMsuR0320Nz3asVRj5axXFvKJ5Ftz9COQ",authDomain:"jogadores-de-volei.firebaseapp.com",projectId:"jogadores-de-volei",storageBucket:"jogadores-de-volei.firebasestorage.app",messagingSenderId:"48728914064",appId:"1:48728914064:web:1dd7aeb705319886f74015",measurementId:GA_ID};
initializeApp(firebaseConfig);const db=getFirestore(),isAdminPage=location.pathname.toLowerCase().endsWith("/admin.html");
if(!window.__ga4_loaded){window.__ga4_loaded=true;const s=document.createElement("script");s.async=true;s.src=`https://www.googletagmanager.com/gtag/js?id=${GA_ID}`;document.head.appendChild(s);window.dataLayer=window.dataLayer||[];window.gtag=function(){window.dataLayer.push(arguments)};window.gtag("js",new Date());window.gtag("config",GA_ID,{anonymize_ip:true,send_page_view:true})}
function visitorId(){try{let id=localStorage.getItem("bd_atletas_visitor");if(!id){id=crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(36).slice(2)}`;localStorage.setItem("bd_atletas_visitor",id)}return id}catch{return`anon-${Math.random().toString(36).slice(2)}`}}
function device(){return innerWidth<=700?"Celular":innerWidth<=1100?"Tablet":"Computador"}
function saveOwnEvent(name,p={}){if(isAdminPage)return null;try{return addDoc(collection(db,"site_stats"),{nome:String(name).slice(0,60),pagina:location.pathname.slice(0,200),visitante:visitorId(),dispositivo:device(),origem:String(p.origem||"site").slice(0,50),criadoEm:serverTimestamp()}).catch(()=>null)}catch{return null}}
export function trackEvent(name,p={}){if(typeof window.gtag==="function")window.gtag("event",name,p);saveOwnEvent(name,p)}
const style=document.createElement("style");style.textContent=`.admin-tab,.analytics-cta,.stats-link{pointer-events:auto!important;position:relative!important;z-index:20!important;cursor:pointer!important;touch-action:manipulation!important}.admin-form #posicao{display:none!important}.admin-form #adminPosicoesBox{display:block!important;visibility:visible!important;opacity:1!important}.admin-form #adminPosicoesBox .multi-options{display:grid!important}.admin-form #adminPosicoesBox .multi-option{display:flex!important}@media(max-width:700px){.admin-tabs{display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr))!important;overflow:visible!important;width:100%!important;position:relative!important;z-index:30!important}.admin-tab{width:100%!important;min-height:48px!important;white-space:normal!important}.stats-grid,.stats-links,.stats-real-grid{grid-template-columns:1fr!important}.stats-link{min-height:62px!important}}`;document.head.appendChild(style);
if(isAdminPage)import(`./estatisticas-admin.js?v=20260826-3`);
document.addEventListener("DOMContentLoaded",()=>{if(!isAdminPage)trackEvent("page_view",{origem:"site"});const t=(q,e,p={})=>document.querySelectorAll(q).forEach(x=>x.addEventListener("click",()=>trackEvent(e,p),{passive:true}));t(".whatsapp-top-cta,.whatsapp-cadastro","whatsapp_click");t(".championship-cta","campeonatos_click");t(".hero-button","ver_atletas_click");t(".admin-cta","painel_admin_click");const c=document.querySelector('a[href*="cadastro-atleta"]');if(c)c.addEventListener("click",()=>trackEvent("cadastro_aberto"),{passive:true});const q=document.getElementById("btnPesquisar");if(q)q.addEventListener("click",()=>trackEvent("pesquisa_atletas"),{passive:true});const f=document.getElementById("cadastroAtletaForm");if(f)f.addEventListener("submit",()=>trackEvent("cadastro_enviado"));});
