// Analytics + consentimento de cookies
import{initializeApp}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import{getFirestore,collection,addDoc,serverTimestamp}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
const GA_ID="G-K033D1K41Y";
const firebaseConfig={apiKey:"AIzaSyBMsuR0320Nz3asVRj5axXFvKJ5Ftz9COQ",authDomain:"jogadores-de-volei.firebaseapp.com",projectId:"jogadores-de-volei",storageBucket:"jogadores-de-volei.firebasestorage.app",messagingSenderId:"48728914064",appId:"1:48728914064:web:1dd7aeb705319886f74015",measurementId:GA_ID};
initializeApp(firebaseConfig);const db=getFirestore(),isAdminPage=location.pathname.toLowerCase().endsWith("/admin.html"),CONSENT_KEY="bd_atletas_cookie_consent";
function consent(){try{return localStorage.getItem(CONSENT_KEY)}catch{return null}}
function loadGA(){if(window.__ga4_loaded||consent()!=="accepted")return;window.__ga4_loaded=true;const s=document.createElement("script");s.async=true;s.src=`https://www.googletagmanager.com/gtag/js?id=${GA_ID}`;document.head.appendChild(s);window.dataLayer=window.dataLayer||[];window.gtag=function(){window.dataLayer.push(arguments)};window.gtag("js",new Date());window.gtag("config",GA_ID,{anonymize_ip:true,send_page_view:true})}
function visitorId(){try{let id=localStorage.getItem("bd_atletas_visitor");if(!id){id=crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(36).slice(2)}`;localStorage.setItem("bd_atletas_visitor",id)}return id}catch{return`anon-${Math.random().toString(36).slice(2)}`}}
function device(){return innerWidth<=700?"Celular":innerWidth<=1100?"Tablet":"Computador"}
function saveOwnEvent(name,p={}){if(isAdminPage||consent()!=="accepted")return null;try{return addDoc(collection(db,"site_stats"),{nome:String(name).slice(0,60),pagina:location.pathname.slice(0,200),visitante:visitorId(),dispositivo:device(),origem:String(p.origem||"site").slice(0,50),criadoEm:serverTimestamp()}).catch(()=>null)}catch{return null}}
export function trackEvent(name,p={}){if(consent()!=="accepted")return;loadGA();if(typeof window.gtag==="function")window.gtag("event",name,p);saveOwnEvent(name,p)}
const style=document.createElement("style");style.textContent=`.admin-tab,.analytics-cta,.stats-link{pointer-events:auto!important;position:relative!important;z-index:20!important;cursor:pointer!important;touch-action:manipulation!important}.admin-form #posicao{display:none!important}.admin-form #adminPosicoesBox{display:block!important;visibility:visible!important;opacity:1!important;width:100%!important}.admin-form #adminPosicoesBox .multi-options{display:grid!important}.admin-form #adminPosicoesBox .multi-option{display:flex!important}.admin-form #adminPosicoesBox input{display:block!important;visibility:visible!important;opacity:1!important;position:static!important;width:18px!important;height:18px!important}.bd-cookie-banner{position:fixed;left:18px;right:18px;bottom:18px;z-index:2147483640;background:#111814;color:#f5f0e3;border:1px solid rgba(217,169,63,.35);border-radius:16px;box-shadow:0 18px 60px rgba(0,0,0,.5);padding:18px}.bd-cookie-banner strong{color:#f2cc72}.bd-cookie-banner p{margin:6px 0 12px;font-size:12px;line-height:1.5;color:#d5d1c7}.bd-cookie-actions{display:flex;gap:8px;flex-wrap:wrap}.bd-cookie-actions button,.bd-cookie-actions a{border:0;border-radius:9px;padding:10px 14px;font-size:11px;font-weight:900;text-decoration:none;cursor:pointer}.bd-cookie-accept{background:linear-gradient(135deg,#f2cc72,#bd8425);color:#15130e}.bd-cookie-reject,.bd-cookie-manage{background:#0b100d;border:1px solid rgba(217,169,63,.35)!important;color:#f2cc72}.bd-legal-links{display:flex;gap:10px;justify-content:center;flex-wrap:wrap;margin:22px auto 8px;padding:0 16px}.bd-legal-links a{color:#8f968e;font-size:10px;text-decoration:none}.bd-legal-links a:hover{color:#f2cc72;text-decoration:underline}@media(max-width:700px){.bd-cookie-banner{left:10px;right:10px;bottom:10px}.bd-cookie-actions{display:grid;grid-template-columns:1fr}.bd-cookie-actions button,.bd-cookie-actions a{text-align:center}}`;document.head.appendChild(style);
function mostrarBanner(){if(isAdminPage||consent())return;const b=document.createElement("div");b.className="bd-cookie-banner";b.innerHTML='<strong>🍪 Privacidade e cookies</strong><p>Usamos tecnologias estritamente necessárias para lembrar sua escolha e, somente com sua autorização, analytics para entender como o site é utilizado. Você pode aceitar ou recusar. <a href="politica-cookies.html" style="color:#f2cc72">Saiba mais</a>.</p><div class="bd-cookie-actions"><button class="bd-cookie-accept">ACEITAR ANALYTICS</button><button class="bd-cookie-reject">REJEITAR ANALYTICS</button><a class="bd-cookie-manage" href="politica-cookies.html">POLÍTICA DE COOKIES</a></div>';document.body.appendChild(b);const fechar=v=>{try{localStorage.setItem(CONSENT_KEY,v)}catch{}b.remove();if(v==="accepted"){loadGA();trackEvent("consent_granted",{origem:"cookie_banner"})}};b.querySelector(".bd-cookie-accept").onclick=()=>fechar("accepted");b.querySelector(".bd-cookie-reject").onclick=()=>fechar("rejected")}
function inserirLinksLegais(){if(isAdminPage||document.querySelector(".bd-legal-links"))return;const alvo=document.querySelector(".site-footer")||document.body;const box=document.createElement("nav");box.className="bd-legal-links";box.setAttribute("aria-label","Informações legais");box.innerHTML='<a href="politica-privacidade.html">Política de Privacidade</a><a href="termos-de-uso.html">Termos de Uso</a><a href="politica-cookies.html">Política de Cookies</a>';alvo.parentNode?.insertBefore(box,alvo.nextSibling)}
function repararPosicoesAdmin(){if(!isAdminPage)return;const form=document.getElementById("atletaForm");if(!form)return;const antigo=document.getElementById("posicao");if(!antigo)return;let box=document.getElementById("adminPosicoesBox");if(!box){const label=antigo.closest("label");box=document.createElement("div");box.id="adminPosicoesBox";box.className="multi-box";box.innerHTML='<label>POSIÇÕES *</label><div class="multi-options"><label class="multi-option"><input type="checkbox" value="Levantador">Levantador</label><label class="multi-option"><input type="checkbox" value="Ponteiro">Ponteiro</label><label class="multi-option"><input type="checkbox" value="Oposto">Oposto</label><label class="multi-option"><input type="checkbox" value="Central">Central</label><label class="multi-option"><input type="checkbox" value="Líbero">Líbero</label><label class="multi-option"><input type="checkbox" value="Universal">Universal</label></div><small class="multi-help">Selecione uma ou mais posições.</small>';antigo.type="hidden";antigo.value="";if(label){label.parentNode.insertBefore(box,label);label.remove()}else{antigo.parentNode.insertBefore(box,antigo)}}else{antigo.style.display="none"}box.querySelectorAll("input[type=checkbox]").forEach(c=>{c.addEventListener("change",()=>{antigo.value=[...box.querySelectorAll("input:checked")].map(x=>x.value).join(", ")})})}
if(isAdminPage){import(`./estatisticas-admin.js?v=20260826-4`);if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>setTimeout(repararPosicoesAdmin,100));else setTimeout(repararPosicoesAdmin,100);new MutationObserver(()=>repararPosicoesAdmin()).observe(document.documentElement,{childList:true,subtree:true})}
document.addEventListener("DOMContentLoaded",()=>{if(isAdminPage)return;inserirLinksLegais();mostrarBanner();if(consent()==="accepted")trackEvent("page_view",{origem:"site"});const t=(q,e,p={})=>document.querySelectorAll(q).forEach(x=>x.addEventListener("click",()=>trackEvent(e,p),{passive:true}));t(".whatsapp-top-cta,.whatsapp-cadastro","whatsapp_click");t(".championship-cta","campeonatos_click");t(".hero-button","ver_atletas_click");t(".admin-cta","painel_admin_click");const c=document.querySelector('a[href*="cadastro-atleta"]');if(c)c.addEventListener("click",()=>trackEvent("cadastro_aberto"),{passive:true});const q=document.getElementById("btnPesquisar");if(q)q.addEventListener("click",()=>trackEvent("pesquisa_atletas"),{passive:true});const f=document.getElementById("cadastroAtletaForm");if(f)f.addEventListener("submit",()=>trackEvent("cadastro_enviado"));});