import{initializeApp}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";import{getFirestore,collection,addDoc,serverTimestamp,getDocs,query,where}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
const firebaseConfig={apiKey:"AIzaSyBMsuR0320Nz3asVRj5axXFvKJ5Ftz9COQ",authDomain:"jogadores-de-volei.firebaseapp.com",projectId:"jogadores-de-volei",storageBucket:"jogadores-de-volei.firebasestorage.app",messagingSenderId:"48728914064",appId:"1:48728914064:web:1dd7aeb705319886f74015",measurementId:"G-K033D1K41Y"};
const db=getFirestore(initializeApp(firebaseConfig));
const PIX_CHAVE="A DEFINIR";
const PLANOS={bronze:{nome:"Bronze",valor:50,selo:"APOIO ESSENCIAL",beneficios:["Logo no banco de atletas","Presença na rede de apoiadores"]},prata:{nome:"Prata",valor:100,selo:"APOIO DESTAQUE",beneficios:["Logo em destaque","Banner automático","Presença na rede de apoiadores"]},ouro:{nome:"Ouro",valor:200,selo:"APOIO PREMIUM",beneficios:["Banner premium","Logo em destaque","Prioridade na divulgação"]},master:{nome:"Master",valor:350,selo:"APOIO MASTER",beneficios:["Banner principal","Maior destaque visual","Divulgação prioritária"]}};
const $=id=>document.getElementById(id),esc=v=>{const d=document.createElement("div");d.textContent=v??"";return d.innerHTML},dinheiro=v=>Number(v).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
let planoAtual="bronze";
function atualizarPlano(){document.querySelectorAll(".apoio-plan").forEach(c=>c.classList.toggle("selected",c.dataset.plano===planoAtual));const p=PLANOS[planoAtual];if($("apoioPlanoSelecionado"))$("apoioPlanoSelecionado").innerHTML="<strong>"+esc(p.nome)+"</strong> · "+dinheiro(p.valor)+"/mês";if($("apoioPixValor"))$("apoioPixValor").textContent=dinheiro(p.valor)}
function abrirModal(){const m=$("apoioModal");if(m)m.classList.remove("hidden");document.body.style.overflow="hidden";atualizarPlano()}
function fecharModal(){const m=$("apoioModal");if(m)m.classList.add("hidden");document.body.style.overflow=""}
document.addEventListener("click",e=>{const card=e.target.closest(".apoio-plan");if(card){planoAtual=card.dataset.plano;atualizarPlano()}if(e.target.closest("[data-abrir-apoio]"))abrirModal();if(e.target.closest("[data-fechar-apoio]"))fecharModal()});
async function enviarPedido(e){e.preventDefault();const f=e.currentTarget,nome=$("apoioNomeEmpresa").value.trim(),responsavel=$("apoioResponsavel").value.trim(),contato=$("apoioContato").value.trim(),cidade=$("apoioCidade").value.trim(),link=$("apoioLink").value.trim(),p=PLANOS[planoAtual],status=$("apoioStatus");if(!nome||!responsavel||!contato||!cidade){status.textContent="Preencha empresa, responsável, contato e cidade.";return}status.textContent="Enviando solicitação...";try{const ref=await addDoc(collection(db,"apoiadores_pendentes"),{empresa:nome,responsavel,contato,cidade,link,plano:p.nome,planoId:planoAtual,valor:p.valor,status:"aguardando_pagamento",aprovacao:"pendente",criadoEm:serverTimestamp()});f.classList.add("hidden");$("apoioPagamento").classList.remove("hidden");$("apoioNumeroPedido").textContent=ref.id.slice(0,8).toUpperCase();$("apoioPixChave").textContent=PIX_CHAVE;$("apoioPixValor").textContent=dinheiro(p.valor);status.textContent=""}catch(err){console.error(err);status.textContent="Não foi possível enviar a solicitação. Tente novamente."}}
async function carregarApoiadoresPremium(){const box=$("apoioBanners");if(!box)return;try{const s=await getDocs(query(collection(db,"apoiadores"),where("ativo","==",true)));const arr=s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>{const ordem={Master:0,Ouro:1,Prata:2,Bronze:3};return(ordem[a.plano]??9)-(ordem[b.plano]??9)});box.innerHTML=arr.map(a=>{const classe=String(a.plano||"").toLowerCase();return '<a class="apoio-public-card '+classe+'" href="'+esc(a.link||"#")+'" target="_blank" rel="noopener noreferrer"><img src="'+esc(a.imagem||"")+'" alt="Logo de '+esc(a.nome||"apoiador")+'"><span class="nivel">'+esc(a.plano||"APOIADOR")+'</span><strong>'+esc(a.nome||"Apoiador")+'</strong><small>Parceiro do Banco de Dados de Atletas</small></a>'}).join("")||"<p class='subtitulo'>Em breve, novas marcas farão parte desta rede.</p>"}catch(e){console.error(e)}}
document.addEventListener("DOMContentLoaded",()=>{const f=$("apoioForm");f?.addEventListener("submit",enviarPedido);document.querySelectorAll(".apoio-plan").forEach(c=>c.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();planoAtual=c.dataset.plano;atualizarPlano()}}));$("apoioVoltarForm")?.addEventListener("click",()=>{$("apoioPagamento")?.classList.add("hidden");$("apoioForm")?.classList.remove("hidden")});atualizarPlano();carregarApoiadoresPremium()});
