import{initializeApp,getApps,getApp}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";import{getFirestore,collection,addDoc}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
const cfg={apiKey:"AIzaSyBMsuR0320Nz3asVRj5axXFvKJ5Ftz9COQ",authDomain:"jogadores-de-volei.firebaseapp.com",projectId:"jogadores-de-volei",storageBucket:"jogadores-de-volei.firebasestorage.app",messagingSenderId:"48728914064",appId:"1:48728914064:web:1dd7aeb705319886f74015",measurementId:"G-K033D1K41Y"};
const db=getFirestore(getApps().length?getApp():initializeApp(cfg));const normalizarCategoria=v=>{const s=String(v||"").trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"");if(s.includes("inic"))return"Iniciante";if(s.includes("avan"))return"Avançado";return"Intermediário"};const normalizarCidade=(cidade,uf)=>{let s=String(cidade||"").trim().replace(/\s+/g," "),u=String(uf||"").trim().toUpperCase();const m=s.match(/^([A-Z]{2})\s*[-,]\s*(.+)$/i)||s.match(/^(.+?)\s*[-,]\s*([A-Z]{2})$/i);if(m){if(m[1].length===2){u=m[1].toUpperCase();s=m[2].trim()}else{s=m[1].trim();u=m[2].toUpperCase()}}return u+" - "+s};
function compress(file,max=800){return new Promise((resolve,reject)=>{if(!file)return reject(new Error("Selecione uma foto do atleta."));const r=new FileReader();r.onload=e=>{const i=new Image();i.onload=()=>{const s=Math.min(1,max/Math.max(i.width,i.height)),c=document.createElement("canvas");c.width=Math.max(1,Math.round(i.width*s));c.height=Math.max(1,Math.round(i.height*s));c.getContext("2d").drawImage(i,0,0,c.width,c.height);let q=.82,x=c.toDataURL("image/jpeg",q);while(x.length>620000&&q>.35){q-=.07;x=c.toDataURL("image/jpeg",q)}if(x.length>700000)return reject(new Error("A foto ficou muito grande. Escolha uma foto menor ou tire um novo print da foto."));resolve(x)};i.onerror=()=>reject(new Error("Não foi possível processar a foto."));i.src=e.target.result};r.onerror=()=>reject(new Error("Não foi possível ler a foto."));r.readAsDataURL(file)})}
const form=document.getElementById("cadastroForm"),foto=document.getElementById("cadFoto"),preview=document.getElementById("cadPreview"),btn=document.getElementById("cadEnviar"),mensagem=document.getElementById("cadStatusMsg");
const campeonatosBox=document.getElementById("cadCampeonatos"),btnAddCampeonato=document.getElementById("btnAddCampeonato");
function adicionarCampeonato(dados={}){if(!campeonatosBox)return;const item=document.createElement("div");item.className="campeonato-item";item.innerHTML=`<input class="campNome" maxlength="120" placeholder="Nome do campeonato" value="${String(dados.campeonato||"").replace(/"/g,"&quot;")}"><input class="campColocacao" maxlength="40" placeholder="Colocação" value="${String(dados.colocacao||"").replace(/"/g,"&quot;")}"><input class="campAno" type="number" min="1900" max="2100" placeholder="Ano" value="${String(dados.ano||"").replace(/"/g,"&quot;")}"><button type="button" class="btn-remove-campeonato" aria-label="Remover campeonato">✕</button>`;item.querySelector(".btn-remove-campeonato").onclick=()=>item.remove();campeonatosBox.appendChild(item)}
function obterCampeonatos(){return[...document.querySelectorAll(".campeonato-item")].map(item=>({campeonato:item.querySelector(".campNome").value.trim(),colocacao:item.querySelector(".campColocacao").value.trim(),ano:item.querySelector(".campAno").value.trim()})).filter(x=>x.campeonato).slice(0,30)}
if(btnAddCampeonato)btnAddCampeonato.addEventListener("click",()=>adicionarCampeonato());
const selecionados=id=>[...document.querySelectorAll(`#${id} input[type="checkbox"]:checked`)].map(x=>x.value);
function mostrarMensagem(texto,erro=false){if(!mensagem)return;mensagem.textContent=texto;mensagem.className=erro?"cadastro-status erro":"cadastro-status"}
if(foto)foto.addEventListener("change",()=>{const file=foto.files?.[0];if(!file)return;const r=new FileReader();r.onload=()=>{preview.src=r.result;preview.style.display="block"};r.readAsDataURL(file)});
if(form)form.addEventListener("submit",async e=>{e.preventDefault();mostrarMensagem("");try{const modalidades=selecionados("cadModalidades"),posicoes=selecionados("cadPosicoes");if(!modalidades.length){mostrarMensagem("Selecione pelo menos uma modalidade.",true);return}if(!posicoes.length){mostrarMensagem("Selecione pelo menos uma posição.",true);return}if(!form.checkValidity()){form.reportValidity();return}btn.disabled=true;btn.textContent="ENVIANDO...";mostrarMensagem("Enviando cadastro para análise...");const imagem=await compress(foto.files?.[0]);await addDoc(collection(db,"atletas_pendentes"),{nome:document.getElementById("cadNome").value.trim(),nascimento:document.getElementById("cadNascimento").value,cidade:normalizarCidade(document.getElementById("cadCidade").value,document.getElementById("cadUF").value),uf:document.getElementById("cadUF").value.toUpperCase(),contato:document.getElementById("cadContato").value.trim(),modalidades,posicoes,modalidade:modalidades.join(", "),posicao:posicoes.join(", "),categoria:normalizarCategoria(document.getElementById("cadCategoria").value),time:document.getElementById("cadTime").value.trim(),status:"ativo",aprovacao:"pendente",historicoCampeonatos:obterCampeonatos(),observacoes:document.getElementById("cadObs").value.trim(),foto:imagem,criadoEm:new Date().toISOString()});document.querySelector(".cadastro-modal").innerHTML='<div class="cadastro-success"><div class="success-icon">🏐</div><h3>CADASTRO ENVIADO!</h3><p>Seus dados foram recebidos e ficarão aguardando aprovação da M&amp;M Organização.</p><a href="https://wa.me/5516988586327?text=Ol%C3%A1!%20Acabei%20de%20enviar%20meu%20cadastro%20para%20o%20Banco%20de%20Dados%20de%20Atletas." target="_blank" rel="noopener noreferrer">💬 FALAR COM A M&amp;M ORGANIZAÇÃO</a></div>'}catch(err){console.error("Erro ao enviar cadastro:",err);mostrarMensagem(err?.message||"Não foi possível enviar o cadastro. Verifique sua conexão e tente novamente.",true)}finally{if(btn){btn.disabled=false;btn.textContent="ENVIAR PARA ANÁLISE"}}});