import{getApp,getApps,initializeApp}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import{addDoc,collection,getDocs,getFirestore,limit,orderBy,query,where}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
import{uploadCloudinary}from"./cloudinary-upload.js?v=20260901-8";
import{feedImageUrl}from"./media-utils.js?v=20260901-1";
const cfg={apiKey:"AIzaSyBMsuR0320Nz3asVRj5axXFvKJ5Ftz9COQ",authDomain:"jogadores-de-volei.firebaseapp.com",projectId:"jogadores-de-volei",storageBucket:"jogadores-de-volei.firebasestorage.app",messagingSenderId:"48728914064",appId:"1:48728914064:web:1dd7aeb705319886f74015"};
const app=getApps().length?getApp():initializeApp(cfg),db=getFirestore(app),$=id=>document.getElementById(id),esc=v=>{const d=document.createElement("div");d.textContent=v??"";return d.innerHTML};
const TIMEOUT=18000,withTimeout=(p,ms=TIMEOUT)=>Promise.race([p,new Promise((_,reject)=>setTimeout(()=>reject(Object.assign(new Error("O banco demorou para responder."),{code:"deadline-exceeded"})),ms))]);
const hoje=()=>{const d=new Date();return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)},fmt=v=>{const d=new Date(`${v}T12:00:00`);return Number.isNaN(d.getTime())?"Data não informada":d.toLocaleDateString("pt-BR")};
function safeUrl(value){let s=String(value||"").trim();if(!s)return"";if(!/^https?:\/\//i.test(s))s="https://"+s;try{const u=new URL(s);return u.protocol==="https:"?u.href:""}catch{return""}}
function extractLink(description){const text=String(description||""),m=text.match(/\[link\](https?:\/\/[^\s\[]+)\[\/link\]/i);return{link:m?.[1]||"",description:text.replace(/\s*\[link\][\s\S]*?\[\/link\]\s*/gi," ").trim()}}
function embedLink(description,link){const base=String(description||"").replace(/\s*\[link\][\s\S]*?\[\/link\]\s*/gi," ").trim().slice(0,520);return link?`${base}${base?"\n":""}[link]${link}[/link]`.slice(0,700):base}
async function carregar(){const box=$("listaCampeonatos"),counter=$("contador");try{let snap;try{snap=await withTimeout(getDocs(query(collection(db,"campeonatos"),where("publicado","==",true),orderBy("data","asc"),limit(60))))}catch{snap=await withTimeout(getDocs(query(collection(db,"campeonatos"),where("publicado","==",true),limit(60))))}const arr=snap.docs.map(d=>({id:d.id,...d.data()})).filter(c=>String(c.data||"")>=hoje()).sort((a,b)=>String(a.data||"").localeCompare(String(b.data||"")));counter.textContent=`${arr.length} ${arr.length===1?"evento publicado":"eventos publicados"}`;box.innerHTML=arr.length?arr.map(c=>{const parsed=extractLink(c.descricao),image=feedImageUrl(c.imagem||""),media=parsed.link?`<a class="champ-image-link" href="${esc(parsed.link)}" target="_blank" rel="noopener noreferrer" aria-label="Abrir página do organizador de ${esc(c.nome||"campeonato")}"><img class="champ-image" src="${esc(image)}" alt="Cartaz de ${esc(c.nome||"campeonato")}" loading="lazy" decoding="async"></a>`:`<div class="champ-image-link"><img class="champ-image" src="${esc(image)}" alt="Cartaz de ${esc(c.nome||"campeonato")}" loading="lazy" decoding="async"></div>`;return`<article class="champ-card">${media}<div class="champ-body"><span class="tag">🏆 CAMPEONATO</span><h3>${esc(c.nome||"Campeonato")}</h3><div class="meta"><strong>📅 ${fmt(c.data)}</strong><br>📍 ${esc(c.local||"Local não informado")}<br>👤 ${esc(c.organizador||"Organizador não informado")}</div>${parsed.description?`<p class="meta">${esc(parsed.description)}</p>`:""}${parsed.link?`<a class="champ-organizer-link" href="${esc(parsed.link)}" target="_blank" rel="noopener noreferrer">ABRIR PÁGINA / INSCRIÇÕES →</a>`:""}</div></article>`}).join(""):'<div class="empty" style="grid-column:1/-1">Ainda não há campeonatos próximos publicados.</div>'}catch(e){console.error(e);counter.textContent="Não foi possível carregar";box.innerHTML='<div class="empty" style="grid-column:1/-1">Não foi possível carregar os campeonatos agora.</div>'}}
function configurarPreview(){const input=$("cartaz"),preview=$("preview");input?.addEventListener("change",()=>{const file=input.files?.[0];preview.style.display="none";preview.removeAttribute("src");if(!file)return;if(!["image/jpeg","image/png","image/webp"].includes(file.type)||file.size>10*1024*1024){input.value="";$("status").textContent="Use JPG, PNG ou WEBP com até 10 MB.";$("status").className="status erro";return}const url=URL.createObjectURL(file);preview.src=url;preview.style.display="block";preview.onload=()=>URL.revokeObjectURL(url)})}
async function submit(event){event.preventDefault();const st=$("status"),button=$("btnEnviar"),nome=$("nome").value.trim(),organizador=$("organizador").value.trim(),data=$("data").value,local=$("local").value.trim(),descricao=$("descricao").value.trim(),file=$("cartaz").files?.[0],linkRaw=$("linkOrganizador").value.trim(),link=linkRaw?safeUrl(linkRaw):"";st.className="status";if(nome.length<2||organizador.length<2||local.length<2||!data||!file){st.textContent="Preencha os campos obrigatórios e selecione o cartaz.";st.className="status erro";return}if(data<hoje()){st.textContent="A data deve ser hoje ou futura.";st.className="status erro";return}if(linkRaw&&!link){st.textContent="Informe um link HTTPS válido para o organizador ou deixe o campo vazio.";st.className="status erro";return}try{button.disabled=true;button.textContent="ENVIANDO CARTAZ...";st.textContent="Enviando o cartaz original em alta qualidade...";const up=await uploadCloudinary(file,{maxBytes:10*1024*1024,allowImage:true,allowVideo:false,tags:["cadastro-de-atletas","campeonatos"]});button.textContent="SALVANDO...";st.textContent="Salvando campeonato para análise...";await withTimeout(addDoc(collection(db,"campeonatos_pendentes"),{nome,organizador,data,local,descricao:embedLink(descricao,link),imagem:up.url,publicado:false,status:"pendente",aprovacao:"pendente",criadoEm:new Date().toISOString()}));event.currentTarget.reset();$("preview").style.display="none";$("preview").removeAttribute("src");st.textContent="✓ Campeonato enviado. A imagem será clicável para o link informado depois da aprovação.";st.className="status ok"}catch(e){console.error(e);st.textContent=e?.message||"Não foi possível enviar o campeonato.";st.className="status erro"}finally{button.disabled=false;button.textContent="ENVIAR PARA ANÁLISE"}}
$("data").min=hoje();configurarPreview();$("formCampeonato")?.addEventListener("submit",submit);$("btnAtualizarCampeonatos")?.addEventListener("click",carregar);carregar();
