import{getApp,getApps,initializeApp}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import{getAuth,onAuthStateChanged}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import{addDoc,collection,deleteDoc,doc,getCountFromServer,getDoc,getDocs,getFirestore,limit,orderBy,query,setDoc,Timestamp,where}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
import{uploadCloudinary}from"./cloudinary-upload.js?v=20260901-8";
import{feedImageUrl,thumbImageUrl}from"./media-utils.js?v=20260901-1";

const firebaseConfig={apiKey:"AIzaSyBMsuR0320Nz3asVRj5axXFvKJ5Ftz9COQ",authDomain:"jogadores-de-volei.firebaseapp.com",projectId:"jogadores-de-volei",storageBucket:"jogadores-de-volei.firebasestorage.app",messagingSenderId:"48728914064",appId:"1:48728914064:web:1dd7aeb705319886f74015"};
const app=getApps().length?getApp():initializeApp(firebaseConfig),db=getFirestore(app),auth=getAuth(app),$=id=>document.getElementById(id),publishForm=$("publishForm"),feed=$("communityFeed"),feedStatus=$("feedStatus"),publishStatus=$("publishStatus"),photoInput=$("postPhoto"),photoPreview=$("photoPreview"),postText=$("postText"),postCounter=$("postCounter");
let currentUser=null,items=[],liked=new Set();const profiles=new Map(),counts=new Map(),fallback="data:image/svg+xml;charset=UTF-8,"+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="160" height="160"><rect width="160" height="160" fill="#dfe9ef"/><text x="80" y="100" text-anchor="middle" font-size="58">🏐</text></svg>');
const esc=v=>{const d=document.createElement("div");d.textContent=v==null?"":String(v);return d.innerHTML},text=v=>v==null?"":String(v).trim(),millis=v=>v?.toMillis?.()??(v?.seconds?Number(v.seconds)*1000:Date.parse(v)||0),formatDate=v=>millis(v)?new Intl.DateTimeFormat("pt-BR",{dateStyle:"medium",timeStyle:"short"}).format(new Date(millis(v))):"Agora";
function setStatus(el,message,type=""){if(!el)return;el.textContent=message;el.className=`inline-status ${type}`.trim()}
function setFeedStatus(message,type=""){if(!feedStatus)return;feedStatus.textContent=message;feedStatus.className=`feed-status ${type}`.trim()}
async function profileOf(uid){if(!uid)return{nome:"Atleta",fotoUrl:fallback};if(profiles.has(uid))return profiles.get(uid);try{const s=await getDoc(doc(db,"perfis",uid)),p=s.exists()?{uid,...s.data()}:{uid,nome:"Atleta",fotoUrl:fallback};p.fotoUrl=p.fotoUrl||fallback;profiles.set(uid,p);return p}catch{return{uid,nome:"Atleta",fotoUrl:fallback}}}
async function ownVisibility(){if(!currentUser)return"publico";try{const s=await getDoc(doc(db,"config_perfis",currentUser.uid));return s.exists()&&s.data()?.privado===true?"privado":"publico"}catch{return"publico"}}
function mediaMarkup(item){if(item.kind==="video")return`<video class="post-image" src="${esc(item.url)}" controls playsinline preload="metadata"></video>`;return item.url?`<img class="post-image" src="${esc(feedImageUrl(item.url))}" alt="Foto publicada por ${esc(item.author?.nome||item.nome||"atleta")}" loading="lazy" decoding="async">`:""}
function cardCount(id){return counts.get(id)||{likes:0,comments:0}}
function renderFeed(){if(!feed)return;if(!items.length){feed.innerHTML='<div class="empty-feed"><strong>A conversa começa com você</strong><span>Ainda não há publicações na comunidade.</span></div>';return}feed.innerHTML=items.map(item=>{const c=cardCount(item.id),author=item.author||{nome:item.nome||"Atleta",fotoUrl:fallback},caption=item.texto||item.legenda||"";return`<article class="post-card" data-post-id="${esc(item.id)}" data-owner="${esc(item.ownerUid||"")}"><div class="post-card-inner"><div class="post-meta"><a href="perfil-social.html?uid=${encodeURIComponent(item.ownerUid||"")}"><img class="post-avatar" src="${esc(thumbImageUrl(author.fotoUrl||fallback))}" alt=""></a><div class="post-meta-copy"><a class="post-author" href="perfil-social.html?uid=${encodeURIComponent(item.ownerUid||"")}">${esc(author.nome||item.nome||"Atleta")}</a><span class="post-date">${esc(formatDate(item.criadoEm))}</span></div></div>${caption?`<p class="post-text">${esc(caption)}</p>`:""}${mediaMarkup(item)}<div class="post-actions"><button class="post-action like-post${liked.has(item.id)?" active":""}" type="button">${liked.has(item.id)?"♥":"♡"} CURTIR <b>${c.likes||0}</b></button><button class="post-action toggle-comments" type="button" aria-expanded="false">💬 ${c.comments||"COMENTAR"}</button><button class="post-action share-post" type="button">↗ COMPARTILHAR</button><button class="post-action report-post" type="button">⚑ DENUNCIAR</button></div></div><section class="comments-panel" aria-label="Comentários"><div class="comments-title"><span>CONVERSA DA COMUNIDADE</span><span>${c.comments||0} comentário${c.comments===1?"":"s"}</span></div><div class="comments-list" data-comments-list><div class="comment-empty">Abra os comentários para carregar.</div></div><form class="comment-form" data-post-id="${esc(item.id)}"><input name="texto" type="text" maxlength="500" placeholder="Escreva um comentário..." required><button class="comment-submit" type="submit">ENVIAR</button><div class="comment-status" role="status"></div></form></section></article>`}).join("")}
async function hydrateCounts(){await Promise.all(items.map(async item=>{const[likes,comments]=await Promise.all([getCountFromServer(collection(db,"curtidas_publicacoes",item.id,"usuarios")).then(x=>x.data().count||0).catch(()=>0),getCountFromServer(query(collection(db,"comentarios_publicacoes"),where("publicacaoId","==",item.id),where("aprovado","==",true))).then(x=>x.data().count||0).catch(()=>0)]);counts.set(item.id,{likes,comments})}));renderFeed()}
async function hydrateLiked(){liked=new Set();if(!currentUser)return;await Promise.all(items.map(async item=>{try{if((await getDoc(doc(db,"curtidas_publicacoes",item.id,"usuarios",currentUser.uid))).exists())liked.add(item.id)}catch{}}));renderFeed()}
async function loadFeed(){setFeedStatus("Carregando publicações...");try{const get=async(name,max)=>{try{return await getDocs(query(collection(db,name),where("aprovado","==",true),where("visibilidade","==","publico"),orderBy("criadoEm","desc"),limit(max)))}catch{return getDocs(query(collection(db,name),where("aprovado","==",true),where("visibilidade","==","publico"),limit(max)))}};const[p,v]=await Promise.all([get("publicacoes",22),get("videos",6)]),raw=[...p.docs.map(d=>({id:d.id,...d.data(),kind:"image",url:d.data().imagemUrl||d.data().imagem||""})),...v.docs.map(d=>({id:d.id,...d.data(),kind:"video",url:d.data().videoUrl||""}))].filter(x=>x.status!=="removido"&&((x.texto||x.legenda||"").trim()||x.url)).sort((a,b)=>millis(b.criadoEm)-millis(a.criadoEm)).slice(0,28);await Promise.all([...new Set(raw.map(x=>x.ownerUid).filter(Boolean))].map(profileOf));items=raw.map(x=>({...x,author:profiles.get(x.ownerUid)||{nome:x.nome||"Atleta",fotoUrl:fallback}}));renderFeed();setFeedStatus(`${items.length} publicação${items.length===1?"":"ões"} na rede.`);const idle=window.requestIdleCallback||((fn)=>setTimeout(fn,120));idle(()=>Promise.all([hydrateCounts(),hydrateLiked()]).catch(()=>{}))}catch(error){console.error("Comunidade:",error);feed.innerHTML='<div class="empty-feed"><strong>Não foi possível abrir o feed</strong><span>Atualize a página e tente novamente.</span></div>';setFeedStatus("Erro ao carregar publicações.","error")}}

photoInput?.addEventListener("change",()=>{const file=photoInput.files?.[0];photoPreview.classList.add("hidden");photoPreview.innerHTML="";if(!file)return;if(!["image/jpeg","image/png","image/webp"].includes(file.type)||file.size>25*1024*1024){photoInput.value="";setStatus(publishStatus,"Use JPG, PNG ou WEBP com até 25 MB.","error");return}const url=URL.createObjectURL(file);photoPreview.innerHTML=`<img src="${url}" alt="Prévia"><span>Arquivo original pronto para envio.</span>`;photoPreview.classList.remove("hidden");photoPreview.querySelector("img").onload=()=>URL.revokeObjectURL(url)});
postText?.addEventListener("input",()=>{if(postCounter)postCounter.textContent=String(postText.value.length)});
publishForm?.addEventListener("submit",async event=>{event.preventDefault();const button=publishForm.querySelector('button[type="submit"]'),body=text(postText?.value),file=photoInput?.files?.[0]||null;if(!currentUser){setStatus(publishStatus,"Entre na sua conta para publicar.","error");return}if(!body&&!file){setStatus(publishStatus,"Escreva uma legenda ou selecione uma foto.","error");return}button.disabled=true;setStatus(publishStatus,file?"Enviando foto original...":"Publicando...");try{const upload=file?await uploadCloudinary(file,{maxBytes:25*1024*1024,allowImage:true,allowVideo:false,tags:["cadastro-de-atletas","publicacoes","comunidade"]}):null,me=await profileOf(currentUser.uid),now=Timestamp.now(),visibilidade=await ownVisibility();await addDoc(collection(db,"publicacoes"),{ownerUid:currentUser.uid,ownerEmail:currentUser.email||"",nome:me.nome||currentUser.displayName||text($("postName")?.value)||"Atleta",texto:body,imagem:upload?.url||"",imagemUrl:upload?.url||"",imagemPath:upload?.path||"",imagemMime:upload?.mime||"image/jpeg",imagemTamanho:Number(upload?.size||0),legenda:body,tipo:"imagem",midias:[],hashtags:[],mencoes:[],armazenamento:upload?"cloudinary":"nenhum",visibilidade,aprovado:true,status:"publicado",criadoEm:now});publishForm.reset();if(postCounter)postCounter.textContent="0";photoPreview.classList.add("hidden");photoPreview.innerHTML="";setStatus(publishStatus,"Publicado no seu feed, na Comunidade e na página principal!","success");await loadFeed()}catch(error){console.error("Publicação:",error);setStatus(publishStatus,error?.message||"Não foi possível publicar.","error")}finally{button.disabled=false}});

async function loadComments(postId,list){list.innerHTML='<div class="comment-empty">Carregando...</div>';try{let snap;try{snap=await getDocs(query(collection(db,"comentarios_publicacoes"),where("publicacaoId","==",postId),where("aprovado","==",true),orderBy("criadoEm","asc"),limit(100)))}catch{snap=await getDocs(query(collection(db,"comentarios_publicacoes"),where("publicacaoId","==",postId),where("aprovado","==",true),limit(100)))}const rows=await Promise.all(snap.docs.map(async d=>{const x=d.data(),p=await profileOf(x.ownerUid);return`<article class="comment-item"><strong>${esc(p.nome||x.nome||"Atleta")}</strong><time>${esc(formatDate(x.criadoEm))}</time><p>${esc(x.texto||"")}</p></article>`}));list.innerHTML=rows.join("")||'<div class="comment-empty">Seja a primeira pessoa a comentar.</div>'}catch{list.innerHTML='<div class="comment-empty">Comentários indisponíveis.</div>'}}
feed?.addEventListener("click",async event=>{const button=event.target.closest("button"),card=event.target.closest(".post-card");if(!button||!card)return;const postId=card.dataset.postId,item=items.find(x=>x.id===postId);if(button.classList.contains("like-post")){if(!currentUser){setFeedStatus("Entre na sua conta para curtir.","error");return}const ref=doc(db,"curtidas_publicacoes",postId,"usuarios",currentUser.uid),c=cardCount(postId);try{if(liked.has(postId)){await deleteDoc(ref);liked.delete(postId);c.likes=Math.max(0,c.likes-1)}else{await setDoc(ref,{uid:currentUser.uid,criadoEm:Timestamp.now()});liked.add(postId);c.likes++;}counts.set(postId,c);renderFeed()}catch{setFeedStatus("Não foi possível registrar a curtida.","error")}return}if(button.classList.contains("toggle-comments")){const panel=card.querySelector(".comments-panel"),open=panel.classList.toggle("open");button.setAttribute("aria-expanded",String(open));if(open)await loadComments(postId,panel.querySelector("[data-comments-list]"));return}if(button.classList.contains("share-post")){const url=`${location.origin}${location.pathname}#post-${postId}`;try{if(navigator.share)await navigator.share({title:"Banco de Atletas",text:item?.texto||item?.legenda||"Publicação",url});else await navigator.clipboard.writeText(url)}catch{}return}if(button.classList.contains("report-post")){if(!currentUser){setFeedStatus("Entre para denunciar.","error");return}const reason=prompt("Motivo da denúncia:","Conteúdo inadequado");if(!reason?.trim())return;try{await addDoc(collection(db,"denuncias"),{alvoTipo:"publicacao",alvoId:postId,motivo:reason.trim().slice(0,300),detalhes:"",reportadoPorUid:currentUser.uid,criadoEm:Timestamp.now(),status:"pendente"});button.textContent="✓ DENÚNCIA ENVIADA";button.disabled=true}catch{setFeedStatus("Não foi possível enviar a denúncia.","error")}}});
feed?.addEventListener("submit",async event=>{const form=event.target.closest(".comment-form");if(!form)return;event.preventDefault();const status=form.querySelector(".comment-status"),button=form.querySelector("button"),body=text(form.elements.texto.value);if(!currentUser){status.textContent="Entre para comentar.";return}if(!body){status.textContent="Escreva um comentário.";return}button.disabled=true;try{const me=await profileOf(currentUser.uid);await addDoc(collection(db,"comentarios_publicacoes"),{ownerUid:currentUser.uid,ownerEmail:currentUser.email||"",publicacaoId:form.dataset.postId,nome:me.nome||currentUser.displayName||"Atleta",texto:body,parentCommentId:"",aprovado:true,status:"publicado",criadoEm:Timestamp.now()});form.reset();status.textContent="Comentário publicado.";const c=cardCount(form.dataset.postId);c.comments++;counts.set(form.dataset.postId,c);await loadComments(form.dataset.postId,form.closest(".comments-panel").querySelector("[data-comments-list]"))}catch{status.textContent="Não foi possível comentar."}finally{button.disabled=false}});
$("refreshFeed")?.addEventListener("click",loadFeed);
onAuthStateChanged(auth,user=>{currentUser=user;const accountLink=$("accountLink");if(accountLink){accountLink.hidden=true}if(items.length)hydrateLiked().catch(()=>{})});
loadFeed();
