import{getApp,getApps,initializeApp}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import{getAuth,onAuthStateChanged}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import{collection,deleteDoc,deleteField,doc,getDoc,getDocs,getFirestore,onSnapshot,query,serverTimestamp,setDoc,updateDoc}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
import{deleteObject,getStorage,ref as storageRef}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-storage.js";
const cfg={apiKey:"AIzaSyBMsuR0320Nz3asVRj5axXFvKJ5Ftz9COQ",authDomain:"jogadores-de-volei.firebaseapp.com",projectId:"jogadores-de-volei",storageBucket:"jogadores-de-volei.firebasestorage.app",messagingSenderId:"48728914064",appId:"1:48728914064:web:1dd7aeb705319886f74015"};
const app=getApps().length?getApp():initializeApp(cfg),db=getFirestore(app),auth=getAuth(app),storage=getStorage(app),ADMIN_EMAIL="swagtop411@gmail.com";
const list=document.getElementById("comunidadeAdminLista"),status=document.getElementById("comunidadeAdminStatus"),badge=document.getElementById("comunidadePendentesBadge");
const refs={post:collection(db,"publicacoes"),video:collection(db,"videos"),story:collection(db,"stories"),comment:collection(db,"comentarios_publicacoes")};let items=[],privacyWatchersStarted=false;
const text=v=>v==null?"":String(v).trim(),esc=v=>{const el=document.createElement("div");el.textContent=v==null?"":String(v);return el.innerHTML};
const dateValue=v=>{if(!v)return 0;if(typeof v.toMillis==="function")return v.toMillis();if(v.seconds)return Number(v.seconds)*1000;const p=Date.parse(v);return Number.isNaN(p)?0:p};
const formatDate=v=>dateValue(v)?new Intl.DateTimeFormat("pt-BR",{dateStyle:"medium",timeStyle:"short"}).format(new Date(dateValue(v))):"Agora";
const label={post:"PUBLICAÇÃO",story:"STORY",video:"VÍDEO",comment:"COMENTÁRIO"};
const collectionName={post:"publicacoes",story:"stories",video:"videos",comment:"comentarios_publicacoes"};
function setStatus(message,type=""){if(!status)return;status.textContent=message;status.className=("status "+type).trim()}
function pendingCount(){return items.filter(x=>x.item.aprovado!==true||x.item.status==="pendente").length}
function updateBadge(){if(badge)badge.textContent=String(pendingCount())}
async function isAdminUser(user){if(!user)return false;if(String(user.email||"").trim().toLowerCase()===ADMIN_EMAIL)return true;try{return(await user.getIdTokenResult())?.claims?.admin===true}catch{return false}}
function mediaUrl(item){return text(item.imagemUrl||item.imagem||item.mediaUrl||item.videoUrl)}
function card(row){
 const {type,item}=row,media=mediaUrl(item),isVideo=type==="video"||String(item.mediaType||"").startsWith("video"),published=item.aprovado===true&&item.status!=="pendente",archived=type==="story"&&dateValue(item.expiraEm)>0&&dateValue(item.expiraEm)<=Date.now();
 const mediaMarkup=media?(isVideo?`<video class="community-moderation-image" src="${esc(media)}" controls preload="metadata"></video>`:`<img class="community-moderation-image" src="${esc(media)}" alt="Mídia de ${esc(item.nome||"Atleta")}" loading="lazy">`):"";
 const body=esc(item.texto||item.legenda||"");
 const publishButton=!published&&type!=="comment"?'<button class="community-approve-button" type="button" data-community-action="publish">✓ PUBLICAR</button>':(!published&&type==="comment"?'<button class="community-approve-button" type="button" data-community-action="publish">✓ APROVAR</button>':"");
 const state=archived?"ARQUIVADO":published?"PUBLICADO":"PENDENTE";
 return `<article class="community-moderation-card" data-type="${type}" data-id="${esc(item.id)}"><div><span class="community-moderation-type">${label[type]} · ${state}</span><h3>${esc(item.nome||"Atleta")}</h3><p>${body||"Sem legenda."}</p><div class="community-moderation-meta">${esc(formatDate(item.criadoEm))}</div>${mediaMarkup}</div><div class="community-moderation-actions">${publishButton}<button class="community-approve-button" type="button" data-community-action="edit">✎ EDITAR</button><button class="community-reject-button" type="button" data-community-action="delete">✕ EXCLUIR</button></div></article>`
}
function render(){updateBadge();if(!list)return;if(!items.length){list.innerHTML='<div class="community-admin-empty">Nenhum conteúdo publicado ainda.</div>';return}const order={post:1,video:2,story:3,comment:4},groups={post:items.filter(x=>x.type==="post"),video:items.filter(x=>x.type==="video"),story:items.filter(x=>x.type==="story"),comment:items.filter(x=>x.type==="comment")};list.innerHTML=Object.keys(groups).filter(k=>groups[k].length).sort((a,b)=>order[a]-order[b]).map(k=>`<div class="community-admin-separator">${label[k]}S (${groups[k].length})</div><div class="community-admin-list">${groups[k].map(card).join("")}</div>`).join("")}
async function loadCommunity(){if(!list)return;list.innerHTML='<p class="subtitulo">Carregando conteúdo...</p>';try{const snaps=await Promise.all(Object.entries(refs).map(async([type,ref])=>({type,snapshot:await getDocs(ref)})));items=snaps.flatMap(({type,snapshot})=>snapshot.docs.map(d=>({type,id:d.id,item:{id:d.id,...d.data()}}))).sort((a,b)=>dateValue(b.item.criadoEm)-dateValue(a.item.criadoEm));render();setStatus(`${items.length} item(ns) na comunidade.`,"success")}catch(error){console.error("Comunidade ADM:",error);list.innerHTML='<div class="community-admin-error">Não foi possível carregar a comunidade.</div>';setStatus("Erro ao carregar a comunidade.","error")}}
function editValue(type,item){return type==="post"?text(item.legenda||item.texto):text(item.legenda||item.texto)}
async function editItem(type,id,item){const atual=editValue(type,item),novo=window.prompt(type==="comment"?"Editar comentário:":"Editar legenda:",atual);if(novo===null)return;const value=String(novo).trim().slice(0,type==="comment"?500:2200),ref=doc(db,collectionName[type],id);if(type==="post")await updateDoc(ref,{legenda:value,texto:value});else if(type==="comment")await updateDoc(ref,{texto:value});else await updateDoc(ref,{legenda:value})}
async function publishLegacy(type,id){const ref=doc(db,collectionName[type],id);await updateDoc(ref,{aprovado:true,status:type==="comment"?"ativo":"publicado",aprovadoEm:serverTimestamp()})}
function mediaPathFor(type,item){if(type==="post")return text(item.imagemPath);if(type==="story")return text(item.mediaPath);if(type==="video")return text(item.videoPath);return""}
async function removeStoredMedia(type,item){if(text(item.armazenamento).toLowerCase()==="cloudinary"||mediaUrl(item).includes("res.cloudinary.com"))return;const path=mediaPathFor(type,item);if(!path)return;try{await deleteObject(storageRef(storage,path))}catch(error){if(error?.code!=="storage/object-not-found")console.warn("Falha ao remover mídia antiga:",error)}}
list?.addEventListener("click",async event=>{const button=event.target.closest("button[data-community-action]"),cardEl=event.target.closest("[data-type][data-id]");if(!button||!cardEl)return;const type=cardEl.dataset.type,id=cardEl.dataset.id,action=button.dataset.communityAction,current=items.find(x=>x.type===type&&x.id===id)?.item||{};button.disabled=true;try{if(action==="edit")await editItem(type,id,current);else if(action==="publish")await publishLegacy(type,id);else if(action==="delete"){if(!window.confirm("Excluir este conteúdo da rede?")){button.disabled=false;return}await removeStoredMedia(type,current);await deleteDoc(doc(db,collectionName[type],id))}await loadCommunity();setStatus(action==="edit"?"Conteúdo editado.":action==="publish"?"Conteúdo publicado.":"Conteúdo excluído.","success")}catch(error){console.error("Gerenciamento da comunidade:",error);button.disabled=false;setStatus("Não foi possível concluir a ação.","error")}});

function privatePayload(data,fields){const payload={};for(const field of fields)if(Object.prototype.hasOwnProperty.call(data,field))payload[field]=data[field];return payload}
async function migrateSensitiveDocument(collectionNameValue,snapshot,fields,marker=true){const data=snapshot.data()||{},payload=privatePayload(data,fields);if(!Object.keys(payload).length)return;await setDoc(doc(db,collectionNameValue,snapshot.id,"privado","dados"),{...payload,privacidadeMigradaEm:serverTimestamp()},{merge:true});const removals={};for(const field of Object.keys(payload))removals[field]=deleteField();if(marker)removals.privacidadeV3=serverTimestamp();await updateDoc(snapshot.ref,removals)}
async function sanitizeSnapshot(snapshot,collectionNameValue,fields,marker=true){for(const change of snapshot.docChanges()){if(change.type==="removed")continue;try{await migrateSensitiveDocument(collectionNameValue,change.doc,fields,marker)}catch(error){console.warn("Privacidade V3:",collectionNameValue,error?.code||error)}}}
function startPrivacyWatchers(){if(privacyWatchersStarted)return;privacyWatchersStarted=true;onSnapshot(collection(db,"atletas"),snap=>void sanitizeSnapshot(snap,"atletas",["nascimento","ownerEmail","ownerDisplayName","valorPlano","planoStatus","pagamentoConfirmado"]));onSnapshot(collection(db,"equipes"),snap=>void sanitizeSnapshot(snap,"equipes",["contato","responsavel","ownerEmail","valorPlano","planoStatus","pagamentoConfirmado"]));onSnapshot(collection(db,"perfis"),snap=>void sanitizeSnapshot(snap,"perfis",["nascimento","contato","email","plano","planoId","valorPlano","planoStatus","pagamentoConfirmado","status","legadoAtletaId","ownerEmail","ownerDisplayName","atualizadoEm","criadoEm"],false))}
// Stories expirados não são apagados. Eles deixam a faixa ativa após 24h e permanecem no arquivo público do perfil até exclusão manual do dono ou ADM.
async function cleanupExpiredStories(){return}
function locationParts(cidade,uf){let city=text(cidade),state=text(uf).toUpperCase();const m=city.match(/^([A-Z]{2})\s*[-,]\s*(.+)$/i);if(m){if(!state)state=m[1].toUpperCase();city=m[2].trim()}return{cidade:city,uf:state}}
document.addEventListener("click",async event=>{const button=event.target.closest?.(".claim-approve");if(!button)return;event.preventDefault();event.stopImmediatePropagation();if(!(await isAdminUser(auth.currentUser)))return;const claimId=button.dataset.id;if(!claimId)return;button.disabled=true;try{const claimSnap=await getDoc(doc(db,"reivindicacoes_perfis",claimId));if(!claimSnap.exists())throw new Error("Solicitação não encontrada.");const claim=claimSnap.data()||{},athleteId=String(claim.perfilId||"");if(!athleteId)throw new Error("Perfil não identificado.");const athleteRef=doc(db,"atletas",athleteId),athleteSnap=await getDoc(athleteRef);if(!athleteSnap.exists())throw new Error("Perfil do atleta não encontrado.");const athlete=athleteSnap.data()||{};if(athlete.ownerUid&&athlete.ownerUid!==claim.solicitanteUid)throw new Error("Este perfil já pertence a outra conta.");if(!window.confirm("Vincular este perfil à conta solicitante?")){button.disabled=false;return}const loc=locationParts(athlete.cidade,athlete.uf),publicProfile={uid:claim.solicitanteUid,nome:athlete.nome||claim.perfilNome||"Atleta",cidade:loc.cidade||"Não informado",uf:loc.uf||"SP",modalidade:athlete.modalidade||"Vôlei de praia",posicao:athlete.posicao||"Universal",categoria:["Iniciante","Intermediário","Avançado"].includes(athlete.categoria)?athlete.categoria:"Iniciante",time:athlete.time||"Sem equipe",bio:athlete.bio||athlete.observacoes||"",fotoUrl:athlete.foto||"",fotoPath:"",capaUrl:"",capaPath:"",historicoCampeonatos:Array.isArray(athlete.historicoCampeonatos)?athlete.historicoCampeonatos:[]},privateProfile={nascimento:athlete.nascimento||"",contato:athlete.contato||"",email:claim.solicitanteEmail||"",plano:athlete.plano||"Gratuito",planoId:athlete.planoId||"gratuito",valorPlano:Number(athlete.valorPlano||0),planoStatus:athlete.planoStatus||"ativo",pagamentoConfirmado:athlete.pagamentoConfirmado===true,legadoAtletaId:athleteId,atualizadoEm:serverTimestamp()};await setDoc(doc(db,"perfis",claim.solicitanteUid),publicProfile,{merge:false});try{await setDoc(doc(db,"perfis",claim.solicitanteUid,"privado","dados"),privateProfile,{merge:true})}catch{await setDoc(doc(db,"atletas",athleteId,"privado","dados"),privateProfile,{merge:true})}await updateDoc(athleteRef,{ownerUid:claim.solicitanteUid,atualizadoEm:serverTimestamp()});await updateDoc(claimSnap.ref,{status:"aprovada",analisadoPorUid:auth.currentUser.uid,analisadoEm:serverTimestamp()});document.getElementById("btnAtualizarReivindicacoes")?.click()}catch(error){console.error("Reivindicação segura:",error);alert(error?.message||"Não foi possível aprovar a reivindicação.");button.disabled=false}},true);
document.getElementById("btnAtualizarComunidade")?.addEventListener("click",loadCommunity);
onAuthStateChanged(auth,async user=>{if(!(await isAdminUser(user)))return;startPrivacyWatchers();void cleanupExpiredStories();void loadCommunity()});