import{initializeApp,getApps,getApp}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import{getAuth,onAuthStateChanged}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
const firebaseConfig={apiKey:"AIzaSyBMsuR0320Nz3asVRj5axXFvKJ5Ftz9COQ",authDomain:"jogadores-de-volei.firebaseapp.com",projectId:"jogadores-de-volei",storageBucket:"jogadores-de-volei.firebasestorage.app",messagingSenderId:"48728914064",appId:"1:48728914064:web:1dd7aeb705319886f74015",measurementId:"G-K033D1K41Y"};
const app=getApps().length?getApp():initializeApp(firebaseConfig);
const auth=getAuth(app);
const GA4_PROPERTY_ID="532490731";
const GA4_PROXY_URL="https://script.google.com/macros/s/AKfycbxFZVm1NJ910xWjkTmG1_RTWhwirD_pCHZIogWW16AN-O4UoDf_O86-cgGR7-SbiQcAbw/exec";
const GA4_TOKEN="se9i3Pf8Vc8dI-FqXwoolJstmaEjWXD6";
const $=id=>document.getElementById(id);
const fmt=n=>new Intl.NumberFormat("pt-BR").format(Number(n)||0);
const esc=v=>{const d=document.createElement("div");d.textContent=v??"";return d.innerHTML};
function style(){if($("ga4style"))return;const s=document.createElement("style");s.id="ga4style";s.textContent=`.analytics-cta{min-height:52px!important;padding:15px 24px!important;font-size:14px!important}.ga4-source{font-size:11px;color:#9da39c;margin-top:8px}.ga4-source b{color:#f2cc72}.ga4-refresh{margin-top:14px;padding:12px 16px;border:0;border-radius:10px;background:linear-gradient(135deg,#f2cc72,#bd8425);color:#15130e;font-weight:900;cursor:pointer}.ga4-loading{padding:30px;text-align:center;color:#c9cec8}.ga4-error{padding:18px;border-radius:12px;background:rgba(220,80,70,.10);border:1px solid rgba(220,80,70,.25);color:#f0c8c4;line-height:1.6}.ga4-card strong{font-size:26px!important}.ga4-bars{display:grid;gap:9px}.ga4-bar{display:grid;grid-template-columns:100px 1fr 45px;gap:8px;align-items:center;font-size:11px}.ga4-bar span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.ga4-track,.ga4-day-track{height:11px;background:#0b0e0c;border-radius:8px;overflow:hidden}.ga4-track i,.ga4-day-track i{display:block;height:100%;background:linear-gradient(90deg,#a96d13,#f2cc72);border-radius:8px}.ga4-bar strong,.ga4-day strong{text-align:right;color:#f2cc72}.ga4-days{display:grid;gap:8px}.ga4-day{display:grid;grid-template-columns:52px 1fr 45px;gap:8px;align-items:center;font-size:10px;color:#9da39c}@media(max-width:700px){.analytics-cta{width:100%;font-size:13px!important}.ga4-bar{grid-template-columns:82px 1fr 42px}}`;document.head.appendChild(s)}
function bars(rows,max=8){const a=(rows||[]).slice(0,max),m=Math.max(1,...a.map(r=>Number(r.metrics?.[0]||0)));return `<div class="ga4-bars">${a.map(r=>{const n=r.dimensions?.[0]||"(não informado)",v=Number(r.metrics?.[0]||0);return `<div class="ga4-bar"><span title="${esc(n)}">${esc(n)}</span><div class="ga4-track"><i style="width:${v?Math.max(3,v/m*100):0}%"></i></div><strong>${fmt(v)}</strong></div>`}).join("")}</div>`}
function render(d){const p=$("estatisticasView")?.querySelector(".stats-panel");if(!p)return;const t=d.totals||{},days=d.daily||[],m=Math.max(1,...days.map(r=>Number(r.metrics?.[0]||0)));p.innerHTML=`<div class="stats-intro"><h2>📊 Google Analytics 4</h2><p>Dados reais da propriedade <strong>${GA4_PROPERTY_ID}</strong>, consultados pela API oficial do Google Analytics.</p><button id="btnAtualizarGA4" class="ga4-refresh" type="button">🔄 Atualizar agora</button><div class="ga4-source">Fonte: <b>Google Analytics Data API</b> · ${new Date(d.updatedAt||Date.now()).toLocaleString("pt-BR")}</div></div><div class="stats-grid"><div class="stats-card ga4-card"><span class="icon">👥</span><strong>${fmt(t.activeUsers)}</strong><span>Usuários ativos · 7 dias</span></div><div class="stats-card ga4-card"><span class="icon">🆕</span><strong>${fmt(t.newUsers)}</strong><span>Novos usuários · 7 dias</span></div><div class="stats-card ga4-card"><span class="icon">🟢</span><strong>${fmt(t.realtimeUsers)}</strong><span>Usuários em tempo real</span></div><div class="stats-card ga4-card"><span class="icon">📅</span><strong>${fmt(t.sessions)}</strong><span>Sessões · 7 dias</span></div><div class="stats-card ga4-card"><span class="icon">👁️</span><strong>${fmt(t.views)}</strong><span>Visualizações · 7 dias</span></div><div class="stats-card ga4-card"><span class="icon">🎯</span><strong>${fmt(t.events)}</strong><span>Eventos · 7 dias</span></div></div><div class="stats-intro" style="margin-top:18px"><h2>📈 Usuários por dia</h2><div class="ga4-days">${days.map(r=>{const dte=r.dimensions?.[0]||"",v=Number(r.metrics?.[0]||0),label=dte.length===8?`${dte.slice(6)}/${dte.slice(4,6)}`:dte;return `<div class="ga4-day"><span>${esc(label)}</span><div class="ga4-day-track"><i style="width:${v?Math.max(4,v/m*100):0}%"></i></div><strong>${fmt(v)}</strong></div>`}).join("")}</div></div><div class="stats-grid" style="margin-top:18px"><div class="stats-card"><h3>📱 Dispositivos</h3>${bars(d.devices)}</div><div class="stats-card"><h3>🌎 Países</h3>${bars(d.countries)}</div></div><div class="stats-grid" style="margin-top:18px"><div class="stats-card"><h3>📄 Páginas mais vistas</h3>${bars(d.pages)}</div><div class="stats-card"><h3>⚡ Eventos</h3>${bars(d.events,12)}</div></div><div class="stats-note"><strong>Dados oficiais:</strong> este painel não calcula números a partir do Firebase. Os valores são retornados pelo Google Analytics 4. <a href="https://analytics.google.com/analytics/web/#/a390906538p532490731/" target="_blank" rel="noopener" style="color:#f2cc72">Abrir Google Analytics ↗</a></div>`;$("btnAtualizarGA4").onclick=load}
function setup(msg){const p=$("estatisticasView")?.querySelector(".stats-panel");if(!p)return;p.innerHTML=`<div class="stats-intro"><h2>📊 Google Analytics 4</h2><p>O painel está tentando buscar os dados reais do GA4.</p><div class="ga4-error"><strong>⚠️ Não foi possível carregar os dados.</strong><br>${esc(msg||"Erro desconhecido.")}<br><button class="ga4-refresh" type="button" onclick="location.reload()">🔄 Tentar novamente</button></div></div>`}
function loading(){const p=$("estatisticasView")?.querySelector(".stats-panel");if(p)p.innerHTML=`<div class="stats-intro"><h2>📊 Google Analytics 4</h2><div class="ga4-loading">⏳ Carregando dados reais do Google Analytics...</div></div>`}
function jsonp(url){return new Promise((resolve,reject)=>{const n="ga4cb"+Date.now()+Math.random().toString(36).slice(2),s=document.createElement("script"),tm=setTimeout(()=>{clean();reject(new Error("Tempo esgotado ao consultar o Google Analytics."))},20000);function clean(){clearTimeout(tm);delete window[n];s.remove()}window[n]=x=>{clean();resolve(x)};s.onerror=()=>{clean();reject(new Error("Falha ao conectar ao proxy do Google Apps Script."))};s.src=url+(url.includes("?")?"&":"?")+"callback="+n;document.body.appendChild(s)})}
async function load(){if(!GA4_PROXY_URL){setup("GA4_PROXY_URL não configurada.");return}loading();try{const sep=GA4_PROXY_URL.includes("?")?"&":"?";const d=await jsonp(`${GA4_PROXY_URL}${sep}token=${encodeURIComponent(GA4_TOKEN)}`);if(!d?.ok)throw new Error(d?.error||"O proxy não retornou uma resposta válida.");render(d)}catch(e){console.error("GA4:",e);setup(e.message)}}
function init(){style();onAuthStateChanged(auth,u=>{if(u)load();else setup("Usuário administrativo não autenticado.")})}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();