import{initializeApp}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import{getAuth,onAuthStateChanged}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import{getFirestore,collection,getDocs,query,orderBy,limit}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";

const firebaseConfig={apiKey:"AIzaSyBMsuR0320Nz3asVRj5axXFvKJ5Ftz9COQ",authDomain:"jogadores-de-volei.firebaseapp.com",projectId:"jogadores-de-volei",storageBucket:"jogadores-de-volei.firebasestorage.app",messagingSenderId:"48728914064",appId:"1:48728914064:web:1dd7aeb705319886f74015",measurementId:"G-K033D1K41Y"};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),$=id=>document.getElementById(id);
const esc=v=>{const d=document.createElement("div");d.textContent=v??"";return d.innerHTML};

function format(n){return new Intl.NumberFormat("pt-BR").format(Number(n)||0)}
function dayKey(d){return new Date(d).toLocaleDateString("pt-BR",{day:"2-digit",month:"2-digit"})}
function buildPanel(){const p=$("estatisticasView");if(!p)return;const panel=p.querySelector(".stats-panel");if(!panel)return;panel.innerHTML=`<div class="stats-intro"><h2>📊 Estatísticas do site</h2><p>Dados próprios do Banco de Atletas. Atualizados diretamente a partir das visitas e ações registradas no site, sem precisar abrir o Google Analytics.</p><button id="btnAtualizarStats" class="btn-primary" type="button" style="margin-top:14px">🔄 Atualizar agora</button><span id="statsAtualizado" style="display:block;margin-top:9px;color:#858c85;font-size:10px"></span></div><div id="statsErro" class="status"></div><div class="stats-grid"><div class="stats-card"><span class="icon">👥</span><strong id="stUsuarios">--</strong><span>Visitantes únicos nos últimos 7 dias.</span></div><div class="stats-card"><span class="icon">🟢</span><strong id="stAgora">--</strong><span>Visitantes ativos nos últimos 5 minutos.</span></div><div class="stats-card"><span class="icon">👁️</span><strong id="stViews">--</strong><span>Visualizações de páginas nos últimos 7 dias.</span></div><div class="stats-card"><span class="icon">🎯</span><strong id="stAcoes">--</strong><span>Ações importantes realizadas pelos visitantes.</span></div><div class="stats-card"><span class="icon">📱</span><strong id="stCelular">--</strong><span>Acessos feitos pelo celular.</span></div><div class="stats-card"><span class="icon">💻</span><strong id="stComputador">--</strong><span>Acessos feitos por computador ou tablet.</span></div></div><div class="stats-intro" style="margin-top:18px"><h2>📈 Últimos 7 dias</h2><div id="statsDias" class="stats-days"></div></div><div class="stats-grid"><div class="stats-card"><span class="icon">📝</span><strong id="stCadastros">--</strong><span>Cadastros abertos ou enviados.</span></div><div class="stats-card"><span class="icon">💬</span><strong id="stWhatsapp">--</strong><span>Cliques no WhatsApp.</span></div><div class="stats-card"><span class="icon">🔎</span><strong id="stPesquisas">--</strong><span>Pesquisas de atletas.</span></div><div class="stats-card"><span class="icon">🏆</span><strong id="stCamp">--</strong><span>Cliques em campeonatos.</span></div><div class="stats-card"><span class="icon">🏐</span><strong id="stVer">--</strong><span>Cliques em Ver Atletas.</span></div><div class="stats-card"><span class="icon">📄</span><strong id="stPaginas">--</strong><span>Páginas com maior movimento.</span></div></div><div class="stats-note"><strong>Privacidade:</strong> o painel usa um identificador aleatório armazenado apenas no navegador para estimar visitantes únicos. Não registra nome, telefone, e-mail ou conteúdo de formulários.</div>`;$("btnAtualizarStats").onclick=loadStats}

async function loadStats(){const erro=$("statsErro");if(erro){erro.textContent="";erro.className="status"}try{const snap=await getDocs(query(collection(db,"site_stats"),orderBy("criadoEm","desc"),limit(5000)));const now=Date.now(),week=now-7*86400000,active=now-5*60000,events=snap.docs.map(d=>d.data()).filter(e=>e.criadoEm?.toDate).map(e=>({...e,ms:e.criadoEm.toDate().getTime()})).filter(e=>e.ms>=week);const users=new Set(events.map(e=>e.visitante).filter(Boolean));const activeUsers=new Set(events.filter(e=>e.ms>=active).map(e=>e.visitante).filter(Boolean));const views=events.filter(e=>e.nome==="page_view").length;const actions=events.filter(e=>e.nome!=="page_view").length;const cel=events.filter(e=>e.dispositivo==="Celular").length;const comp=events.filter(e=>e.dispositivo!=="Celular").length;const count=n=>events.filter(e=>e.nome===n).length;["stUsuarios","stAgora","stViews","stAcoes","stCelular","stComputador"].forEach((id,i)=>$(id).textContent=format([users.size,activeUsers.size,views,actions,cel,comp][i]));$("stCadastros").textContent=format(count("cadastro_aberto")+count("cadastro_enviado"));$("stWhatsapp").textContent=format(count("whatsapp_click"));$("stPesquisas").textContent=format(count("pesquisa_atletas"));$("stCamp").textContent=format(count("campeonatos_click"));$("stVer").textContent=format(count("ver_atletas_click"));const pages={};events.forEach(e=>{if(e.nome==="page_view")pages[e.pagina]=(pages[e.pagina]||0)+1});$("stPaginas").textContent=Object.entries(pages).sort((a,b)=>b[1]-a[1]).slice(0,3).map(([p,n])=>`${p.replace("/","")||"início"}: ${n}`).join(" • ")||"Sem dados";const days=[];for(let i=6;i>=0;i--){const start=new Date();start.setHours(0,0,0,0);start.setDate(start.getDate()-i);const end=new Date(start);end.setDate(end.getDate()+1);const n=events.filter(e=>e.ms>=start.getTime()&&e.ms<end.getTime()).length;days.push({label:dayKey(start),n})}const max=Math.max(1,...days.map(x=>x.n));$("statsDias").innerHTML=days.map(x=>`<div class="stats-day"><span>${esc(x.label)}</span><div><i style="width:${Math.max(4,x.n/max*100)}%"></i></div><strong>${format(x.n)}</strong></div>`).join("");$("statsAtualizado").textContent=`Atualizado em ${new Date().toLocaleString("pt-BR")}`}
catch(e){console.error(e);if(erro){erro.textContent=`Não foi possível carregar as estatísticas (${e.code||"erro"}).`;erro.className="status erro"}}}

function init(){buildPanel();onAuthStateChanged(auth,user=>{if(user)loadStats()})}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
