import "./site-v5.js?v=20260904-2";
import { getApp, getApps, initializeApp } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import { collection, documentId, getDocs, getFirestore, limit, orderBy, query, startAfter, where } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
import { feedImageUrl, thumbImageUrl } from "./media-utils.js?v=20260907-1";

const cfg={apiKey:"AIzaSyBMsuR0320Nz3asVRj5axXFvKJ5Ftz9COQ",authDomain:"jogadores-de-volei.firebaseapp.com",projectId:"jogadores-de-volei",storageBucket:"jogadores-de-volei.firebasestorage.app",messagingSenderId:"48728914064",appId:"1:48728914064:web:1dd7aeb705319886f74015"};
const app=getApps().length?getApp():initializeApp(cfg),db=getFirestore(app);
const $=id=>document.getElementById(id);
const esc=value=>{const d=document.createElement("div");d.textContent=value??"";return d.innerHTML};
const norm=value=>String(value??"").trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/\s+/g," ");
const ms=value=>value?.toMillis?.()??(value?.seconds?Number(value.seconds)*1000:new Date(value||0).getTime()||0);
const fallback="data:image/svg+xml;charset=UTF-8,"+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="180" height="180"><rect width="180" height="180" fill="#18221d"/><text x="90" y="112" text-anchor="middle" font-size="64">🏐</text></svg>');
const PAGE_SIZE=70,SEARCH_TARGET=18,AUTO_SEARCH_PAGES=2,PROFILE_RENDER_LIMIT=80;
const FILTER_IDS={modalidade:"exploreModalidade",categoria:"exploreCategoria",posicao:"explorePosicao",cidade:"exploreCidade",time:"exploreEquipe"};
const params=new URLSearchParams(location.search);

let profiles=[],media=[];
let queryRaw=params.get("q")||"",queryText=norm(queryRaw);
let type=["all","profiles","images","videos"].includes(params.get("type"))?params.get("type"):"all";
let sort=["relevance","name","complete"].includes(params.get("sort"))?params.get("sort"):"relevance";
const filters={modalidade:params.get("modalidade")||"",categoria:params.get("categoria")||"",posicao:params.get("posicao")||"",cidade:params.get("cidade")||"",time:params.get("equipe")||""};
const legacyMap=new Map(),profileMap=new Map();
let legacyCursor=null,profileCursor=null,legacyDone=false,profileDone=false,loadingMore=false,searchTimer=0,searchGeneration=0,suggestionIndex=-1;

function listField(value,fallbackValue=""){if(Array.isArray(value))return value.map(String).map(x=>x.trim()).filter(Boolean);if(String(value||"").trim())return String(value).split(",").map(x=>x.trim()).filter(Boolean);return fallbackValue?[String(fallbackValue).trim()].filter(Boolean):[]}
function normalizeAthlete(id,data,source){const a=data||{},positions=listField(a.posicoes,a.posicao),modalities=listField(a.modalidades,a.modalidade),ownerUid=String(a.ownerUid||a.uid||(source==="perfil-social"?id:"")).trim();return{id,uid:source==="perfil-social"?id:ownerUid,ownerUid,fonte:source,nome:String(a.nome||"").trim(),fotoUrl:String(a.fotoUrl||a.foto||"").trim(),cidade:String(a.cidade||"").trim(),uf:String(a.uf||"").trim(),modalidade:modalities.join(", "),categoria:String(a.categoria||a.nivel||"").trim(),posicao:positions.join(", "),time:String(a.time||a.equipe||"").trim(),bio:String(a.bio||"").trim(),status:String(a.status||"ativo").trim()}}
function mergeAthlete(base,next){const out={...base};for(const [key,value] of Object.entries(next)){if(value!==""&&value!=null)out[key]=value}out.id=base.id;out.fonte="perfil-social";return out}
function rebuildProfiles(){const legacy=[...legacyMap.values()].filter(p=>p.nome&&norm(p.status)!=="inativo"),social=[...profileMap.values()].filter(p=>p.nome&&norm(p.status)!=="inativo"),merged=legacy.map(p=>({...p})),byUid=new Map(merged.filter(p=>p.ownerUid).map(p=>[p.ownerUid,p]));for(const p of social){const existing=byUid.get(p.ownerUid);if(existing)Object.assign(existing,mergeAthlete(existing,p));else merged.push({...p})}profiles=merged.sort((a,b)=>String(a.nome||"").localeCompare(String(b.nome||""),"pt-BR"));refreshFilterOptions();renderAll();syncLoadMore()}
function profileHref(p){if(p.fonte==="perfil-social"&&p.uid)return `perfil-social.html?uid=${encodeURIComponent(p.uid)}`;return `perfil.html?id=${encodeURIComponent(p.id)}`}
function profilePhoto(p){return p?.fotoUrl?thumbImageUrl(p.fotoUrl):fallback}
function profileSearchText(p){return norm([p.nome,p.cidade,p.uf,p.modalidade,p.posicao,p.categoria,p.time,p.bio].filter(Boolean).join(" "))}
function queryTokens(){return queryText.split(" ").filter(Boolean)}
function completeness(p){let score=0;if(p.fotoUrl)score+=22;if(p.cidade)score+=13;if(p.modalidade)score+=14;if(p.categoria)score+=14;if(p.posicao)score+=14;if(p.time)score+=10;if(p.bio)score+=8;if(p.uf)score+=5;return Math.min(100,score)}
function relevance(p){if(!queryText)return completeness(p)/10;const name=norm(p.nome),fields={cidade:norm(`${p.cidade} ${p.uf}`),modalidade:norm(p.modalidade),posicao:norm(p.posicao),categoria:norm(p.categoria),time:norm(p.time),bio:norm(p.bio)},tokens=queryTokens();let score=completeness(p)/25;if(name===queryText)score+=120;else if(name.startsWith(queryText))score+=85;else if(name.includes(queryText))score+=55;for(const token of tokens){if(name===token)score+=28;else if(name.startsWith(token))score+=22;else if(name.includes(token))score+=17;if(fields.cidade.includes(token))score+=12;if(fields.modalidade.includes(token))score+=11;if(fields.posicao.includes(token))score+=11;if(fields.categoria.includes(token))score+=10;if(fields.time.includes(token))score+=9;if(fields.bio.includes(token))score+=3}return score}
function matchesFilters(p){for(const [key,value] of Object.entries(filters)){if(value&&!norm(p[key]).includes(norm(value)))return false}return true}
function matchesQuery(p){if(!queryText)return true;const text=profileSearchText(p);return queryTokens().every(token=>text.includes(token))}
function filteredProfiles(){const list=profiles.filter(p=>matchesFilters(p)&&matchesQuery(p));return list.sort((a,b)=>{if(sort==="name")return a.nome.localeCompare(b.nome,"pt-BR");if(sort==="complete")return completeness(b)-completeness(a)||a.nome.localeCompare(b.nome,"pt-BR");return relevance(b)-relevance(a)||completeness(b)-completeness(a)||a.nome.localeCompare(b.nome,"pt-BR")})}
function mediaSearchText(m,p){return norm([m.caption,p?.nome,p?.cidade,p?.uf,p?.time,p?.modalidade,p?.categoria,p?.posicao,m.kind].filter(Boolean).join(" "))}
function matchesMedia(item){if(type==="images"&&item.kind!=="image")return false;if(type==="videos"&&item.kind!=="video")return false;const p=profiles.find(x=>x.ownerUid&&x.ownerUid===item.ownerUid);if(p&&!matchesFilters(p))return false;if(queryText&&!queryTokens().every(token=>mediaSearchText(item,p).includes(token)))return false;return true}
function activeSearch(){return !!queryText||Object.values(filters).some(Boolean)}
function uniqueValues(key){const values=new Map();for(const p of profiles){for(const raw of listField(p[key])){const n=norm(raw);if(n&&!values.has(n))values.set(n,raw)}}return [...values.values()].sort((a,b)=>a.localeCompare(b,"pt-BR"))}

function refreshFilterOptions(){for(const [key,id] of Object.entries(FILTER_IDS)){const select=$(id);if(!select)continue;const current=filters[key],label=select.dataset.label||select.options[0]?.textContent||"Todos";select.innerHTML=`<option value="">${esc(label)}</option>`+uniqueValues(key).map(value=>`<option value="${esc(value)}"${norm(value)===norm(current)?" selected":""}>${esc(value)}</option>`).join("");if(current&&!select.value){select.insertAdjacentHTML("beforeend",`<option value="${esc(current)}" selected>${esc(current)}</option>`)}}}
function syncUrl(){const out=new URLSearchParams();if(queryRaw.trim())out.set("q",queryRaw.trim());if(type!=="all")out.set("type",type);if(sort!=="relevance")out.set("sort",sort);if(filters.modalidade)out.set("modalidade",filters.modalidade);if(filters.categoria)out.set("categoria",filters.categoria);if(filters.posicao)out.set("posicao",filters.posicao);if(filters.cidade)out.set("cidade",filters.cidade);if(filters.time)out.set("equipe",filters.time);history.replaceState(null,"",`${location.pathname}${out.size?`?${out}`:""}`)}
function renderChips(){const box=$("exploreChips");if(!box)return;const items=[];if(queryRaw.trim())items.push({key:"q",label:`Busca: ${queryRaw.trim()}`});for(const [key,value] of Object.entries(filters))if(value)items.push({key,label:value});if(type!=="all")items.push({key:"type",label:type==="profiles"?"Atletas":type==="images"?"Fotos":"Vídeos"});box.innerHTML=items.map(x=>`<span class="explore-chip">${esc(x.label)}<button type="button" data-clear-filter="${esc(x.key)}" aria-label="Remover filtro">×</button></span>`).join("");$("exploreReset")?.toggleAttribute("hidden",items.length===0)}
function renderInsights(){const cities=new Set(),modalities=new Set(),teams=new Set();for(const p of profiles){if(p.cidade)cities.add(norm(p.cidade));listField(p.modalidade).forEach(x=>modalities.add(norm(x)));if(p.time)teams.add(norm(p.time))}const vals={exploreInsightAthletes:profiles.length,exploreInsightCities:cities.size,exploreInsightModalities:modalities.size,exploreInsightTeams:teams.size};for(const [id,value] of Object.entries(vals))if($(id))$(id).textContent=value}
function renderStatus(matchCount=filteredProfiles().length){const text=$("exploreSearchStatusText"),bar=$("exploreSearchProgress");if(text)text.innerHTML=loadingMore?`Ampliando a busca na base... <strong>${matchCount} encontrado${matchCount===1?"":"s"}</strong>`:`<strong>${matchCount} encontrado${matchCount===1?"":"s"}</strong> • ${profiles.length} atletas analisados nesta sessão`;if(bar)bar.style.width=loadingMore?"72%":legacyDone&&profileDone?"100%":"38%"}
function tagsFor(p){return[p.modalidade,p.categoria,p.posicao,p.time].filter(Boolean).slice(0,2)}
function renderProfiles(){const box=$("exploreProfiles"),section=$("profilesSection");if(!box||!section)return;section.hidden=type==="images"||type==="videos";if(section.hidden)return;const list=filteredProfiles(),shown=list.slice(0,PROFILE_RENDER_LIMIT);$("profilesCount").textContent=`${list.length} encontrado${list.length===1?"":"s"} • ${profiles.length} carregados`;box.innerHTML=shown.length?shown.map((p,index)=>`<a class="profile-card" href="${esc(profileHref(p))}">${activeSearch()&&sort==="relevance"&&index<3?'<span class="profile-relevance">MELHOR CORRESP.</span>':""}<img src="${esc(profilePhoto(p))}" alt="${esc(p.nome||"Atleta")}" loading="lazy" decoding="async"><strong>${esc(p.nome||"Atleta")}</strong><small>${esc([p.cidade,p.uf,p.categoria].filter(Boolean).join(" • ")||"Perfil esportivo")}</small><div class="profile-tags">${tagsFor(p).map(t=>`<span>${esc(t)}</span>`).join("")}</div></a>`).join(""):`<div class="explore-empty">Nenhum atleta encontrado neste trecho da base.${!legacyDone||!profileDone?'<br><button type="button" class="explore-more-inline" data-search-more>BUSCAR MAIS NA BASE</button>':""}</div>`;renderStatus(list.length)}
function discoveryProfiles(){const base=filteredProfiles();if(activeSearch())return base.slice(0,8);return [...profiles].sort((a,b)=>completeness(b)-completeness(a)||a.nome.localeCompare(b.nome,"pt-BR")).slice(0,8)}
function renderDiscovery(){const section=$("discoverySection"),box=$("exploreDiscovery"),title=$("discoveryTitle"),copy=$("discoveryCopy");if(!section||!box)return;section.hidden=type==="images"||type==="videos"||!profiles.length;if(section.hidden)return;const list=discoveryProfiles();if(title)title.textContent=activeSearch()?"MELHORES CORRESPONDÊNCIAS":"DESCOBRIR ATLETAS";if(copy)copy.textContent=activeSearch()?"Perfis que mais combinam com sua busca atual.":"Perfis públicos com informações esportivas completas para você conhecer.";box.innerHTML=list.map(p=>`<a class="discovery-card" href="${esc(profileHref(p))}"><span class="discovery-score">${activeSearch()?"RELEVANTE":`${completeness(p)}% PERFIL`}</span><img src="${esc(profilePhoto(p))}" alt="${esc(p.nome||"Atleta")}" loading="lazy" decoding="async"><div><strong>${esc(p.nome||"Atleta")}</strong><small>${esc([p.cidade,p.modalidade,p.categoria,p.posicao].filter(Boolean).join(" • ")||"Perfil esportivo")}</small></div></a>`).join("")}
function renderMedia(){const box=$("exploreGrid"),section=$("mediaSection");if(!box||!section)return;section.hidden=type==="profiles";if(section.hidden)return;const list=media.filter(matchesMedia).slice(0,90);$("mediaCount").textContent=`${list.length} conteúdo${list.length===1?"":"s"}`;box.innerHTML=list.length?list.map(item=>{const p=profiles.find(x=>x.ownerUid&&x.ownerUid===item.ownerUid)||{},url=item.kind==="image"?feedImageUrl(item.url):item.url,mediaMarkup=item.kind==="video"?`<video src="${esc(url)}" muted playsinline preload="metadata"></video>`:`<img src="${esc(url)}" alt="Publicação de ${esc(p.nome||"atleta")}" loading="lazy" decoding="async">`,href=p.id?profileHref(p):`perfil-social.html?uid=${encodeURIComponent(item.ownerUid)}`,badge=item.kind==="video"?"▶":item.mediaCount>1?`▦ ${item.mediaCount}`:"▦";return `<a class="explore-item" href="${esc(href)}">${mediaMarkup}<span class="explore-type ${item.mediaCount>1?"carousel":""}">${badge}</span><div class="explore-item-overlay"><strong>${esc(p.nome||item.nome||"Atleta")}</strong><span>${esc(item.caption||"")}</span></div></a>`}).join(""):'<div class="explore-empty">Nenhuma publicação encontrada para esses filtros.</div>'}
function renderAll(){renderProfiles();renderDiscovery();renderMedia();renderChips();renderInsights();renderSuggestions()}

function suggestionCandidates(){if(!queryText)return[];const out=[],seen=new Set(),push=x=>{const key=`${x.kind}:${norm(x.value||x.label)}`;if(!seen.has(key)){seen.add(key);out.push(x)}};filteredProfiles().slice(0,5).forEach(p=>push({kind:"profile",label:p.nome,value:p.uid||p.id,profile:p}));const fieldDefs=[...uniqueValues("cidade").map(v=>({kind:"cidade",label:v,value:v,icon:"⌖"})),...uniqueValues("modalidade").map(v=>({kind:"modalidade",label:v,value:v,icon:"🏐"})),...uniqueValues("categoria").map(v=>({kind:"categoria",label:v,value:v,icon:"★"})),...uniqueValues("time").map(v=>({kind:"time",label:v,value:v,icon:"👥"}))];fieldDefs.filter(x=>norm(x.label).includes(queryText)).slice(0,5).forEach(push);return out.slice(0,8)}
function renderSuggestions(){const box=$("exploreSuggestions"),input=$("exploreQuery");if(!box||!input)return;const list=document.activeElement===input?suggestionCandidates():[];suggestionIndex=-1;box.classList.toggle("open",list.length>0);box.innerHTML=list.map((x,i)=>x.kind==="profile"?`<button class="explore-suggestion" type="button" data-suggestion-index="${i}" data-profile-href="${esc(profileHref(x.profile))}"><img src="${esc(profilePhoto(x.profile))}" alt=""><span><strong>${esc(x.label)}</strong><small>${esc([x.profile.cidade,x.profile.categoria,x.profile.posicao].filter(Boolean).join(" • ")||"Abrir perfil")}</small></span></button>`:`<button class="explore-suggestion" type="button" data-suggestion-index="${i}" data-suggestion-field="${esc(x.kind)}" data-suggestion-value="${esc(x.value)}"><span class="explore-suggestion-icon">${x.icon}</span><span><strong>${esc(x.label)}</strong><small>Filtrar por ${esc(x.kind==="time"?"equipe":x.kind)}</small></span></button>`).join("")}
function activateSuggestion(next){const nodes=[...document.querySelectorAll(".explore-suggestion")];if(!nodes.length)return;suggestionIndex=(next+nodes.length)%nodes.length;nodes.forEach((n,i)=>n.classList.toggle("active",i===suggestionIndex));nodes[suggestionIndex]?.scrollIntoView({block:"nearest"})}
function chooseSuggestion(button){if(!button)return;if(button.dataset.profileHref){location.href=button.dataset.profileHref;return}const field=button.dataset.suggestionField,value=button.dataset.suggestionValue;if(field&&field in filters){filters[field]=value;queryRaw="";queryText="";$("exploreQuery").value="";refreshFilterOptions();renderAll();syncUrl();scheduleSearchCoverage()}}

async function readPage(name,last=null,pageSize=PAGE_SIZE){const constraints=[orderBy(documentId())];if(last)constraints.push(startAfter(last));constraints.push(limit(pageSize));const snap=await getDocs(query(collection(db,name),...constraints));return{docs:snap.docs,last:snap.docs.at(-1)||last,done:snap.size<pageSize}}
function addLegacy(docs){for(const d of docs)legacyMap.set(d.id,normalizeAthlete(d.id,d.data(),"atletas"))}
function addSocial(docs){for(const d of docs)profileMap.set(d.id,normalizeAthlete(d.id,d.data(),"perfil-social"))}
function syncLoadMore(){const section=$("profilesSection");if(!section)return;let button=$("exploreLoadMoreAthletes"),show=!legacyDone||!profileDone;if(!show){button?.remove();return}if(!button){button=document.createElement("button");button.id="exploreLoadMoreAthletes";button.type="button";button.className="explore-load-more";button.addEventListener("click",()=>loadMoreAthletes(false));section.appendChild(button)}button.disabled=loadingMore;button.textContent=loadingMore?"AMPLIANDO A BASE...":activeSearch()?"BUSCAR MAIS ATLETAS":"CARREGAR MAIS ATLETAS"}
async function loadMoreAthletes(auto=false){if(loadingMore||legacyDone&&profileDone)return false;loadingMore=true;syncLoadMore();renderStatus();try{const jobs=[];if(!legacyDone)jobs.push(readPage("atletas",legacyCursor).then(page=>{addLegacy(page.docs);legacyCursor=page.last;legacyDone=page.done}));if(!profileDone)jobs.push(readPage("perfis",profileCursor).then(page=>{addSocial(page.docs);profileCursor=page.last;profileDone=page.done}));await Promise.allSettled(jobs);rebuildProfiles();return true}finally{loadingMore=false;syncLoadMore();renderStatus();if(!auto)renderSuggestions()}}
function scheduleSearchCoverage(){clearTimeout(searchTimer);const generation=++searchGeneration;if(!activeSearch())return;searchTimer=setTimeout(()=>ensureSearchCoverage(generation),280)}
async function ensureSearchCoverage(generation){if(generation!==searchGeneration)return;for(let i=0;i<AUTO_SEARCH_PAGES;i++){if(generation!==searchGeneration||filteredProfiles().length>=SEARCH_TARGET||legacyDone&&profileDone)break;const loaded=await loadMoreAthletes(true);if(!loaded)break}}
async function readPublicMedia(name,max){try{return await getDocs(query(collection(db,name),where("aprovado","==",true),where("visibilidade","==","publico"),orderBy("criadoEm","desc"),limit(max)))}catch{return getDocs(query(collection(db,name),where("aprovado","==",true),where("visibilidade","==","publico"),limit(max)))}}

async function load(){try{const [legacyResult,profileResult,postsResult,videosResult]=await Promise.allSettled([readPage("atletas"),readPage("perfis"),readPublicMedia("publicacoes",160),readPublicMedia("videos",100)]);if(legacyResult.status==="fulfilled"){addLegacy(legacyResult.value.docs);legacyCursor=legacyResult.value.last;legacyDone=legacyResult.value.done}else legacyDone=true;if(profileResult.status==="fulfilled"){addSocial(profileResult.value.docs);profileCursor=profileResult.value.last;profileDone=profileResult.value.done}else profileDone=true;const postsSnap=postsResult.status==="fulfilled"?postsResult.value:null,videosSnap=videosResult.status==="fulfilled"?videosResult.value:null,posts=postsSnap?postsSnap.docs.map(d=>{const x=d.data(),mids=Array.isArray(x.midias)?x.midias.filter(m=>m&&m.tipo!=="video"&&(m.url||m.mediaUrl)):[],url=mids[0]?.url||mids[0]?.mediaUrl||x.imagemUrl||x.imagem||"";return{id:d.id,kind:"image",ownerUid:x.ownerUid||"",nome:x.nome||"",url,mediaCount:Math.max(1,mids.length),caption:x.legenda||x.texto||"",createdAt:x.criadoEm}}).filter(x=>x.url&&x.ownerUid):[],videos=videosSnap?videosSnap.docs.map(d=>{const x=d.data();return{id:d.id,kind:"video",ownerUid:x.ownerUid||"",nome:x.nome||"",url:x.videoUrl||x.mediaUrl||"",mediaCount:1,caption:x.legenda||x.texto||"",createdAt:x.criadoEm}}).filter(x=>x.url&&x.ownerUid):[];media=[...posts,...videos].sort((a,b)=>ms(b.createdAt)-ms(a.createdAt));rebuildProfiles();const input=$("exploreQuery"),typeEl=$("exploreType"),sortEl=$("exploreSort");if(input)input.value=queryRaw;if(typeEl)typeEl.value=type;if(sortEl)sortEl.value=sort;renderAll();syncLoadMore();scheduleSearchCoverage()}catch(error){console.error("Explorar V26:",error);$("exploreProfiles").innerHTML='<div class="explore-empty">Não foi possível carregar os atletas.</div>';$("exploreGrid").innerHTML='<div class="explore-empty">Não foi possível carregar as publicações agora.</div>'}}

$("exploreQuery")?.addEventListener("input",event=>{queryRaw=event.target.value;queryText=norm(queryRaw);syncUrl();renderAll();scheduleSearchCoverage()});
$("exploreQuery")?.addEventListener("focus",renderSuggestions);
$("exploreQuery")?.addEventListener("keydown",event=>{if(event.key==="ArrowDown"){event.preventDefault();activateSuggestion(suggestionIndex+1)}else if(event.key==="ArrowUp"){event.preventDefault();activateSuggestion(suggestionIndex-1)}else if(event.key==="Enter"&&suggestionIndex>=0){event.preventDefault();chooseSuggestion(document.querySelectorAll(".explore-suggestion")[suggestionIndex])}else if(event.key==="Escape")$("exploreSuggestions")?.classList.remove("open")});
$("exploreClear")?.addEventListener("click",()=>{queryRaw="";queryText="";$("exploreQuery").value="";syncUrl();renderAll();$("exploreQuery").focus()});
$("exploreType")?.addEventListener("change",event=>{type=event.target.value;syncUrl();renderAll()});
$("exploreSort")?.addEventListener("change",event=>{sort=event.target.value;syncUrl();renderAll()});
for(const [key,id] of Object.entries(FILTER_IDS))$(id)?.addEventListener("change",event=>{filters[key]=event.target.value;syncUrl();renderAll();scheduleSearchCoverage()});
$("exploreChips")?.addEventListener("click",event=>{const button=event.target.closest("[data-clear-filter]");if(!button)return;const key=button.dataset.clearFilter;if(key==="q"){queryRaw="";queryText="";$("exploreQuery").value=""}else if(key==="type"){type="all";$("exploreType").value="all"}else if(key in filters){filters[key]="";$(FILTER_IDS[key]).value=""}syncUrl();renderAll()});
$("exploreReset")?.addEventListener("click",()=>{queryRaw="";queryText="";type="all";sort="relevance";Object.keys(filters).forEach(k=>filters[k]="");$("exploreQuery").value="";$("exploreType").value="all";$("exploreSort").value="relevance";refreshFilterOptions();syncUrl();renderAll()});
$("exploreSuggestions")?.addEventListener("mousedown",event=>{const button=event.target.closest(".explore-suggestion");if(button){event.preventDefault();chooseSuggestion(button)}});
$("profilesSection")?.addEventListener("click",event=>{if(event.target.closest("[data-search-more]")){event.preventDefault();loadMoreAthletes(false)}});
document.addEventListener("click",event=>{if(!event.target.closest(".explore-searchbox"))$("exploreSuggestions")?.classList.remove("open")});

load();
