import "./site-v5.js?v=20260901-9";
import {getApp,getApps,initializeApp} from "https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import {getAuth,onAuthStateChanged} from "https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import {addDoc,collection,deleteDoc,doc,getCountFromServer,getDoc,getDocs,getFirestore,limit,orderBy,query,setDoc,Timestamp,where} from "https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
import {createNotification,renderStoriesBar,initSocialNetwork} from "./social-network.js?v=20260901-3";
import {feedImageUrl,thumbImageUrl} from "./media-utils.js?v=20260901-1";

const cfg={apiKey:"AIzaSyBMsuR0320Nz3asVRj5axXFvKJ5Ftz9COQ",authDomain:"jogadores-de-volei.firebaseapp.com",projectId:"jogadores-de-volei",storageBucket:"jogadores-de-volei.firebasestorage.app",messagingSenderId:"48728914064",appId:"1:48728914064:web:1dd7aeb705319886f74015"};
const app=getApps().length?getApp():initializeApp(cfg),auth=getAuth(app),db=getFirestore(app);
const $=id=>document.getElementById(id),esc=v=>{const d=document.createElement("div");d.textContent=v??"";return d.innerHTML};
const ms=v=>v?.toMillis?.()??(v?.seconds?Number(v.seconds)*1000:new Date(v||0).getTime()||0),date=v=>ms(v)?new Date(ms(v)).toLocaleString("pt-BR",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}):"";
const fallback="data:image/svg+xml;charset=UTF-8,"+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="160" height="160"><rect width="160" height="160" fill="#dfe9ef"/><text x="80" y="100" text-anchor="middle" font-size="58">🏐</text></svg>');
let user=null,profileComplete=false,posts=[],videos=[],following=new Set(),liked=new Set(),saved=new Set(),loaded=false;
const profiles=new Map(),likeCounts=new Map(),commentCounts=new Map();

function installFeedStyles(){if(document.getElementById("instagramFeedStylesV8"))return;const s=document.createElement("style");s.id="instagramFeedStylesV8";s.textContent=`
.home-social{max-width:none!important}.home-social-grid{display:block!important}.home-feed-column{width:100%!important}.social-stories-wrap{border:1px solid #d6e2e9;border-radius:16px;padding:12px;background:#f3f8fa;margin-bottom:16px}.social-stories{display:flex!important;gap:14px!important;overflow-x:auto!important;scrollbar-width:none!important}.social-stories::-webkit-scrollbar{display:none}.story-item{flex:0 0 72px;text-align:center;color:#20384a;font:800 9px Arial;cursor:pointer}.story-item span{display:block;margin-top:6px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.home-feed{display:grid;gap:18px}.social-post{overflow:hidden;border:1px solid #dce5eb;border-radius:18px;background:#fff}.social-post-head{display:flex;align-items:center;gap:10px;padding:12px 14px}.feed-avatar{width:40px;height:40px;border-radius:50%;object-fit:cover;border:2px solid #b9deea}.social-author{color:#142b3b!important;text-decoration:none!important;font:900 12px Arial}.feed-author-copy{flex:1;min-width:0}.feed-author-copy small{display:block;color:#6c7f8f!important;font-size:9px;margin-top:3px}.social-date{color:#748796!important;font-size:9px}.social-media-frame{position:relative;width:100%;background:#e9eff3;display:flex;align-items:center;justify-content:center;max-height:780px;overflow:hidden}.social-media-frame img,.social-media-frame video{display:block;width:100%;height:auto;max-height:780px;object-fit:contain;background:#e9eff3}.social-feed-video{min-height:260px}.feed-kind{position:absolute;right:10px;top:10px;padding:5px 8px;border-radius:30px;background:rgba(7,24,39,.72);color:#fff;font-size:10px}.social-post-body{padding:10px 14px 13px;background:#fff}.social-actions{display:flex;align-items:center;gap:8px}.social-actions button{border:0!important;background:transparent!important;color:#3b566a!important;font-size:20px!important;cursor:pointer!important;padding:5px!important;min-height:auto!important;box-shadow:none!important}.social-actions button b{font-size:11px}.social-actions .home-save{margin-left:auto}.social-actions .active{color:#008fbe!important}.social-likes{margin:4px 0 6px;font-size:11px}.social-text{font-size:12px;line-height:1.5;margin:3px 0 7px;color:#253d50!important;white-space:pre-wrap}.view-comments{border:0!important;background:transparent!important;color:#65798a!important;padding:0!important;cursor:pointer;font-size:10px!important;min-height:auto!important}.feed-heart-pop{position:absolute;inset:0;display:grid;place-items:center;pointer-events:none;font-size:80px;opacity:0;transform:scale(.5);transition:.25s}.feed-heart-pop.show{opacity:.9;transform:scale(1)}
.social-comments-modal{position:fixed;inset:0;z-index:23000;background:rgba(7,24,39,.48);display:none;place-items:center;padding:15px;backdrop-filter:blur(8px)}.social-comments-modal.open{display:grid}.social-comments-box{width:min(540px,100%);max-height:82vh;display:flex;flex-direction:column;background:#fff;border:1px solid #d7e2e9;border-radius:17px;overflow:hidden;box-shadow:0 28px 90px rgba(7,24,39,.24)}.comments-head{display:flex;align-items:center;justify-content:space-between;padding:13px 15px;border-bottom:1px solid #e2e9ee}.comments-head h3{margin:0;color:#172b3b}.social-comments-close{border:0!important;background:transparent!important;color:#465f72!important;font-size:24px!important}.social-comments-list{overflow:auto;flex:1;padding:10px}.social-comment{display:flex;gap:8px;padding:9px}.social-comment img{width:31px;height:31px;border-radius:50%;object-fit:cover}.social-comment strong{display:block;font-size:10px;color:#172b3b}.social-comment span{font-size:11px;color:#3d5365}.social-comment-form{display:flex;gap:7px;padding:10px;border-top:1px solid #e2e9ee}.social-comment-form input{flex:1}.social-comment-form button{border:0!important;border-radius:20px!important;background:#008fbe!important;color:#fff!important;padding:0 15px!important;font-weight:900!important}.social-login-gate{padding:28px;text-align:center;border:1px solid #dce5eb;border-radius:15px;background:#f5f8fa;color:#5e7485}.social-login-gate strong,.social-login-gate span{display:block}.social-login-gate span{margin-top:5px}.social-login-gate a{display:inline-block;margin-top:11px;color:#008fbe}
`;document.head.appendChild(s)}

async function profileOf(uid){if(!uid)return{uid:"",nome:"Atleta",fotoUrl:fallback};if(profiles.has(uid))return profiles.get(uid);try{const s=await getDoc(doc(db,"perfis",uid));const p=s.exists()?{uid,...s.data()}:{uid,nome:"Atleta"};p.fotoUrl=p.fotoUrl||fallback;profiles.set(uid,p);return p}catch{return{uid,nome:"Atleta",fotoUrl:fallback}}}
function gate(){if(user)return true;location.href=`conta.html?tab=login&return=${encodeURIComponent(location.pathname+location.search+location.hash)}`;return false}
function action(){if(!gate())return false;if(!profileComplete){location.href="meu-perfil.html?novo=1";return false}return true}
function mediaOf(p){return p._kind==="video"?(p.videoUrl||p.mediaUrl||""):(p.imagemUrl||p.imagem||"")}
function postMedia(p){const raw=mediaOf(p);if(!raw)return"";if(p._kind==="video")return `<div class="social-media-frame" data-double-like><video class="social-feed-video" src="${esc(raw)}" controls playsinline preload="metadata"></video><span class="feed-kind">▶ vídeo</span><span class="feed-heart-pop">❤</span></div>`;const url=feedImageUrl(raw);return `<div class="social-media-frame" data-double-like><img src="${esc(url)}" alt="Publicação de ${esc(p.nome||"atleta")}" loading="lazy" decoding="async"><span class="feed-heart-pop">❤</span></div>`}
function allItems(){return [...posts.map(x=>({...x,_kind:"image"})),...videos.map(x=>({...x,_kind:"video"}))].sort((a,b)=>{const fa=following.has(a.ownerUid)?1:0,fb=following.has(b.ownerUid)?1:0;return fb-fa||ms(b.criadoEm)-ms(a.criadoEm)})}

async function prefetchProfiles(items){const ids=[...new Set(items.map(x=>x.ownerUid).filter(Boolean))];await Promise.all(ids.map(profileOf))}
function renderFeed(){const box=$("homeFeed");if(!box)return;const items=allItems();if(!items.length){box.innerHTML='<div class="social-login-gate"><strong>O feed está começando</strong><span>Publique o primeiro momento da rede esportiva.</span></div>';return}box.innerHTML=items.map(p=>{const a=profiles.get(p.ownerUid)||{nome:p.nome||"Atleta",fotoUrl:fallback},lc=likeCounts.get(p.id)||0,cc=commentCounts.get(p.id)||0;return `<article class="social-post" id="post-${esc(p.id)}" data-post-id="${esc(p.id)}" data-owner="${esc(p.ownerUid||"")}"><div class="social-post-head"><a href="perfil-social.html?uid=${encodeURIComponent(p.ownerUid||"")}"><img class="feed-avatar" src="${esc(thumbImageUrl(a.fotoUrl||fallback))}" alt=""></a><div class="feed-author-copy"><a class="social-author" href="perfil-social.html?uid=${encodeURIComponent(p.ownerUid||"")}">${esc(a.nome||p.nome||"Atleta")}</a><small>${following.has(p.ownerUid)?"Seguindo":"Rede esportiva"}</small></div><span class="social-date">${esc(date(p.criadoEm))}</span></div>${postMedia(p)}<div class="social-post-body"><div class="social-actions"><button class="home-like ${liked.has(p.id)?"active":""}" type="button" aria-label="Curtir">${liked.has(p.id)?"❤":"♡"} <b data-like-count>${lc}</b></button><button class="home-comment" type="button" aria-label="Comentar">💬 <b data-comment-count>${cc}</b></button><button class="home-share" type="button" aria-label="Compartilhar">↗</button><button class="home-save ${saved.has(p.id)?"active":""}" type="button" aria-label="Salvar">${saved.has(p.id)?"🔖":"♧"}</button></div><p class="social-likes" data-like-label>${lc?`<strong>${lc} curtida${lc===1?"":"s"}</strong>`:""}</p>${(p.texto||p.legenda)?`<p class="social-text">${esc(p.texto||p.legenda||"")}</p>`:""}<button class="view-comments" type="button" data-comments-label>${cc?`Ver todos os ${cc} comentários`:"Adicionar comentário"}</button></div></article>`}).join("");setupVideoAutoplay()}

function updateCard(id){const card=document.querySelector(`[data-post-id="${CSS.escape(id)}"]`);if(!card)return;const lc=likeCounts.get(id)||0,cc=commentCounts.get(id)||0,likeBtn=card.querySelector(".home-like"),saveBtn=card.querySelector(".home-save");if(likeBtn){likeBtn.classList.toggle("active",liked.has(id));likeBtn.firstChild.textContent=liked.has(id)?"❤ ":"♡ ";const b=likeBtn.querySelector("[data-like-count]");if(b)b.textContent=lc}if(saveBtn){saveBtn.classList.toggle("active",saved.has(id));saveBtn.textContent=saved.has(id)?"🔖":"♧"}const likeLabel=card.querySelector("[data-like-label]");if(likeLabel)likeLabel.innerHTML=lc?`<strong>${lc} curtida${lc===1?"":"s"}</strong>`:"";const cb=card.querySelector("[data-comment-count]");if(cb)cb.textContent=cc;const label=card.querySelector("[data-comments-label]");if(label)label.textContent=cc?`Ver todos os ${cc} comentários`:"Adicionar comentário"}

function setupVideoAutoplay(){const obs=new IntersectionObserver(entries=>entries.forEach(e=>{const v=e.target;if(e.isIntersecting&&e.intersectionRatio>.65){v.muted=true;v.play().catch(()=>{})}else v.pause()}),{threshold:[0,.65,1]});document.querySelectorAll(".social-feed-video").forEach(v=>obs.observe(v))}
async function loadFollowing(){following=new Set();if(!user)return;try{const s=await getDocs(query(collection(db,"seguindo",user.uid,"usuarios"),limit(300)));following=new Set(s.docs.map(d=>d.id))}catch{}}
async function hydratePersonal(items){liked=new Set();saved=new Set();if(!user)return;await Promise.all(items.map(async p=>{await Promise.all([getDoc(doc(db,"curtidas_publicacoes",p.id,"usuarios",user.uid)).then(s=>{if(s.exists())liked.add(p.id)}).catch(()=>{}),getDoc(doc(db,"salvos",user.uid,"publicacoes",p.id)).then(s=>{if(s.exists())saved.add(p.id)}).catch(()=>{})])}))}
async function hydrateCounts(items){await Promise.all(items.map(async p=>{const [l,c]=await Promise.all([getCountFromServer(collection(db,"curtidas_publicacoes",p.id,"usuarios")).then(x=>x.data().count||0).catch(()=>0),getCountFromServer(query(collection(db,"comentarios_publicacoes"),where("publicacaoId","==",p.id),where("aprovado","==",true))).then(x=>x.data().count||0).catch(()=>0)]);likeCounts.set(p.id,l);commentCounts.set(p.id,c);updateCard(p.id)}))}

async function loadContent(){
  const loadCollection=async(name,max)=>{try{return await getDocs(query(collection(db,name),where("aprovado","==",true),orderBy("criadoEm","desc"),limit(max)))}catch{return getDocs(query(collection(db,name),where("aprovado","==",true),limit(max)))}};
  const[p,v]=await Promise.all([loadCollection("publicacoes",18).catch(()=>({docs:[]})),loadCollection("videos",8).catch(()=>({docs:[]}))]);
  posts=p.docs.map(d=>({id:d.id,...d.data()})).filter(x=>x.status!=="removido");videos=v.docs.map(d=>({id:d.id,...d.data(),_kind:"video"})).filter(x=>x.status!=="removido")
}

async function load(){
  const box=$("homeFeed");if(box)box.innerHTML='<div class="social-login-gate"><strong>Carregando a rede esportiva...</strong><span>Preparando as publicações mais recentes.</span></div>';
  await Promise.all([loadContent(),loadFollowing()]);const items=allItems();await prefetchProfiles(items);renderFeed();
  if($("homeStories"))renderStoriesBar($("homeStories")).catch(()=>{});
  const idle=window.requestIdleCallback||((fn)=>setTimeout(fn,120));idle(async()=>{await Promise.all([hydratePersonal(items),hydrateCounts(items)]);items.forEach(p=>updateCard(p.id))});
  loaded=true;const h=location.hash.match(/^#post-(.+)$/);if(h)requestAnimationFrame(()=>document.getElementById(`post-${decodeURIComponent(h[1])}`)?.scrollIntoView({block:"center"}))
}

async function openComments(id){if(!action())return;let modal=$("socialCommentsModal");if(!modal){modal=document.createElement("div");modal.id="socialCommentsModal";modal.className="social-comments-modal";modal.innerHTML='<div class="social-comments-box"><div class="comments-head"><h3>Comentários</h3><button class="social-comments-close">×</button></div><div class="social-comments-list"></div><form class="social-comment-form"><input maxlength="500" placeholder="Adicione um comentário..." required><button>Publicar</button></form></div>';document.body.appendChild(modal);modal.querySelector(".social-comments-close").onclick=()=>modal.classList.remove("open");modal.onclick=e=>{if(e.target===modal)modal.classList.remove("open")}}modal.classList.add("open");const list=modal.querySelector(".social-comments-list");list.innerHTML='<div class="social-login-gate">Carregando comentários...</div>';try{let snap;try{snap=await getDocs(query(collection(db,"comentarios_publicacoes"),where("publicacaoId","==",id),where("aprovado","==",true),orderBy("criadoEm","asc"),limit(120)))}catch{snap=await getDocs(query(collection(db,"comentarios_publicacoes"),where("publicacaoId","==",id),where("aprovado","==",true),limit(120)))}const data=await Promise.all(snap.docs.map(async d=>{const x=d.data(),p=await profileOf(x.ownerUid);return `<div class="social-comment"><img src="${esc(thumbImageUrl(p.fotoUrl||fallback))}" alt=""><div><strong>${esc(p.nome||x.nome||"Atleta")}</strong><span>${esc(x.texto||"")}</span></div></div>`}));list.innerHTML=data.join("")||'<div class="social-login-gate">Ainda não há comentários.</div>'}catch{list.innerHTML='<div class="social-login-gate">Comentários indisponíveis.</div>'}const form=modal.querySelector("form");form.onsubmit=async e=>{e.preventDefault();const input=form.querySelector("input"),texto=input.value.trim();if(!texto)return;const p=posts.find(x=>x.id===id)||videos.find(x=>x.id===id),me=await profileOf(user.uid),btn=form.querySelector("button");btn.disabled=true;try{await addDoc(collection(db,"comentarios_publicacoes"),{ownerUid:user.uid,ownerEmail:user.email||"",publicacaoId:id,nome:me.nome||user.displayName||"Atleta",texto,parentCommentId:"",aprovado:true,status:"publicado",criadoEm:Timestamp.now()});input.value="";list.insertAdjacentHTML("beforeend",`<div class="social-comment"><img src="${esc(thumbImageUrl(me.fotoUrl||fallback))}"><div><strong>${esc(me.nome||"Atleta")}</strong><span>${esc(texto)}</span></div></div>`);commentCounts.set(id,(commentCounts.get(id)||0)+1);updateCard(id);if(p?.ownerUid)await createNotification(p.ownerUid,"comment",{sourceId:id,text:texto.slice(0,120)})}catch(err){console.error(err);alert("Não foi possível publicar o comentário.")}finally{btn.disabled=false}}}

async function likePost(id,card,forceLike=false){if(!action())return;const ref=doc(db,"curtidas_publicacoes",id,"usuarios",user.uid),post=posts.find(x=>x.id===id)||videos.find(x=>x.id===id);try{if(liked.has(id)&&!forceLike){await deleteDoc(ref);liked.delete(id);likeCounts.set(id,Math.max(0,(likeCounts.get(id)||1)-1))}else if(!liked.has(id)){await setDoc(ref,{uid:user.uid,criadoEm:Timestamp.now()});liked.add(id);likeCounts.set(id,(likeCounts.get(id)||0)+1);if(post?.ownerUid)createNotification(post.ownerUid,"like",{sourceId:id}).catch(()=>{})}if(forceLike){const pop=card?.querySelector(".feed-heart-pop");if(pop){pop.classList.add("show");setTimeout(()=>pop.classList.remove("show"),500)}}updateCard(id)}catch(e){console.error(e);alert("Não foi possível registrar a curtida.")}}
async function toggleSave(id){if(!action())return;const ref=doc(db,"salvos",user.uid,"publicacoes",id);try{if(saved.has(id)){await deleteDoc(ref);saved.delete(id)}else{const p=posts.find(x=>x.id===id)||videos.find(x=>x.id===id);await setDoc(ref,{postId:id,kind:p?._kind||"post",createdAt:Timestamp.now()});saved.add(id)}updateCard(id)}catch(e){console.error(e);alert("Não foi possível salvar a publicação.")}}
async function sharePost(id){const p=posts.find(x=>x.id===id)||videos.find(x=>x.id===id),url=`${location.origin}${location.pathname}#post-${encodeURIComponent(id)}`;try{if(navigator.share)await navigator.share({title:"Banco de Atletas",text:p?.texto||p?.legenda||"Publicação",url});else if(navigator.clipboard){await navigator.clipboard.writeText(url);alert("Link copiado.")}}catch{}}
function bindFeed(){const box=$("homeFeed");if(!box)return;box.addEventListener("click",async e=>{const card=e.target.closest("[data-post-id]");if(!card)return;const id=card.dataset.postId,b=e.target.closest("button");if(b?.classList.contains("home-share"))return sharePost(id);if(b?.classList.contains("home-save"))return toggleSave(id);if(b?.classList.contains("home-like"))return likePost(id,card);if(b?.classList.contains("home-comment")||b?.classList.contains("view-comments"))return openComments(id)});box.addEventListener("dblclick",e=>{const card=e.target.closest("[data-post-id]"),media=e.target.closest("[data-double-like]");if(card&&media)likePost(card.dataset.postId,card,true)})}

installFeedStyles();initSocialNetwork();bindFeed();
onAuthStateChanged(auth,async u=>{user=u;profileComplete=false;if(u){try{const p=await getDoc(doc(db,"perfis",u.uid));profileComplete=p.exists()&&!!p.data()?.nome}catch{}}if(!loaded)await load();else{await loadFollowing();renderFeed();const items=allItems();const idle=window.requestIdleCallback||((fn)=>setTimeout(fn,100));idle(async()=>{await hydratePersonal(items);items.forEach(p=>updateCard(p.id));if($("homeStories"))renderStoriesBar($("homeStories")).catch(()=>{})})}});
