import{getApp,getApps,initializeApp}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";import{getAuth,onAuthStateChanged}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";import{getFirestore,collection,getDocs,getDoc,query,where,orderBy,limit,doc,setDoc,deleteDoc,Timestamp}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
const cfg={apiKey:"AIzaSyBMsuR0320Nz3asVRj5axXFvKJ5Ftz9COQ",authDomain:"jogadores-de-volei.firebaseapp.com",projectId:"jogadores-de-volei",storageBucket:"jogadores-de-volei.firebasestorage.app",messagingSenderId:"48728914064",appId:"1:48728914064:web:1dd7aeb705319886f74015"};
const app=getApps().length?getApp():initializeApp(cfg),auth=getAuth(app),db=getFirestore(app);let user=null,profileComplete=false,posts=[],videoPosts=[],liked=new Set();
const $=id=>document.getElementById(id),esc=v=>{const d=document.createElement("div");d.textContent=v??"";return d.innerHTML},txt=v=>v==null?"":String(v),date=v=>{if(!v)return"";if(typeof v.toMillis==="function")return new Date(v.toMillis()).toLocaleDateString("pt-BR");if(v.seconds)return new Date(Number(v.seconds)*1000).toLocaleDateString("pt-BR");return new Date(v).toLocaleDateString("pt-BR")},img=v=>/^https?:\/\//i.test(txt(v))||/^data:image\//i.test(txt(v))?txt(v):"";
function gate(){const m=document.createElement("div");m.className="home-social-auth-modal open";m.innerHTML='<div class="home-social-auth-box"><h3>FAÇA PARTE DA REDE</h3><p>Para curtir, comentar, publicar, seguir atletas e participar da comunidade, você precisa criar sua conta ou entrar.</p><a href="conta.html?tab=register">CRIAR CONTA</a><a href="conta.html">ENTRAR</a><br><button>Continuar navegando</button></div>';m.querySelector("button").onclick=()=>m.remove();document.body.appendChild(m)}
function action(){if(!user){gate();return false}if(!profileComplete){location.href="meu-perfil.html?novo=1";return false}return true}
function renderStories(arr){const box=$("homeStories");if(!box)return;if(!arr.length){box.innerHTML='<div class="social-login-gate"><strong>Ainda não há stories</strong><span>Os próximos momentos da comunidade aparecerão aqui.</span></div>';return}box.innerHTML=arr.map(s=>{const source=img(s.imagemUrl||s.imagem||s.mediaUrl);return source?'<article class="story-item"><div class="story-ring"><img src="'+esc(source)+'" alt="" loading="lazy"></div><span>'+esc(s.nome||s.autorNome||"Atleta")+'</span></article>':""}).join("")}
function renderVideos(){ }
function renderFeed(){const box=$("homeFeed");if(!box)return;const all=[...posts.map(p=>({...p,_kind:"image"})),...videoPosts.map(v=>({...v,_kind:"video"}))].sort((a,b)=>(b.criadoEm?.seconds||0)-(a.criadoEm?.seconds||0));if(!all.length){box.innerHTML='<div class="social-login-gate"><strong>O feed está começando</strong><span>Seja uma das primeiras pessoas a publicar na nova rede.</span><a href="conta.html?tab=register">CRIAR CONTA</a></div>';return}box.innerHTML=all.map(p=>{const source=img(p.imagemUrl||p.imagem);const video=txt(p.videoUrl||p.mediaUrl);const likedNow=liked.has(p.id);return '<article class="social-post" data-post-id="'+esc(p.id)+'">'+(p._kind==="video"&&video?'<video class="social-feed-video" src="'+esc(video)+'" controls playsinline preload="metadata"></video>':source?'<img src="'+esc(source)+'" alt="Publicação de '+esc(p.nome||"atleta")+'" loading="lazy">':"")+'<div class="social-post-body"><a class="social-author" href="perfil-social.html?uid='+encodeURIComponent(p.ownerUid||"")+'">'+esc(p.nome||p.autorNome||"Atleta")+' · '+esc(date(p.criadoEm))+'</a><p class="social-text">'+esc(p.texto||p.legenda||"")+'</p><div class="social-actions"><button class="home-like" type="button">'+(likedNow?"❤️":"♡")+' CURTIR</button><button class="home-comment" type="button">💬 COMENTAR</button><button class="home-share" type="button">↗ COMPARTILHAR</button></div></div></article>'}).join("")}
async function load(){try{let snap;try{snap=await getDocs(query(collection(db,"publicacoes"),where("aprovado","==",true),orderBy("criadoEm","desc"),limit(12)))}catch{snap=await getDocs(query(collection(db,"publicacoes"),where("aprovado","==",true),limit(12)))}posts=snap.docs.map(d=>({id:d.id,...d.data()})).filter(p=>p.status!=="removido").sort((a,b)=>(b.criadoEm?.seconds||0)-(a.criadoEm?.seconds||0));renderFeed()}catch(e){console.error("Feed:",e);$("homeFeed").innerHTML='<div class="social-login-gate"><strong>Não foi possível carregar o feed</strong><span>Atualize a página e tente novamente.</span></div>'}
for(const spec of [["stories","homeStories"],["videos","homeVideos"]]){try{const s=await getDocs(query(collection(db,spec[0]),orderBy("criadoEm","desc"),limit(10)));const a=s.docs.map(d=>({id:d.id,...d.data()}));if(spec[0]==="stories")renderStories(a);else{videoPosts=a;renderFeed()}}catch(e){if(spec[0]==="stories")renderStories([]);else{videoPosts=[];renderFeed()}}}}
$("homeFeed")?.addEventListener("click",async e=>{const b=e.target.closest("button"),card=e.target.closest("[data-post-id]");if(!b||!card)return;if(!action())return;const id=card.dataset.postId;if(b.classList.contains("home-like")){const ref=doc(db,"curtidas_publicacoes",id,"usuarios",user.uid);try{if(liked.has(id)){await deleteDoc(ref);liked.delete(id)}else{await setDoc(ref,{uid:user.uid,criadoEm:Timestamp.now()});liked.add(id)}renderFeed()}catch(err){console.error(err)}}if(b.classList.contains("home-comment"))location.href="comunidade.html#post-"+encodeURIComponent(id);if(b.classList.contains("home-share")){const url=location.origin+location.pathname+"#post-"+id;if(navigator.share)try{await navigator.share({title:"Banco de Atletas",text:posts.find(p=>p.id===id)?.texto||"",url})}catch{}else if(navigator.clipboard)await navigator.clipboard.writeText(url)}})
$("siteMenuTrigger")?.addEventListener("click",()=>{const d=$("siteMenuDrawer");d.classList.add("open");d.setAttribute("aria-hidden","false");$("siteMenuTrigger").setAttribute("aria-expanded","true")});
document.querySelectorAll("[data-fechar-menu]").forEach(x=>x.addEventListener("click",()=>{$("siteMenuDrawer").classList.remove("open");$("siteMenuDrawer").setAttribute("aria-hidden","true");$("siteMenuTrigger")?.setAttribute("aria-expanded","false")}));
$("menuRanking")?.addEventListener("click",()=>{document.querySelector("[data-fechar-ranking]")?.click();$("btnAbrirRanking")?.click();$("siteMenuDrawer").classList.remove("open")});
$("menuEquipes")?.addEventListener("click",()=>{ $("btnAbrirEquipes")?.click();$("siteMenuDrawer").classList.remove("open")});
onAuthStateChanged(auth,async u=>{user=u;profileComplete=false;if(u){try{const p=await getDoc(doc(db,"perfis",u.uid));profileComplete=p.exists()&&!!p.data()?.nome&&!!p.data()?.cidade&&!!p.data()?.uf}catch(e){console.warn("Perfil:",e)}}});
load();