import{getApp,getApps,initializeApp}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import{getAuth,onAuthStateChanged}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import{getFirestore,getDoc,doc,collection,getDocs,query,where,orderBy,addDoc,deleteDoc,setDoc,serverTimestamp}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
const cfg={apiKey:"AIzaSyBMsuR0320Nz3asVRj5axXFvKJ5Ftz9COQ",authDomain:"jogadores-de-volei.firebaseapp.com",projectId:"jogadores-de-volei",storageBucket:"jogadores-de-volei.firebasestorage.app",messagingSenderId:"48728914064",appId:"1:48728914064:web:1dd7aeb705319886f74015"},app=getApps().length?getApp():initializeApp(cfg),auth=getAuth(app),db=getFirestore(app),uid=new URLSearchParams(location.search).get("uid");
const $=id=>document.getElementById(id),esc=v=>{const d=document.createElement("div");d.textContent=v??"";return d.innerHTML},fallback="data:image/svg+xml;charset=UTF-8,"+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="300" height="300"><rect width="300" height="300" fill="#18221d"/><text x="150" y="180" text-anchor="middle" font-size="100">🏐</text></svg>');
let profile=null,currentUser=null,media={photos:[],videos:[],stories:[]},following=false;
function img(v){return v||fallback}
async function getCount(path){try{return(await getDocs(collection(db,path))).size}catch{return 0}}
async function getFollowState(){if(!currentUser||currentUser.uid===uid)return;const s=await getDoc(doc(db,"seguidores",uid,"usuarios",currentUser.uid));following=s.exists()}
async function loadFollowers(type){const base=type==="followers"?["seguidores",uid,"usuarios"]:["seguindo",uid,"usuarios"];const snap=await getDocs(collection(db,...base));const ids=snap.docs.map(d=>d.id);const users=await Promise.all(ids.slice(0,100).map(async id=>{const p=await getDoc(doc(db,"perfis",id));return p.exists()?{uid:id,...p.data()}:null}));$("modalTitle").textContent=type==="followers"?"Seguidores":"Seguindo";$("userList").innerHTML=users.filter(Boolean).map(u=>\`<a class="pp-user" href="perfil-social.html?uid=\${encodeURIComponent(u.uid)}" style="text-decoration:none;color:inherit"><img src="\${esc(img(u.fotoUrl))}"><strong>\${esc(u.nome||"Atleta")}</strong></a>\`).join("")||'<div class="pp-empty">Nenhuma pessoa por enquanto.</div>';$("listModal").classList.add("open")}
async function toggleFollow(){if(!currentUser){location.href="conta.html?tab=login&return="+encodeURIComponent(location.pathname+location.search);return}if(currentUser.uid===uid)return;const a=doc(db,"seguidores",uid,"usuarios",currentUser.uid),b=doc(db,"seguindo",currentUser.uid,"usuarios",uid);const button=$("followButton");button.disabled=true;try{if(following){await deleteDoc(a);await deleteDoc(b);following=false}else{await setDoc(a,{uid:currentUser.uid,criadoEm:serverTimestamp()});await setDoc(b,{uid,criadoEm:serverTimestamp()});following=true}await refreshCounts();renderActions()}catch(e){console.error(e);alert("Não foi possível atualizar o relacionamento agora.")}finally{button.disabled=false}}
async function refreshCounts(){const [followers,followingCount]=await Promise.all([getCount("seguidores/"+uid+"/usuarios"),getCount("seguindo/"+uid+"/usuarios")]);$("followers").textContent=followers;$("following").textContent=followingCount}
function renderActions(){const a=$("actions");if(!currentUser){a.innerHTML=\`<button id="followButton" class="pp-btn primary">SEGUIR</button>\`}else if(currentUser.uid===uid){a.innerHTML=\`<a class="pp-btn primary" href="meu-perfil.html">✎ EDITAR MEU PERFIL</a><a class="pp-btn" href="meu-perfil.html#publicar">＋ PUBLICAR</a>\`}else{a.innerHTML=\`<button id="followButton" class="pp-btn \${following?"following":"primary"}">\${following?"✓ SEGUINDO":"SEGUIR"}</button>\`}$("followButton")?.addEventListener("click",toggleFollow)}
function renderPosts(){const items=[...media.photos.map(x=>({t:"img",url:x.url})),...media.videos.map(x=>({t:"video",url:x.url}))];$("gallery").innerHTML=items.length?items.map(x=>x.t==="img"?\`<div class="pp-grid-item"><img src="\${esc(x.url)}" loading="lazy"></div>\`:\`<div class="pp-grid-item"><video src="\${esc(x.url)}" controls preload="metadata"></video><span class="type">▶</span></div>\`).join(""):'<div class="pp-empty" style="grid-column:1/-1">Este atleta ainda não publicou conteúdo.</div>'}
function renderStories(){const s=media.stories.filter(x=>(x.expira?.toDate?.()||new Date())>new Date());$("stories").textContent=s.length;$("storyList").innerHTML=s.length?s.map(x=>\`<img class="pp-story" src="\${esc(x.url)}" loading="lazy">\`).join(""):'<div class="pp-empty">Nenhum story ativo.</div>'}
async function load(){if(!uid){$("name").textContent="Perfil não encontrado";return}const p=await getDoc(doc(db,"perfis",uid));if(!p.exists()){$("name").textContent="Perfil ainda não preenchido";return}profile=p.data();document.title=(profile.nome||"Perfil")+" | Banco de Atletas";$("name").textContent=profile.nome||"Atleta";$("meta").textContent=[profile.cidade,profile.uf,profile.modalidade,profile.posicao,profile.categoria,profile.time].filter(Boolean).join(" • ");$("bio").textContent=profile.bio||"Atleta da rede esportiva.";$("avatar").src=img(profile.fotoUrl);if(profile.capaUrl)$("cover").style.backgroundImage=\`url("\${profile.capaUrl}")\`;
const qsafe=async(...args)=>{try{return await getDocs(query(...args,orderBy("criadoEm","desc")))}catch{return await getDocs(query(...args))}};
const[photos,videos,stories]=await Promise.all([qsafe(collection(db,"publicacoes"),where("ownerUid","==",uid),where("aprovado","==",true)),qsafe(collection(db,"videos"),where("ownerUid","==",uid)),qsafe(collection(db,"stories"),where("ownerUid","==",uid))]);
media.photos=photos.docs.map(d=>({id:d.id,url:d.data().imagemUrl||d.data().imagem}));media.videos=videos.docs.map(d=>({id:d.id,url:d.data().videoUrl}));media.stories=stories.docs.map(d=>({id:d.id,url:d.data().mediaUrl,mediaType:d.data().mediaType||"image",expira:d.data().expiraEm}));
$("photos").textContent=media.photos.length;$("videos").textContent=media.videos.length;renderPosts();renderStories();await getFollowState();await refreshCounts();renderActions()}
document.querySelectorAll(".pp-tab").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".pp-tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");const stories=b.dataset.tab==="stories";$("gallery").hidden=stories;$("storyList").hidden=!stories}));
$("followersStat").onclick=()=>loadFollowers("followers");$("followingStat").onclick=()=>loadFollowers("following");$("closeModal").onclick=()=>$("listModal").classList.remove("open");$("listModal").addEventListener("click",e=>{if(e.target.id==="listModal")$("listModal").classList.remove("open")});
onAuthStateChanged(auth,u=>{currentUser=u;load().catch(e=>{console.error(e);$("name").textContent="Não foi possível carregar este perfil"})});
