import{getApp,getApps,initializeApp}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import{
  collection,documentId,getDocs,getFirestore,limit,orderBy,query,startAfter
}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";

const cfg={apiKey:"AIzaSyBMsuR0320Nz3asVRj5axXFvKJ5Ftz9COQ",authDomain:"jogadores-de-volei.firebaseapp.com",projectId:"jogadores-de-volei",storageBucket:"jogadores-de-volei.firebasestorage.app",messagingSenderId:"48728914064",appId:"1:48728914064:web:1dd7aeb705319886f74015",measurementId:"G-K033D1K41Y"};
const app=getApps().length?getApp():initializeApp(cfg),db=getFirestore(app);
const TIMEOUT=15000;
const withTimeout=(p,ms=TIMEOUT)=>Promise.race([p,new Promise((_,reject)=>setTimeout(()=>reject(Object.assign(new Error("O banco demorou para responder."),{code:"deadline-exceeded"})),ms))]);
const $=id=>document.getElementById(id),txt=v=>v==null?"":String(v),esc=v=>{const d=document.createElement("div");d.textContent=txt(v);return d.innerHTML};
const normal=v=>txt(v).trim().toLocaleLowerCase("pt-BR").normalize("NFD").replace(/[\u0300-\u036f]/g,"");
const UFS=new Set(["AC","AL","AP","AM","BA","CE","DF","ES","GO","MA","MT","MS","MG","PA","PB","PR","PE","PI","RJ","RN","RS","RO","RR","SC","SP","SE","TO"]);
const fallbackFoto=()=>"data:image/svg+xml;charset=UTF-8,"+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="600" height="600"><rect width="600" height="600" fill="#e8d5b5"/><text x="300" y="330" text-anchor="middle" font-size="150">🏐</text></svg>');

function normalizarCategoria(v){const s=normal(v);if(s.includes("inic"))return"Iniciante";if(s.includes("avan"))return"Avançado";if(s.includes("inter"))return"Intermediário";return txt(v).trim()}
function normalizarCidade(v){const s=txt(v).trim().replace(/\s+/g," ");let m=s.match(/^([A-Z]{2})\s*[-,]\s*(.+)$/i);if(m&&UFS.has(m[1].toUpperCase()))return m[1].toUpperCase()+" - "+m[2].trim();m=s.match(/^(.+?)\s*[-,]\s*([A-Z]{2})$/i);if(m&&UFS.has(m[2].toUpperCase()))return m[2].toUpperCase()+" - "+m[1].trim();return s}
function listaCampo(valor,alternativo=""){if(Array.isArray(valor))return valor.map(txt).map(x=>x.trim()).filter(Boolean);if(txt(valor).trim())return txt(valor).split(",").map(x=>x.trim()).filter(Boolean);return alternativo?[txt(alternativo)]:[]}
function safeImage(v){const s=txt(v).trim();if(/^data:image\/(jpeg|jpg|png|webp);base64,/i.test(s))return s;try{const u=new URL(s,location.href),host=u.hostname.toLowerCase();const allowed=host===location.hostname||host==="firebasestorage.googleapis.com"||host.endsWith(".firebasestorage.googleapis.com")||host==="storage.googleapis.com";return allowed&&u.protocol==="https:"?u.href:fallbackFoto()}catch{return fallbackFoto()}}
function safeLink(v){try{const u=new URL(txt(v).trim());return u.protocol==="https:"?u.href:"#"}catch{return"#"}}

async function readAll(name,{pageSize=100,max=2000}={}){
  const out=[];let last=null;
  while(out.length<max){
    const constraints=[orderBy(documentId())];
    if(last)constraints.push(startAfter(last));
    constraints.push(limit(Math.min(pageSize,max-out.length)));
    const snap=await withTimeout(getDocs(query(collection(db,name),...constraints)));
    out.push(...snap.docs);
    if(snap.size<pageSize)break;
    last=snap.docs[snap.docs.length-1];
    if(!last)break;
  }
  return out;
}

function normalizarAtleta(id,data){const a=data&&typeof data==="object"?data:{},posicoes=listaCampo(a.posicoes,a.posicao),modalidades=listaCampo(a.modalidades,a.modalidade);return{id,ownerUid:txt(a.ownerUid||a.uid),fonte:txt(a.fonte||"atletas"),nome:txt(a.nome).trim(),historicoCampeonatos:Array.isArray(a.historicoCampeonatos)?a.historicoCampeonatos:[],time:txt(a.time).trim(),cidade:normalizarCidade(a.cidade),categoria:normalizarCategoria(a.categoria),posicao:posicoes.join(", "),posicoes,modalidade:modalidades.join(", "),modalidades,status:txt(a.status||"ativo"),foto:typeof a.foto==="string"?a.foto:(typeof a.fotoUrl==="string"?a.fotoUrl:"")}}

const apoiadoresLista=$("apoiadoresLista");
async function carregarApoiadores(){if(!apoiadoresLista)return;apoiadoresLista.innerHTML='<div class="sponsors-empty">Carregando apoiadores...</div>';try{const snap=await withTimeout(getDocs(query(collection(db,"apoiadores"),limit(50))));const arr=snap.docs.map(d=>({id:d.id,...(d.data()||{})})).filter(a=>a.ativo!==false).sort((a,b)=>(Number(a.ordem)||999)-(Number(b.ordem)||999));apoiadoresLista.innerHTML=arr.length?arr.map(a=>'<a class="sponsor-card tier-'+esc(normal(a.plano||"bronze"))+'" href="'+esc(safeLink(a.link||"#"))+'" target="_blank" rel="noopener noreferrer nofollow" title="Visitar '+esc(a.nome||"Apoiador")+'"><img src="'+esc(safeImage(a.imagem))+'" alt="Logo de '+esc(a.nome||"Apoiador")+'" loading="lazy"><span class="sponsor-name">'+esc(a.nome||"Apoiador")+'</span><small class="sponsor-tier">'+esc(a.plano||"Apoiador")+'</small></a>').join(""):'<div class="sponsors-empty">Em breve, novas marcas apoiadoras.</div>'}catch(e){console.error("Apoiadores:",e);apoiadoresLista.innerHTML='<div class="sponsors-empty">Não foi possível carregar os apoiadores.</div>'}}

let atletas=[];
const lista=$("listaJogadores"),busca=$("busca"),btnPesquisar=$("btnPesquisar"),filtroNivel=$("filtroNivel"),filtroPosicao=$("filtroPosicao"),filtroCidade=$("filtroCidade"),total=$("total"),ativos=$("ativos"),cidades=$("cidades"),resultadoTexto=$("resultadoTexto");
function renderAtletas(){if(!lista)return;const q=normal(busca?.value),nivel=normal(filtroNivel?.value),pos=normal(filtroPosicao?.value),cidade=normal(filtroCidade?.value);const filtrados=atletas.filter(a=>{const hay=[a.nome,a.time,a.cidade,a.categoria,a.posicao,a.modalidade].map(normal).join(" "),cat=normal(a.categoria);return(!q||hay.includes(q))&&(!nivel||(nivel==="intermediario"?cat.includes("intermediario"):cat===nivel))&&(!pos||a.posicoes.some(x=>normal(x)===pos))&&(!cidade||normal(a.cidade)===cidade)});if(total)total.textContent=atletas.length+" "+(atletas.length===1?"jogador":"jogadores");if(ativos)ativos.textContent=String(atletas.filter(a=>normal(a.status)!=="inativo").length);if(cidades)cidades.textContent=String(new Set(atletas.map(a=>normal(a.cidade)).filter(Boolean)).size);if(resultadoTexto)resultadoTexto.textContent=filtrados.length?filtrados.length+" "+(filtrados.length===1?"perfil encontrado":"perfis encontrados"):"Nenhum atleta corresponde aos filtros";if(!filtrados.length){lista.innerHTML='<div class="card"><div><h3>Nenhum atleta encontrado</h3><p>Tente mudar os filtros ou a busca.</p></div></div>';return}lista.innerHTML=filtrados.map(a=>{const perfil=a.fonte==="perfil-social"&&a.ownerUid?"perfil-social.html?uid="+encodeURIComponent(a.ownerUid):"perfil.html?id="+encodeURIComponent(a.id)+"#comentarios";const tags=[a.modalidade&&"🏐 "+a.modalidade,a.posicao&&"📍 "+a.posicao,a.categoria&&"🎯 "+a.categoria,a.time&&"👥 "+a.time].filter(Boolean).map(x=>'<span class="social-athlete-tag">'+esc(x)+'</span>').join("");return '<article class="card social-athlete-card"><div class="social-athlete-top"><img class="social-athlete-avatar" src="'+esc(safeImage(a.foto))+'" alt="Foto de '+esc(a.nome)+'" loading="lazy"><div><h3 class="social-athlete-name">'+esc(a.nome)+'</h3><p class="social-athlete-location">'+esc(a.cidade?"📍 "+a.cidade:"Cidade não informada")+'</p></div><span class="social-athlete-badge">'+(a.fonte==="perfil-social"?"PERFIL SOCIAL":"ATLETA")+'</span></div><img class="social-athlete-photo" src="'+esc(safeImage(a.foto))+'" alt="Foto de '+esc(a.nome)+'" loading="lazy"><div class="social-athlete-info"><div class="social-athlete-tags">'+tags+'</div><div class="social-athlete-actions"><a class="primary" href="'+perfil+'">VER PERFIL</a><a class="secondary" href="'+perfil+'">💬 COMENTAR</a></div></div></article>'}).join("")}

async function carregarAtletas(){if(!lista)return;lista.innerHTML='<p class="subtitulo">Carregando atletas...</p>';try{const[legacyDocs,profileDocs]=await Promise.all([readAll("atletas",{pageSize:100,max:2000}),readAll("perfis",{pageSize:100,max:2000})]);const legacy=legacyDocs.map(d=>normalizarAtleta(d.id,d.data())),profiles=profileDocs.map(d=>normalizarAtleta(d.id,{...d.data(),uid:d.id,fonte:"perfil-social"})).filter(a=>a.nome&&a.cidade&&normal(a.status)!=="inativo");const byUid=new Map(legacy.filter(a=>a.ownerUid).map(a=>[a.ownerUid,a])),merged=[...legacy];for(const p of profiles){const old=byUid.get(p.ownerUid);if(old)Object.assign(old,{...p,id:old.id,fonte:"perfil-social",ownerUid:p.ownerUid});else merged.push(p)}atletas=merged.filter(a=>a.nome&&normal(a.status)!=="inativo").sort((a,b)=>a.nome.localeCompare(b.nome,"pt-BR"));const cityList=[...new Map(atletas.map(a=>[normal(a.cidade),a.cidade]).filter(([k,v])=>k&&v)).values()].sort((a,b)=>a.localeCompare(b,"pt-BR"));if(filtroCidade)filtroCidade.innerHTML='<option value="">Todas as cidades</option>'+cityList.map(c=>'<option value="'+esc(c)+'">'+esc(c)+'</option>').join("");renderAtletas()}catch(e){console.error("Atletas:",e);lista.innerHTML='<div class="card"><div><h3>Não foi possível carregar os atletas</h3><p>Atualize a página e tente novamente.</p><button type="button" id="btnRetryAtletas" class="search-button">↻ TENTAR NOVAMENTE</button></div></div>';$("btnRetryAtletas")?.addEventListener("click",carregarAtletas)}}
[busca,filtroNivel,filtroPosicao,filtroCidade].filter(Boolean).forEach(el=>{el.addEventListener("input",renderAtletas);el.addEventListener("change",renderAtletas)});btnPesquisar?.addEventListener("click",renderAtletas);busca?.addEventListener("keydown",e=>{if(e.key==="Enter")renderAtletas()});

let equipes=[];
const buscaEquipe=$("buscaEquipe"),filtroModalidadeEquipe=$("filtroModalidadeEquipe"),filtroCategoriaEquipe=$("filtroCategoriaEquipe"),listaEquipes=$("listaEquipes"),equipesResultadoTexto=$("equipesResultadoTexto"),planoPeso={premium:1,master:1,ouro:2,prata:3,bronze:4,gratuito:5};
function normalizarEquipe(id,data){const e=data||{};return{id,nome:txt(e.nome).trim(),cidade:normalizarCidade(e.cidade),modalidade:txt(e.modalidade).trim(),categoria:normalizarCategoria(e.categoria),logo:typeof e.logo==="string"?e.logo:"",atletas:Array.isArray(e.atletas)?e.atletas.map(txt).map(x=>x.trim()).filter(Boolean).slice(0,30):[],plano:txt(e.plano||"Gratuito"),status:txt(e.status)}}
function renderEquipes(){if(!listaEquipes)return;const q=normal(buscaEquipe?.value),mod=normal(filtroModalidadeEquipe?.value),cat=normal(filtroCategoriaEquipe?.value),filtradas=equipes.filter(e=>{const hay=[e.nome,e.cidade,e.modalidade,e.categoria,...e.atletas].map(normal).join(" ");return(!q||hay.includes(q))&&(!mod||normal(e.modalidade)===mod)&&(!cat||normal(e.categoria)===cat)});if(equipesResultadoTexto)equipesResultadoTexto.textContent=filtradas.length+" "+(filtradas.length===1?"equipe encontrada":"equipes encontradas");if(!filtradas.length){listaEquipes.innerHTML='<div class="team-empty"><strong>Nenhuma equipe encontrada.</strong><span>Altere os filtros ou cadastre uma nova equipe.</span></div>';return}listaEquipes.innerHTML=filtradas.map(e=>'<article class="team-card tier-'+esc(normal(e.plano))+'"><div class="team-card-top"><div class="team-logo-wrap"><img src="'+esc(safeImage(e.logo))+'" alt="Logo da equipe '+esc(e.nome)+'" loading="lazy"></div><div class="team-card-title"><span class="team-plan">'+esc(e.plano)+'</span><h3>'+esc(e.nome)+'</h3><p>📍 '+esc(e.cidade||"Cidade não informada")+'</p></div></div><div class="team-meta"><span>🏐 '+esc(e.modalidade||"Modalidade não informada")+'</span><span>🎯 '+esc(e.categoria||"Categoria não informada")+'</span><span>👥 '+e.atletas.length+' atleta'+(e.atletas.length===1?"":"s")+'</span></div><div class="team-athletes"><strong>ATLETAS DA EQUIPE</strong><ul>'+(e.atletas.length?e.atletas.map(n=>'<li>'+esc(n)+'</li>').join(""):'<li class="team-no-athletes">Atletas ainda não informados.</li>')+'</ul></div></article>').join("")}
async function carregarEquipes(){if(!listaEquipes)return;listaEquipes.innerHTML='<div class="team-loading">Carregando equipes...</div>';try{equipes=(await readAll("equipes",{pageSize:100,max:1000})).map(d=>normalizarEquipe(d.id,d.data())).filter(e=>e.nome&&normal(e.status)!=="inativo").sort((a,b)=>(planoPeso[normal(a.plano)]||9)-(planoPeso[normal(b.plano)]||9)||a.nome.localeCompare(b.nome,"pt-BR"));renderEquipes()}catch(e){console.error("Equipes:",e);listaEquipes.innerHTML='<div class="team-empty"><strong>Não foi possível carregar as equipes.</strong><span>Atualize a página e tente novamente.</span></div>'}}
[buscaEquipe,filtroModalidadeEquipe,filtroCategoriaEquipe].filter(Boolean).forEach(el=>{el.addEventListener("input",renderEquipes);el.addEventListener("change",renderEquipes)});
const btnEquipes=$("btnAbrirEquipes"),btnFecharEquipes=$("btnFecharEquipes"),equipesDrawer=$("equipesDrawer");
function abrirEquipes(){if(!equipesDrawer)return;equipesDrawer.classList.add("aberto");equipesDrawer.setAttribute("aria-hidden","false");btnEquipes?.setAttribute("aria-expanded","true");document.body.classList.add("equipes-open");if(!equipes.length)void carregarEquipes()}
function fecharEquipes(){if(!equipesDrawer)return;equipesDrawer.classList.remove("aberto");equipesDrawer.setAttribute("aria-hidden","true");btnEquipes?.setAttribute("aria-expanded","false");document.body.classList.remove("equipes-open")}
btnEquipes?.addEventListener("click",abrirEquipes);btnFecharEquipes?.addEventListener("click",fecharEquipes);equipesDrawer?.addEventListener("click",e=>{if(e.target.matches("[data-fechar-equipes]"))fecharEquipes()});window.abrirEquipes=abrirEquipes;window.fecharEquipes=fecharEquipes;
document.addEventListener("keydown",e=>{if(e.key==="Escape")fecharEquipes()});

// A Home exibe o feed, não a lista de atletas. Evita centenas de leituras invisíveis.
void carregarApoiadores();
if(document.body.classList.contains("athletes-page"))void carregarAtletas();
