import{initializeApp}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";import{getFirestore,collection,getDocs,query,orderBy}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
const firebaseConfig={apiKey:"AIzaSyBMsuR0320Nz3asVRj5axXFvKJ5Ftz9COQ",authDomain:"jogadores-de-volei.firebaseapp.com",projectId:"jogadores-de-volei",storageBucket:"jogadores-de-volei.firebasestorage.app",messagingSenderId:"48728914064",appId:"1:48728914064:web:1dd7aeb705319886f74015",measurementId:"G-K033D1K41Y"};const db=getFirestore(initializeApp(firebaseConfig));
const $=id=>document.getElementById(id),busca=$("busca"),btnPesquisar=$("btnPesquisar"),filtroNivel=$("filtroNivel"),filtroPosicao=$("filtroPosicao"),filtroCidade=$("filtroCidade"),lista=$("listaJogadores"),total=$("total"),ativos=$("ativos"),cidades=$("cidades"),resultadoTexto=$("resultadoTexto"),apoiadoresLista=$("apoiadoresLista");let atletas=[];
const texto=v=>v==null?"":String(v);const normal=v=>texto(v).trim().toLocaleLowerCase("pt-BR").normalize("NFD").replace(/[\u0300-\u036f]/g,"");const esc=v=>{const d=document.createElement("div");d.textContent=texto(v);return d.innerHTML};const normalizarCategoria=v=>{const s=texto(v).trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"");if(s.includes("inic"))return"Iniciante";if(s.includes("avan"))return"Avançado";if(s.includes("inter"))return"Intermediário";return texto(v).trim()};const UFS=new Set(["AC","AL","AP","AM","BA","CE","DF","ES","GO","MA","MT","MS","MG","PA","PB","PR","PE","PI","RJ","RN","RS","RO","RR","SC","SP","SE","TO"]);const CIDADES_SP_CORRECAO={"SP - Barrinha - HA":"SP - Barrinha","SP - Cruz das Posses - ES":"SP - Cruz das Posses","SP - Jaboticabal - AL":"SP - Jaboticabal","SP - Monte Alto - TO":"SP - Monte Alto","SP - Pitangueiras - AS":"SP - Pitangueiras","SP - Pradópolis - IS":"SP - Pradópolis","SP - Serrana - NA":"SP - Serrana","SP - Sertãozinho - HO":"SP - Sertãozinho","SP - Taquaritinga - GA":"SP - Taquaritinga"};const normalizarCidade=v=>{const s=texto(v).trim().replace(/\s+/g," ");if(CIDADES_SP_CORRECAO[s])return CIDADES_SP_CORRECAO[s];const m=s.match(/^([A-Z]{2})\s*[-,]\s*(.+)$/i);if(m&&UFS.has(m[1].toUpperCase()))return m[1].toUpperCase()+" - "+m[2].trim();const n=s.match(/^(.+?)\s*[-,]\s*([A-Z]{2})$/i);if(n&&UFS.has(n[2].toUpperCase()))return n[2].toUpperCase()+" - "+n[1].trim();return s};const listaCampo=(valor,alternativo="")=>{if(Array.isArray(valor))return valor.map(texto).filter(Boolean);if(texto(valor).trim())return texto(valor).split(",").map(x=>x.trim()).filter(Boolean);return alternativo?[texto(alternativo)]:[]};const foto=f=>{const s=texto(f);const safeData=/^data:image\/(?:jpeg|jpg|png|webp|gif);/i.test(s);return safeData||s.startsWith("https://")||s.startsWith("http://")?s:"data:image/svg+xml;charset=UTF-8,"+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="600" height="600"><rect width="600" height="600" fill="#e8d5b5"/><text x="300" y="330" text-anchor="middle" font-size="150">🏐</text></svg>`)};
const safeUrl=v=>{try{const u=new URL(texto(v).trim(),location.href);return["https:","http:"].includes(u.protocol)?u.href:"#"}catch{return"#"}};
function normalizarAtleta(id,data){const a=data&&typeof data==="object"?data:{},posicoes=listaCampo(a.posicoes,a.posicao),modalidades=listaCampo(a.modalidades,a.modalidade);return{id,nome:texto(a.nome),historicoCampeonatos:Array.isArray(a.historicoCampeonatos)?a.historicoCampeonatos:[],time:texto(a.time),cidade:normalizarCidade(a.cidade),categoria:normalizarCategoria(a.categoria),posicao:posicoes.join(", "),posicoes,modalidade:modalidades.join(", "),modalidades,status:texto(a.status),foto:typeof a.foto==="string"?a.foto:""}}
async function carregarApoiadores(){if(!apoiadoresLista)return;apoiadoresLista.innerHTML='<div class="sponsors-empty">Carregando apoiadores...</div>';try{let s;try{s=await getDocs(query(collection(db,"apoiadores"),orderBy("ordem")))}catch{s=await getDocs(collection(db,"apoiadores"))}const arr=s.docs.map(d=>({id:d.id,...(d.data()||{})})).filter(a=>a.ativo!==false).sort((a,b)=>(Number(a.ordem)||999)-(Number(b.ordem)||999));apoiadoresLista.innerHTML=arr.length?arr.map(a=>`<a class="sponsor-card tier-${normal(a.plano||"bronze")} " href="${esc(safeUrl(a.link||"#"))}" target="_blank" rel="noopener noreferrer nofollow" title="Visitar ${esc(a.nome)}"><img src="${foto(a.imagem)}" alt="Logo de ${esc(a.nome)}" loading="lazy"><span class="sponsor-name">${esc(a.nome)}</span><small class="sponsor-tier">${esc(a.plano||"Apoiador")}</small></a>`).join(""):'<div class="sponsors-empty">Em breve, novas marcas apoiadoras.</div>'}catch(e){console.error("Erro nos apoiadores:",e);apoiadoresLista.innerHTML='<div class="sponsors-empty">Não foi possível carregar os apoiadores.</div>'}}
const buscaEquipe=$("buscaEquipe"),filtroModalidadeEquipe=$("filtroModalidadeEquipe"),filtroCategoriaEquipe=$("filtroCategoriaEquipe"),listaEquipes=$("listaEquipes"),equipesResultadoTexto=$("equipesResultadoTexto");let equipes=[];
const planoPeso={premium:1,master:1,ouro:2,prata:3,bronze:4,gratuito:5};
const planoNome=v=>texto(v||"Gratuito").trim();
function normalizarEquipe(id,data){const e=data&&typeof data==="object"?data:{},lista=Array.isArray(e.atletas)?e.atletas.map(texto).map(x=>x.trim()).filter(Boolean).slice(0,30):[];return{id,nome:texto(e.nome).trim(),cidade:normalizarCidade(e.cidade),modalidade:texto(e.modalidade).trim(),categoria:normalizarCategoria(e.categoria),logo:typeof e.logo==="string"?e.logo:"",atletas:lista,plano:planoNome(e.plano),status:texto(e.status)}}
async function carregarEquipes(){if(!listaEquipes)return;listaEquipes.innerHTML='<div class="team-loading">Carregando equipes...</div>';try{let s;try{s=await getDocs(query(collection(db,"equipes"),orderBy("nome")))}catch{s=await getDocs(collection(db,"equipes"))}equipes=s.docs.map(d=>normalizarEquipe(d.id,d.data())).filter(e=>e.nome&&e.status!=="inativo").sort((a,b)=>(planoPeso[normal(a.plano)]||9)-(planoPeso[normal(b.plano)]||9)||a.nome.localeCompare(b.nome,"pt-BR"));renderEquipes()}catch(e){console.error("Erro ao carregar equipes:",e);listaEquipes.innerHTML='<div class="team-empty"><strong>Não foi possível carregar as equipes.</strong><span>Atualize a página e tente novamente.</span></div>'}}
function renderEquipes(){const q=normal(buscaEquipe?.value),mod=normal(filtroModalidadeEquipe?.value),cat=normal(filtroCategoriaEquipe?.value);const filtradas=equipes.filter(e=>{const hay=[e.nome,e.cidade,e.modalidade,e.categoria,...e.atletas].map(normal).join(" ");return(!q||hay.includes(q))&&(!mod||normal(e.modalidade)===mod)&&(!cat||normal(e.categoria)===cat)});if(equipesResultadoTexto)equipesResultadoTexto.textContent=filtradas.length?filtradas.length+" "+(filtradas.length===1?"equipe encontrada":"equipes encontradas"):"Nenhuma equipe corresponde aos filtros";if(!filtradas.length){listaEquipes.innerHTML='<div class="team-empty"><strong>Nenhuma equipe encontrada.</strong><span>Cadastre uma equipe ou altere os filtros para encontrar outras.</span></div>';return}listaEquipes.innerHTML=filtradas.map(e=>{const nomes=e.atletas.length?e.atletas.map(n=>'<li>'+esc(n)+'</li>').join(""):'<li class="team-no-athletes">Atletas ainda não informados.</li>';const tier=normal(e.plano||"gratuito"),destaque=tier!=="gratuito";return '<article class="team-card tier-'+esc(tier)+'"><div class="team-card-top"><div class="team-logo-wrap"><img src="'+foto(e.logo)+'" alt="Logo da equipe '+esc(e.nome)+'" loading="lazy"></div><div class="team-card-title"><span class="team-plan">'+esc(e.plano)+'</span><h3>'+esc(e.nome)+'</h3><p>📍 '+esc(e.cidade||"Cidade não informada")+'</p></div></div><div class="team-meta"><span>🏐 '+esc(e.modalidade||"Modalidade não informada")+'</span><span>🎯 '+esc(e.categoria||"Categoria não informada")+'</span><span>👥 '+e.atletas.length+' '+(e.atletas.length===1?"atleta":"atletas")+'</span></div><div class="team-athletes"><strong>ATLETAS DA EQUIPE</strong><ul>'+nomes+'</ul></div>'+(destaque?'<div class="team-visibility">⭐ '+esc(e.plano)+' • maior destaque na vitrine</div>':"")+'</article>'}).join("")}
[buscaEquipe,filtroModalidadeEquipe,filtroCategoriaEquipe].filter(Boolean).forEach(x=>x.addEventListener("input",renderEquipes));[filtroModalidadeEquipe,filtroCategoriaEquipe].filter(Boolean).forEach(x=>x.addEventListener("change",renderEquipes));
async function carregar(){if(!lista)return;lista.innerHTML='<p class="subtitulo">Carregando atletas...</p>';try{let s;try{s=await getDocs(query(collection(db,"atletas"),orderBy("nome")))}catch{s=await getDocs(collection(db,"atletas"))}atletas=s.docs.map(d=>normalizarAtleta(d.id,d.data())).sort((a,b)=>a.nome.localeCompare(b.nome,"pt-BR"));const cs=[...new Map(atletas.map(a=>[normal(a.cidade),a.cidade.trim()]).filter(([k,v])=>k&&v)).values()].sort((a,b)=>a.localeCompare(b,"pt-BR"));if(filtroCidade)filtroCidade.innerHTML='<option value="">Todas as cidades</option>'+cs.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join("");render()}catch(e){console.error("Erro ao carregar atletas:",e);lista.innerHTML='<div class="card"><div><h3>Não foi possível carregar os atletas</h3><p>O banco respondeu, mas houve um erro ao montar a lista. Atualize a página.</p></div></div>'}}
function render(){try{const textoBusca=normal(busca?.value),nivel=normal(filtroNivel?.value),pos=normal(filtroPosicao?.value),cidade=normal(filtroCidade?.value);const filtrados=atletas.filter(a=>{const hay=[a.nome,a.time,a.cidade,a.categoria,a.posicao,a.modalidade].map(normal).join(" "),categoria=normal(a.categoria),nivelOk=!nivel||(nivel==="intermediario"?categoria.includes("intermediario"):categoria===nivel),posOk=!pos||a.posicoes.some(x=>normal(x)===pos);return(!textoBusca||hay.includes(textoBusca))&&nivelOk&&posOk&&(!cidade||normal(a.cidade)===cidade)});if(total)total.textContent=`${atletas.length} ${atletas.length===1?"jogador":"jogadores"}`;if(ativos)ativos.textContent=atletas.filter(a=>normal(a.status)!=="inativo").length;if(cidades)cidades.textContent=new Set(atletas.map(a=>normal(a.cidade)).filter(Boolean)).size;if(resultadoTexto)resultadoTexto.textContent=filtrados.length?`${filtrados.length} ${filtrados.length===1?"perfil encontrado":"perfis encontrados"}`:"Nenhum atleta corresponde aos filtros";if(!filtrados.length){lista.innerHTML='<div class="card"><div><h3>Nenhum atleta encontrado</h3><p>Tente mudar os filtros ou a busca.</p></div></div>';return}lista.innerHTML=filtrados.map(a=>{const perfil=`perfil.html?id=${encodeURIComponent(a.id)}#comentarios`,modalidade=a.modalidade?`<p><strong>Modalidade:</strong> ${esc(a.modalidade)}</p>`:"";return `<article class="card"><img src="${foto(a.foto)}" alt="Foto de ${esc(a.nome)}" loading="lazy"><div><h3>${esc(a.nome)} ${normal(a.status)==="inativo"?"🔴":"🟢"}</h3><p><strong>Cidade:</strong> ${esc(a.cidade||"Não informada")}</p>${modalidade}<p><strong>Posição:</strong> ${esc(a.posicao||"Não informada")}</p><p><strong>Categoria:</strong> ${esc(a.categoria||"Não informada")}</p><p><strong>Time atual:</strong> ${esc(a.time||"Não informado")}</p><p class="public-contact-note">🔒 Contato disponível somente para o administrador</p><div class="card-actions"><a class="profile-link" href="${perfil}">VER PERFIL COMPLETO →</a><a class="comment-link" href="${perfil}">💬 DEIXE SEU COMENTÁRIO</a></div></div></article>`}).join("")}catch(e){console.error("Erro ao renderizar atletas:",e);if(lista)lista.innerHTML='<div class="card"><div><h3>Não foi possível carregar os atletas</h3><p>Erro ao exibir o cadastro. Atualize a página.</p></div></div>'}}
function limparBannersAntigos(){document.querySelectorAll('.supporter-horizontal,.apoiador-cta,.supporter-cta,.supporter-commercial,.supporter-promo,.apoiador-horizontal').forEach(el=>el.remove())}
function aplicarEstabilizacao(){limparBannersAntigos();const styleId="estabilizacao-final-v1";if(document.getElementById(styleId))return;const style=document.createElement("style");style.id=styleId;style.textContent=`html,body{max-width:100%;overflow-x:hidden!important}@media(max-width:700px){html,body{width:100%!important;min-width:0!important;overflow-x:hidden!important}.container{width:100%!important;max-width:100%!important;min-height:0!important;visibility:visible!important;opacity:1!important}.hero-premium{display:block!important;width:100%!important;height:auto!important;min-height:0!important;visibility:visible!important;opacity:1!important}.hero-copy,.hero-art{display:block!important;visibility:visible!important;opacity:1!important}.dashboard{display:grid!important;grid-template-columns:1fr!important;width:100%!important;visibility:visible!important;opacity:1!important}.public-layout{display:grid!important;grid-template-columns:1fr!important;width:100%!important;visibility:visible!important;opacity:1!important}.athletes-content{display:block!important;width:100%!important;visibility:visible!important;opacity:1!important}.lista-jogadores{display:grid!important;grid-template-columns:1fr!important;width:100%!important}.card{display:block!important;width:100%!important;max-width:100%!important}.supporter-banner{display:none!important}.cadastro-cta{position:fixed!important;right:12px!important;bottom:12px!important;z-index:99999!important;margin:0!important;padding:0!important;background:transparent!important;border:0!important;box-shadow:none!important;display:block!important;pointer-events:none!important}.cadastro-copy{display:none!important}.whatsapp-cadastro{display:inline-flex!important;pointer-events:auto!important;width:auto!important;max-width:calc(100vw - 24px)!important;white-space:nowrap!important}.filtros{display:grid!important;grid-template-columns:1fr!important;width:100%!important}.filtros input,.filtros select,.filtros .search-button{width:100%!important;min-width:0!important}.site-footer{width:100%!important}.supporter-horizontal{display:none!important}}`;document.head.appendChild(style);limparBannersAntigos();}
[busca,filtroNivel,filtroPosicao,filtroCidade].filter(Boolean).forEach(x=>x.addEventListener("input",render));[filtroNivel,filtroPosicao,filtroCidade].filter(Boolean).forEach(x=>x.addEventListener("change",render));btnPesquisar?.addEventListener("click",render);busca?.addEventListener("keydown",e=>{if(e.key==="Enter")render()});
if(!location.hash){requestAnimationFrame(()=>window.scrollTo(0,0));setTimeout(()=>window.scrollTo(0,0),120)}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",aplicarEstabilizacao,{once:true});else aplicarEstabilizacao();
carregarApoiadores();carregar();carregarEquipes();

const btnRank=$("btnAbrirRanking"),btnFechar=$("btnFecharRanking"),drawer=$("rankingDrawer");
function abrirRanking(){if(!drawer)return;drawer.classList.add("aberto");drawer.setAttribute("aria-hidden","false");btnRank?.setAttribute("aria-expanded","true")}
function fecharRanking(){if(!drawer)return;drawer.classList.remove("aberto");drawer.setAttribute("aria-hidden","true");btnRank?.setAttribute("aria-expanded","false")}
btnRank?.addEventListener("click",abrirRanking);btnFechar?.addEventListener("click",fecharRanking);drawer?.addEventListener("click",e=>{if(e.target.matches("[data-fechar-ranking]"))fecharRanking()});

const btnEquipes=$("btnAbrirEquipes"),btnFecharEquipes=$("btnFecharEquipes"),equipesDrawer=$("equipesDrawer");
function abrirEquipes(){if(!equipesDrawer)return;equipesDrawer.classList.add("aberto");equipesDrawer.setAttribute("aria-hidden","false");btnEquipes?.setAttribute("aria-expanded","true");document.body.classList.add("equipes-open");if(!equipes.length)carregarEquipes()}
function fecharEquipes(){if(!equipesDrawer)return;equipesDrawer.classList.remove("aberto");equipesDrawer.setAttribute("aria-hidden","true");btnEquipes?.setAttribute("aria-expanded","false");document.body.classList.remove("equipes-open")}
btnEquipes?.addEventListener("click",abrirEquipes);btnFecharEquipes?.addEventListener("click",fecharEquipes);equipesDrawer?.addEventListener("click",e=>{if(e.target.matches("[data-fechar-equipes]"))fecharEquipes()});document.addEventListener("keydown",e=>{if(e.key==="Escape")fecharEquipes()});
