import{getApp,getApps,initializeApp}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import{getFirestore,collection,getDocs}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
const cfg={apiKey:"AIzaSyBMsuR0320Nz3asVRj5axXFvKJ5Ftz9COQ",authDomain:"jogadores-de-volei.firebaseapp.com",projectId:"jogadores-de-volei",storageBucket:"jogadores-de-volei.firebasestorage.app",messagingSenderId:"48728914064",appId:"1:48728914064:web:1dd7aeb705319886f74015"};
const app=getApps().length?getApp():initializeApp(cfg),db=getFirestore(app);
const $=id=>document.getElementById(id),esc=v=>{const d=document.createElement("div");d.textContent=v==null?"":String(v);return d.innerHTML};
const norm=v=>String(v??"").trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/\s+/g," ");
const dedupeHistorico=hist=>{const seen=new Set();return(Array.isArray(hist)?hist:[]).filter(h=>{const key=[h?.campeonato,h?.colocacao,h?.ano].map(norm).join("|");if(!key||seen.has(key))return false;seen.add(key);return true})};
const pontos=v=>{const s=norm(v);if(/^(1|1º|1o|1°|primeiro|campeao|campeão)(\s|$)/.test(s))return 100;if(/^(2|2º|2o|2°|segundo)(\s|$)/.test(s))return 80;if(/^(3|3º|3o|3°|terceiro)(\s|$)/.test(s))return 65;if(/^(4|4º|4o|4°|quarto)(\s|$)/.test(s))return 55;if(/^(5|6|7|8)(º|o|°)?(\s|$)/.test(s))return 40;if(/^(9|10|11|12|13|14|15|16|17|18|19|20)(º|o|°)?(\s|$)/.test(s))return 25;return s?10:0};
let atletas=[],filtro={ano:"",categoria:"",modalidade:""},carregando=null;
function chave(a){const uid=String(a.ownerUid||a.uid||"").trim();if(uid)return"uid:"+uid;const legado=String(a.legadoAtletaId||a.id||"").trim();if(legado)return"legado:"+legado;return"identidade:"+norm(a.nome)+"|"+norm(a.cidade)+"|"+String(a.nascimento||"").trim()}
function unificar(){const mapa=new Map();for(const a of atletas){const k=chave(a),old=mapa.get(k);if(!old){mapa.set(k,{...a,historicoCampeonatos:dedupeHistorico(a.historicoCampeonatos)});continue}mapa.set(k,{...old,...a,nome:old.nome||a.nome,cidade:old.cidade||a.cidade,categoria:old.categoria||a.categoria,modalidades:[...new Set([...(old.modalidades||[]),...(a.modalidades||[])].filter(Boolean))],historicoCampeonatos:dedupeHistorico([...(old.historicoCampeonatos||[]),...(a.historicoCampeonatos||[])])})}return[...mapa.values()]}
function montar(){const out=[];for(const a of unificar()){let total=0,participacoes=0;for(const h of dedupeHistorico(a.historicoCampeonatos)){if(filtro.ano&&String(h.ano||"")!==filtro.ano)continue;if(filtro.categoria&&norm(a.categoria)!==norm(filtro.categoria))continue;if(filtro.modalidade&&!(a.modalidades||[]).some(m=>norm(m)===norm(filtro.modalidade)))continue;const p=pontos(h.colocacao);if(p){total+=p;participacoes++}}if(total)out.push({...a,pontos:total,participacoes})}return out.sort((a,b)=>b.pontos-a.pontos||b.participacoes-a.participacoes||String(a.nome||"").localeCompare(String(b.nome||""),"pt-BR"))}
function render(){const box=$("rankingLista");if(!box)return;const arr=montar();if(!arr.length){box.innerHTML='<p class="ranking-vazio">Ainda não há pontuação para os filtros selecionados.</p>';return}const top=arr.slice(0,3),rest=arr.slice(3);const podio=top.map((a,i)=>'<article class="ranking-podio p'+(i+1)+'"><div class="podio-lugar">'+(i+1)+'º</div><div class="podio-nome">'+esc(a.nome||"Atleta")+'</div><small>'+a.participacoes+' campeonato'+(a.participacoes===1?"":"s")+'</small><strong>'+a.pontos+'<em> PTS</em></strong></article>').join("");const lista=rest.map((a,i)=>'<article class="ranking-item"><div class="ranking-posicao">'+(i+4)+'º</div><div class="ranking-atleta"><strong>'+esc(a.nome||"Atleta")+'</strong><small>'+esc(a.cidade||"Cidade não informada")+' · '+a.participacoes+' campeonato'+(a.participacoes===1?"":"s")+'</small></div><div class="ranking-pontos">'+a.pontos+'<small>PONTOS</small></div></article>').join("");box.innerHTML='<div class="ranking-top3">'+podio+'</div><div class="ranking-restante">'+lista+'</div>'}
function garantirDrawer(){let d=$("rankingDrawer");if(d)return d;d=document.createElement("div");d.id="rankingDrawer";d.className="ranking-drawer";d.setAttribute("aria-hidden","true");d.innerHTML='<div class="ranking-overlay" data-fechar-ranking></div><aside class="ranking-panel" role="dialog" aria-modal="true" aria-labelledby="rankingTitulo"><div class="ranking-panel-head"><div><span>DESEMPENHO NO CIRCUITO</span><h2 id="rankingTitulo">RANKING DOS ATLETAS</h2></div><button id="btnFecharRanking" class="ranking-close" type="button" aria-label="Fechar ranking">×</button></div><div id="rankingFiltros" class="ranking-filtros"></div><p class="ranking-intro">Pontuação calculada automaticamente a partir das colocações informadas nos campeonatos do perfil de cada atleta.</p><div id="rankingLista" class="ranking-lista"><p class="ranking-loading">Carregando ranking...</p></div><details class="ranking-regras"><summary>Como os pontos são calculados?</summary><ul><li><strong>1º lugar:</strong> 100 pontos</li><li><strong>2º lugar:</strong> 80 pontos</li><li><strong>3º lugar:</strong> 65 pontos</li><li><strong>4º lugar:</strong> 55 pontos</li><li><strong>5º ao 8º:</strong> 40 pontos</li><li><strong>9º ao 16º:</strong> 25 pontos</li><li><strong>Participação / outras colocações:</strong> 10 pontos</li></ul></details></aside></div>';document.body.appendChild(d);$("btnFecharRanking")?.addEventListener("click",fechar);d.addEventListener("click",e=>{if(e.target.matches("[data-fechar-ranking]"))fechar()});return d}
async function carregar(){if(carregando)return carregando;carregando=(async()=>{try{const[aSnap,pSnap]=await Promise.all([getDocs(collection(db,"atletas")),getDocs(collection(db,"perfis"))]);const perfis=pSnap.docs.map(d=>({id:d.id,...(d.data()||{})}));const byUid=new Map(perfis.map(p=>[String(p.uid||p.id),p]));const byLegado=new Map(perfis.filter(p=>p.legadoAtletaId).map(p=>[String(p.legadoAtletaId),p]));atletas=aSnap.docs.map(d=>{const a={id:d.id,...(d.data()||{})},p=byLegado.get(String(a.id))||byUid.get(String(a.ownerUid||""));return{...a,uid:a.ownerUid||p?.uid||"",nome:a.nome||p?.nome||"Atleta",cidade:a.cidade||p?.cidade||"",categoria:a.categoria||p?.categoria||"",modalidades:Array.isArray(a.modalidades)&&a.modalidades.length?a.modalidades:(Array.isArray(p?.modalidades)&&p.modalidades.length?p.modalidades:(a.modalidade?[a.modalidade]:(p?.modalidade?[p.modalidade]:[]))),historicoCampeonatos:dedupeHistorico([...(a.historicoCampeonatos||[]),...(p?.historicoCampeonatos||[])])}});const ids=new Set(atletas.map(a=>String(a.id)));for(const p of perfis){const hist=Array.isArray(p.historicoCampeonatos)?p.historicoCampeonatos:[],leg=String(p.legadoAtletaId||"");if(!hist.length||(leg&&ids.has(leg)))continue;atletas.push({id:p.uid||p.id,uid:p.uid||p.id,ownerUid:p.uid||"",nome:p.nome||"Atleta",cidade:p.cidade||"",categoria:p.categoria||"",modalidade:p.modalidade||"",modalidades:Array.isArray(p.modalidades)?p.modalidades:(p.modalidade?[p.modalidade]:[]),historicoCampeonatos:dedupeHistorico(hist)})}const anos=[...new Set(atletas.flatMap(a=>a.historicoCampeonatos.map(h=>String(h.ano||"")).filter(Boolean)))].sort().reverse(),cats=[...new Set(atletas.map(a=>a.categoria).filter(Boolean))].sort(),mods=[...new Set(atletas.flatMap(a=>a.modalidades||[]).filter(Boolean))].sort();const f=$("rankingFiltros");if(f)f.innerHTML='<select id="rankingPeriodo"><option value="geral">Ranking geral</option><option value="ano">Ranking por ano</option></select><select id="rankingAno"><option value="">Todos os anos</option>'+anos.map(esc).map(x=>'<option>'+x+'</option>').join("")+'</select><select id="rankingCategoria"><option value="">Todas as categorias</option>'+cats.map(esc).map(x=>'<option>'+x+'</option>').join("")+'</select><select id="rankingModalidade"><option value="">Todas as modalidades</option>'+mods.map(esc).map(x=>'<option>'+x+'</option>').join("")+'</select>';["rankingPeriodo","rankingAno","rankingCategoria","rankingModalidade"].forEach(id=>$(id)?.addEventListener("change",()=>{filtro.ano=$("rankingPeriodo")?.value==="ano"?$("rankingAno")?.value||"":"";filtro.categoria=$("rankingCategoria")?.value||"";filtro.modalidade=$("rankingModalidade")?.value||"";render()}));render()}catch(e){console.error("Ranking:",e);$("rankingLista")&&( $("rankingLista").innerHTML='<p class="ranking-vazio">Não foi possível carregar o ranking. Atualize a página.</p>')}})();return carregando}
async function abrir(){const d=garantirDrawer();d.classList.add("aberto");d.setAttribute("aria-hidden","false");document.body.style.overflow="hidden";const box=$("rankingLista");if(box)box.innerHTML='<p class="ranking-loading">Carregando ranking...</p>';await carregar();render()}
function fechar(){const d=$("rankingDrawer");if(!d)return;d.classList.remove("aberto");d.setAttribute("aria-hidden","true");document.body.style.overflow=""}
window.abrirRanking=abrir;window.fecharRanking=fechar;
document.addEventListener("click",e=>{const el=e.target.closest?.("a[href],button");if(!el)return;const href=el.getAttribute("href")||"",id=el.id||"";if(id==="btnAbrirRanking"){e.preventDefault();e.stopPropagation();abrir();return}if(id==="menuRanking"||/ranking[.]html(?:[?#]|$)/i.test(href)||/index[.]html[?]abrir=ranking(?:[&#]|$)/i.test(href)){e.preventDefault();e.stopPropagation();document.getElementById("siteMenuDrawer")?.classList.remove("open");document.getElementById("siteMenuDrawer")?.setAttribute("aria-hidden","true");abrir()}},true);
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>{if(new URLSearchParams(location.search).get("abrir")==="ranking"||location.hash==="#ranking")setTimeout(abrir,0)},{once:true});else if(new URLSearchParams(location.search).get("abrir")==="ranking"||location.hash==="#ranking")setTimeout(abrir,0);
