await import("./firebase-app-check-v11.js?v=20260902-2");
const THEME_VERSION="20260901-9";
const MENU_ID="siteMenuDrawer";
const MENU_TRIGGER_ID="siteMenuTrigger";
const SOCIAL_PAGES=new Set(["index.html","perfil-social.html","comunidade.html","explorar.html","reels.html","salvos.html","hashtags.html","meu-perfil.html"]);
const FIRST_BOOT=!window.__BD_ATLETAS_SHELL_BOOTED__;
if(FIRST_BOOT)window.__BD_ATLETAS_SHELL_BOOTED__=true;

function currentPage(){return location.pathname.split("/").pop()||"index.html"}
function isSocialPage(){return SOCIAL_PAGES.has(currentPage())}
function ensureTheme(){let link=document.getElementById("siteThemeV5Runtime");if(!link){link=document.createElement("link");link.id="siteThemeV5Runtime";link.rel="stylesheet";document.head.appendChild(link)}link.href=`site-theme.css?v=${THEME_VERSION}`;document.documentElement.classList.add("site-v5");document.body?.classList.add("site-v5");import("./site-v8.js?v=20260901-2").catch(error=>console.warn("Shell V8:",error))}
function tuneImage(img){if(!(img instanceof HTMLImageElement)||img.dataset.v8Quality==="1")return;img.dataset.v8Quality="1";img.decoding="async";img.style.imageRendering="auto"}
function tuneAddedMedia(node){if(node instanceof HTMLImageElement)tuneImage(node);if(node instanceof Element)node.querySelectorAll?.("img").forEach(tuneImage)}
function menuTemplate(){return `<div class="site-menu-overlay" data-fechar-menu></div><aside class="site-menu-panel" role="dialog" aria-modal="true" aria-labelledby="siteMenuTitulo"><button class="site-menu-close" type="button" data-fechar-menu aria-label="Fechar menu">×</button><div class="site-menu-brand"><span>REDE ESPORTIVA</span><h2 id="siteMenuTitulo">MENU</h2><p>Atletas, conteúdo, equipes, campeonatos e oportunidades em um só lugar.</p></div><nav class="site-menu-nav" data-v7-menu-nav><a href="index.html#feed">🏠 <span>INÍCIO / FEED</span></a><a href="explorar.html">⌕ <span>EXPLORAR</span></a><a href="atletas.html">🏐 <span>TODOS OS ATLETAS</span></a><button type="button" data-v7-ranking>🏆 <span>RANKING DOS ATLETAS</span></button><button type="button" data-v7-equipes>👥 <span>EQUIPES CADASTRADAS</span></button><a href="proximos-campeonatos.html">🏆 <span>CAMPEONATOS</span></a><a href="comunidade.html">💬 <span>COMUNIDADE</span></a><a href="reels.html">▶ <span>REELS</span></a><a href="salvos.html">▣ <span>SALVOS</span></a><button type="button" data-v7-messages hidden>✉ <span>MENSAGENS</span><b class="v5-menu-badge" hidden>0</b></button><button type="button" data-v7-notifications hidden>🔔 <span>NOTIFICAÇÕES</span><b class="v5-menu-badge" hidden>0</b></button><a href="conta.html">◉ <span>MINHA CONTA</span></a><a href="https://wa.me/5516988586327?text=Ol%C3%A1!%20Gostaria%20de%20mais%20informa%C3%A7%C3%B5es%20sobre%20o%20Banco%20de%20Dados%20de%20Atletas%20ou%20quero%20ser%20um%20apoiador." target="_blank" rel="noopener noreferrer">🤝 <span>APOIO / PARCERIAS</span></a><a href="admin.html" data-v7-admin hidden>🔐 <span>PAINEL ADM</span></a></nav><div class="site-menu-register"><strong>Rede de oportunidades do vôlei</strong><span>Crie seu perfil esportivo, publique sua trajetória e seja encontrado por equipes e organizadores.</span><a href="conta.html?tab=register">CRIAR MINHA CONTA →</a></div></aside>`}
function ensureHeaderTrigger(){const header=document.querySelector(".header");if(!header)return null;let trigger=document.getElementById(MENU_TRIGGER_ID);if(!trigger){trigger=document.createElement("button");trigger.id=MENU_TRIGGER_ID;trigger.className="site-menu-trigger";trigger.type="button";trigger.setAttribute("aria-controls",MENU_ID);trigger.setAttribute("aria-expanded","false");trigger.innerHTML="☰<span>MENU</span>";header.prepend(trigger)}trigger.onclick=event=>{event.preventDefault();event.stopPropagation();window.toggleSiteMenu?.()};return trigger}
function ensureDrawer(){let drawer=document.getElementById(MENU_ID);if(!drawer){drawer=document.createElement("div");drawer.id=MENU_ID;drawer.className="site-menu-drawer";drawer.setAttribute("aria-hidden","true");document.body.appendChild(drawer)}drawer.innerHTML=menuTemplate();return drawer}
function closeMainMenu(){const d=document.getElementById(MENU_ID),b=document.getElementById(MENU_TRIGGER_ID);d?.classList.remove("open");d?.setAttribute("aria-hidden","true");b?.setAttribute("aria-expanded","false");document.documentElement.classList.remove("site-menu-open");document.body?.classList.remove("site-menu-open")}
function openMainMenu(){const d=document.getElementById(MENU_ID),b=document.getElementById(MENU_TRIGGER_ID);if(!d)return;d.classList.add("open");d.setAttribute("aria-hidden","false");b?.setAttribute("aria-expanded","true");document.documentElement.classList.add("site-menu-open");document.body?.classList.add("site-menu-open");requestAnimationFrame(()=>d.querySelector(".site-menu-close")?.focus())}
function installMenuBehavior(){ensureHeaderTrigger();const drawer=ensureDrawer();window.closeSiteMenu=closeMainMenu;window.toggleSiteMenu=()=>drawer.classList.contains("open")?closeMainMenu():openMainMenu();drawer.addEventListener("click",event=>{if(event.target.closest?.("[data-fechar-menu]")){event.preventDefault();closeMainMenu();return}const ranking=event.target.closest?.("[data-v7-ranking]");if(ranking){event.preventDefault();closeMainMenu();if(typeof window.abrirRanking==="function")window.abrirRanking();else document.getElementById("btnAbrirRanking")?.click()||(location.href="index.html?abrir=ranking");return}const equipes=event.target.closest?.("[data-v7-equipes]");if(equipes){event.preventDefault();closeMainMenu();if(typeof window.abrirEquipes==="function")window.abrirEquipes();else if(document.getElementById("btnAbrirEquipes"))document.getElementById("btnAbrirEquipes").click();else location.href="index.html#equipes";return}const messages=event.target.closest?.("[data-v7-messages]");if(messages){event.preventDefault();closeMainMenu();setTimeout(()=>document.getElementById("snInboxButton")?.click(),20);return}const notifications=event.target.closest?.("[data-v7-notifications]");if(notifications){event.preventDefault();closeMainMenu();setTimeout(()=>document.getElementById("snNotificationsButton")?.click(),20);return}if(event.target.closest?.("a"))closeMainMenu()});document.addEventListener("keydown",event=>{if(event.key==="Escape"&&drawer.classList.contains("open"))closeMainMenu()})}
function badgeCount(sourceId){const source=document.getElementById(sourceId);if(!source||source.hidden)return 0;return Number(String(source.textContent||"0").replace(/\D/g,""))||0}
function syncMenuUtilities(){const drawer=document.getElementById(MENU_ID);if(!drawer)return;const messages=drawer.querySelector("[data-v7-messages]"),notifications=drawer.querySelector("[data-v7-notifications]"),inboxSource=document.getElementById("snInboxButton"),notificationSource=document.getElementById("snNotificationsButton");if(messages){messages.hidden=!inboxSource;const n=badgeCount("snInboxBadge"),b=messages.querySelector(".v5-menu-badge");if(b){b.hidden=n<1;b.textContent=n>99?"99+":String(n)}}if(notifications){notifications.hidden=!notificationSource;const n=badgeCount("snNotificationsBadge"),b=notifications.querySelector(".v5-menu-badge");if(b){b.hidden=n<1;b.textContent=n>99?"99+":String(n)}}}
function openStoryArchive(){const tab=document.querySelector('.pp-tab[data-tab="archive"]');if(tab){tab.click();tab.scrollIntoView({behavior:"smooth",block:"center"});return}const section=document.getElementById("storyArchiveList");section?.removeAttribute("hidden");section?.scrollIntoView({behavior:"smooth",block:"start"})}
function installProfileArchiveButton(){if(currentPage()!=="perfil-social.html")return;const actions=document.getElementById("actions");if(!actions||actions.querySelector("#profileStoriesArchiveButton"))return;const button=document.createElement("button");button.id="profileStoriesArchiveButton";button.type="button";button.className="pp-btn v5-stories-button";button.textContent="▣ STORIES POSTADOS";button.addEventListener("click",openStoryArchive);actions.appendChild(button)}
async function loadSocialModules(){if(!isSocialPage())return;try{await Promise.all([import("./social-v6.js?v=20260901-3"),import("./social-v6-followfix.js?v=20260901-3")])}catch(error){console.warn("Social V6:",error)}if(["index.html","perfil-social.html","comunidade.html","meu-perfil.html"].includes(currentPage()))import("./direct-v5.js?v=20260901-3").catch(error=>console.warn("Direct:",error))}
function runEnhancements(){ensureTheme();installMenuBehavior();document.querySelectorAll("img").forEach(tuneImage);installProfileArchiveButton();syncMenuUtilities();const idle=window.requestIdleCallback||((fn)=>setTimeout(fn,180));idle(loadSocialModules)}

if(FIRST_BOOT){
 if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",runEnhancements,{once:true});else runEnhancements();
 let utilityTimer=0;
 const observer=new MutationObserver(mutations=>{let utilities=false;for(const mutation of mutations){for(const node of mutation.addedNodes){tuneAddedMedia(node);if(node instanceof Element&&(node.id==="actions"||node.querySelector?.("#actions,#snInboxButton,#snNotificationsButton")))utilities=true}}if(!utilities)return;clearTimeout(utilityTimer);utilityTimer=setTimeout(()=>{syncMenuUtilities();installProfileArchiveButton()},120)});
 observer.observe(document.documentElement,{childList:true,subtree:true});
 window.addEventListener("sn:story-deleted",()=>setTimeout(installProfileArchiveButton,80));
}else{
 ensureTheme();
}
