const V8_THEME_ID="siteThemeV8Runtime";
function loadV8Theme(){let link=document.getElementById(V8_THEME_ID);if(!link){link=document.createElement("link");link.id=V8_THEME_ID;link.rel="stylesheet";document.head.appendChild(link)}link.href="site-v8.css?v=20260901-2";if(document.body?.classList.contains("profile-page")&&!document.getElementById("siteProfileV8Runtime")){const profile=document.createElement("link");profile.id="siteProfileV8Runtime";profile.rel="stylesheet";profile.href="site-v8-profile.css?v=20260901-1";document.head.appendChild(profile)}document.documentElement.classList.add("site-v8");document.body?.classList.add("site-v8")}
function ensureUtilityHost(){const header=document.querySelector(".header");if(!header||header.querySelector(".header-actions"))return;const host=document.createElement("div");host.className="header-actions v8-utility-host";host.hidden=true;host.setAttribute("aria-hidden","true");header.appendChild(host)}
function removeAdminEntrypoints(){document.querySelectorAll('a[href="admin.html"],a[href$="/admin.html"],[data-v7-admin]').forEach(el=>{if(el.id==="adminPanelCta"){el.hidden=true;return}el.remove()});delete document.documentElement.dataset.isAdmin}
function moveSupportersBack(){const strip=document.querySelector(".site-supporters-strip"),aside=document.querySelector(".sponsors-sidebar");if(strip&&aside){const title=strip.querySelector(".sponsors-title"),list=strip.querySelector("#apoiadoresLista"),cta=strip.querySelector(".apoio-cta");if(title)aside.appendChild(title);if(list)aside.appendChild(list);if(cta)aside.appendChild(cta);strip.remove()}}
function buildHomeRail(){const path=location.pathname.split("/").pop()||"index.html";if(path!=="index.html")return;const home=document.querySelector(".home-social"),aside=document.querySelector(".sponsors-sidebar");if(!home||!aside)return;moveSupportersBack();let grid=document.querySelector(".v8-home-grid");if(!grid){grid=document.createElement("div");grid.className="v8-home-grid";home.parentNode?.insertBefore(grid,home)}if(home.parentNode!==grid)grid.appendChild(home);if(aside.parentNode!==grid)grid.appendChild(aside)}
function registerServiceWorker(){if(!("serviceWorker"in navigator)||location.protocol!=="https:")return;navigator.serviceWorker.register("sw.js?v=20260908-38",{scope:"./"}).catch(error=>console.warn("Service Worker:",error))}
function addConnectionHints(){for(const href of["https://www.gstatic.com","https://firestore.googleapis.com","https://res.cloudinary.com"]){if(document.querySelector(`link[rel="preconnect"][href="${href}"]`))continue;const link=document.createElement("link");link.rel="preconnect";link.href=href;link.crossOrigin="anonymous";document.head.appendChild(link)}}
function addBasicSeo(){let manifest=document.querySelector('link[rel="manifest"]');if(!manifest){manifest=document.createElement("link");manifest.rel="manifest";manifest.href="manifest.webmanifest?v=20260901-1";document.head.appendChild(manifest)}let theme=document.querySelector('meta[name="theme-color"]');if(!theme){theme=document.createElement("meta");theme.name="theme-color";document.head.appendChild(theme)}theme.content="#071827";const canonical=document.querySelector('link[rel="canonical"]')||document.createElement("link");canonical.rel="canonical";canonical.href=location.origin+location.pathname+location.search;if(!canonical.parentNode)document.head.appendChild(canonical);const ensure=(property,content)=>{let meta=document.head.querySelector(`meta[property="${property}"],meta[name="${property}"]`);if(!meta){meta=document.createElement("meta");if(property.startsWith("og:"))meta.setAttribute("property",property);else meta.name=property;document.head.appendChild(meta)}if(!meta.content)meta.content=content};const description=document.querySelector('meta[name="description"]')?.content||"Rede esportiva para atletas, equipes, campeonatos e apoiadores do vôlei.";ensure("og:title",document.title);ensure("og:description",description);ensure("og:url",location.href);ensure("og:type","website");ensure("og:image",location.origin+"/assets/hero-banner.webp");ensure("twitter:card","summary_large_image");ensure("twitter:image",location.origin+"/assets/hero-banner.webp")}
function loadAdminShortcut(){import("./admin-shortcut-v34.js?v=20260908-38").catch(error=>console.warn("Atalho ADM:",error))}
function boot(){loadV8Theme();ensureUtilityHost();removeAdminEntrypoints();addConnectionHints();addBasicSeo();buildHomeRail();loadAdminShortcut();const idle=window.requestIdleCallback||((fn)=>setTimeout(fn,450));idle(registerServiceWorker)}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot,{once:true});else boot();let railTimer=0;const railObserver=new MutationObserver(mutations=>{let rebuild=false;for(const mutation of mutations){for(const n of mutation.addedNodes){if(!(n instanceof Element))continue;removeAdminEntrypoints();if(!document.querySelector(".header-actions"))ensureUtilityHost();if(n.matches?.(".sponsors-sidebar,.home-social,.site-supporters-strip")||n.querySelector?.(".sponsors-sidebar,.home-social,.site-supporters-strip"))rebuild=true}}if(!rebuild)return;clearTimeout(railTimer);railTimer=setTimeout(buildHomeRail,120)});railObserver.observe(document.documentElement,{childList:true,subtree:true});
