import { getApp,getApps,initializeApp } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import { getAuth,onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import {
  addDoc,collection,deleteDoc,doc,getDoc,getDocs,getFirestore,limit,orderBy,
  query,setDoc,Timestamp,updateDoc,where
} from "https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
import { uploadCloudinary } from "./cloudinary-upload.js?v=20260831-2";
import { createNotification,openStoryViewer } from "./social-network.js?v=20260901-2";

const cfg={apiKey:"AIzaSyBMsuR0320Nz3asVRj5axXFvKJ5Ftz9COQ",authDomain:"jogadores-de-volei.firebaseapp.com",projectId:"jogadores-de-volei",storageBucket:"jogadores-de-volei.firebasestorage.app",messagingSenderId:"48728914064",appId:"1:48728914064:web:1dd7aeb705319886f74015"};
const app=getApps().length?getApp():initializeApp(cfg),auth=getAuth(app),db=getFirestore(app);
const $=id=>document.getElementById(id),esc=v=>{const d=document.createElement("div");d.textContent=v==null?"":String(v);return d.innerHTML};
const ms=v=>v?.toMillis?.()??(v?.seconds?Number(v.seconds)*1000:new Date(v||0).getTime()||0);
const slug=v=>String(v||"").trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,28)||"atleta";
const handleOf=p=>`${slug(p?.nome||"atleta")}-${String(p?.uid||p?.id||"").slice(0,4).toLowerCase()}`;
const fallback="data:image/svg+xml;charset=UTF-8,"+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="180" height="180"><rect width="180" height="180" fill="#18221d"/><text x="90" y="110" text-anchor="middle" font-size="64">🏐</text></svg>');
let user=auth.currentUser,directoryPromise=null,activeDirectOtherUid="",scheduleTimer=0,directDecorating=false;
const profileCache=new Map(),privacyCache=new Map(),blockCache=new Map(),followCache=new Map(),carouselCache=new Map(),highlightCache=new Map();

function installStyles(){if($("socialV6Styles"))return;const s=document.createElement("style");s.id="socialV6Styles";s.textContent=`
.v6-rich a{color:#f2cc72;text-decoration:none;font-weight:850}.v6-rich a:hover{text-decoration:underline}.v6-handle{display:block;margin:-2px 0 7px;color:#838c85;font:700 9px Arial}.v6-handle button{border:0;background:transparent;color:#9fa8a1;padding:0;font:inherit;cursor:pointer}.v6-private-chip{display:inline-flex;margin-left:7px;padding:3px 7px;border-radius:20px;background:#17211a;color:#f2cc72;font:800 7px Arial;vertical-align:middle}
.v6-carousel{position:relative;width:100%;overflow:hidden;background:#000}.v6-carousel-track{display:flex;width:100%;transition:transform .24s ease}.v6-carousel-slide{flex:0 0 100%;width:100%;min-height:260px;display:grid;place-items:center;background:#000}.v6-carousel-slide img,.v6-carousel-slide video{display:block;width:auto;height:auto;max-width:100%;max-height:760px;object-fit:contain;background:#000}.v6-carousel-slide video{width:100%}.v6-carousel-nav{position:absolute;top:50%;translate:0 -50%;z-index:4;width:36px;height:36px;min-height:36px!important;padding:0!important;border:0!important;border-radius:50%!important;background:#0009!important;color:#fff!important;font-size:22px!important}.v6-carousel-prev{left:10px}.v6-carousel-next{right:10px}.v6-carousel-count{position:absolute;right:9px;top:9px;z-index:4;padding:5px 8px;border-radius:20px;background:#0009;color:#fff;font:800 9px Arial}.v6-carousel-dots{position:absolute;left:50%;bottom:9px;translate:-50% 0;z-index:4;display:flex;gap:4px}.v6-carousel-dots i{width:5px;height:5px;border-radius:50%;background:#fff7}.v6-carousel-dots i.active{background:#f2cc72}.v6-carousel-badge{position:absolute;right:6px;top:6px;z-index:3;padding:4px 6px;border-radius:20px;background:#000b;color:#fff;font:900 9px Arial}
.v6-modal{position:fixed;inset:0;z-index:31000;display:none;place-items:center;padding:17px;background:rgba(0,0,0,.84);backdrop-filter:blur(6px)}.v6-modal.open{display:grid}.v6-modal-card{width:min(670px,100%);max-height:91vh;overflow:auto;padding:22px;border:1px solid rgba(217,169,63,.28);border-radius:20px;background:#0b100d;color:#eee;box-shadow:0 30px 100px rgba(0,0,0,.58)}.v6-modal-head{display:flex;align-items:flex-start;justify-content:space-between;gap:12px}.v6-modal-head h2{margin:5px 0;color:#fff}.v6-kicker{color:#f2cc72;font:900 8px Arial;letter-spacing:2px}.v6-close{width:36px!important;height:36px!important;min-height:36px!important;padding:0!important;border:1px solid rgba(217,169,63,.25)!important;border-radius:50%!important;background:#111713!important;color:#f2cc72!important;font-size:22px!important}.v6-field{display:grid;gap:6px;margin-top:14px}.v6-field>span{color:#f2cc72;font:900 8px Arial;letter-spacing:1.2px}.v6-field input,.v6-field textarea,.v6-field select{width:100%;box-sizing:border-box;border:1px solid rgba(217,169,63,.22);border-radius:11px;background:#111713;color:#fff;padding:11px}.v6-field textarea{min-height:100px;resize:vertical}.v6-actions{display:flex;gap:8px;margin-top:16px}.v6-actions button{flex:1;min-height:44px;border:1px solid rgba(217,169,63,.28);border-radius:10px;background:#111713;color:#f2cc72;font-weight:900}.v6-actions .primary{background:linear-gradient(135deg,#f2cc72,#bd8425);color:#111}.v6-status{min-height:18px;margin-top:10px;color:#98a099;font-size:10px}.v6-status.error{color:#ff9a8b}.v6-status.ok{color:#9be3aa}.v6-preview-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:7px;margin-top:10px}.v6-preview{position:relative;aspect-ratio:1;overflow:hidden;border:1px solid rgba(217,169,63,.16);border-radius:9px;background:#030403}.v6-preview img,.v6-preview video{width:100%;height:100%;object-fit:cover}.v6-preview b{position:absolute;left:5px;top:5px;padding:3px 5px;border-radius:20px;background:#000b;color:#fff;font:800 7px Arial}
.v6-lock{margin-top:15px;padding:45px 20px;border:1px solid rgba(217,169,63,.18);border-radius:16px;background:#0b100d;text-align:center}.v6-lock .ico{font-size:38px}.v6-lock h3{margin:9px 0 5px;color:#fff}.v6-lock p{max-width:470px;margin:auto;color:#929b94;font-size:11px;line-height:1.5}
.v6-highlights{margin-top:15px;padding:13px;border:1px solid rgba(217,169,63,.16);border-radius:15px;background:#0b100d}.v6-highlights-head{margin-bottom:9px;color:#fff;font:900 10px Arial}.v6-highlights-row{display:flex;gap:12px;overflow-x:auto;scrollbar-width:none}.v6-highlight{flex:0 0 72px;text-align:center;cursor:pointer}.v6-highlight-ring{width:66px;height:66px;margin:auto;padding:3px;border-radius:50%;background:linear-gradient(135deg,#f2cc72,#82631e);box-sizing:border-box}.v6-highlight-ring img{width:100%;height:100%;object-fit:cover;border:3px solid #0b100d;border-radius:50%;box-sizing:border-box}.v6-highlight span{display:block;margin-top:5px;color:#ddd;font:800 8px Arial;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.v6-highlight-add .v6-highlight-ring{display:grid;place-items:center;border:1px dashed rgba(217,169,63,.5);background:#111713;color:#f2cc72;font-size:25px}.v6-story-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:7px;max-height:45vh;overflow:auto;margin-top:10px}.v6-story-option{position:relative;aspect-ratio:9/14;overflow:hidden;border:1px solid rgba(217,169,63,.16);border-radius:9px;background:#030403}.v6-story-option img,.v6-story-option video{width:100%;height:100%;object-fit:cover}.v6-story-option input{position:absolute;left:6px;top:6px;width:18px;height:18px;accent-color:#d9a93f}.v6-existing-highlight{display:flex;align-items:center;gap:9px;padding:9px;margin-top:7px;border:1px solid rgba(217,169,63,.13);border-radius:10px;background:#111713}.v6-existing-highlight img{width:42px;height:42px;border-radius:50%;object-fit:cover}.v6-existing-highlight strong{flex:1}.v6-existing-highlight button{border:1px solid rgba(255,100,80,.28);border-radius:8px;background:#281511;color:#ff9a8b;padding:7px 9px}
.v6-request{display:grid;grid-template-columns:45px 1fr auto;gap:9px;align-items:center;padding:9px;margin-top:7px;border:1px solid rgba(217,169,63,.13);border-radius:10px;background:#111713}.v6-request img{width:45px;height:45px;border-radius:50%;object-fit:cover}.v6-request small{display:block;margin-top:3px;color:#89918b}.v6-request-actions{display:flex;gap:5px}.v6-request-actions button{padding:7px 9px;border:1px solid rgba(217,169,63,.2);border-radius:8px;background:#172019;color:#f2cc72;font-size:8px}.v6-request-actions .accept{background:#d9a93f;color:#111}
.v6-direct-attach{display:inline-flex!important;align-items:center;justify-content:center;width:38px!important;min-width:38px!important;padding:0!important;border-radius:50%!important;background:#111713!important;color:#f2cc72!important}.v6-direct-media{display:block;max-width:240px;max-height:280px;border-radius:10px;object-fit:contain;background:#000}.sn-msg.v6-media{padding:6px!important;background:#111713!important}.sn-msg.mine.v6-media{background:#1a1912!important;color:#eee!important}
@media(max-width:700px){.v6-preview-grid,.v6-story-grid{grid-template-columns:repeat(3,1fr)}.v6-carousel-slide{min-height:220px}.v6-carousel-slide img,.v6-carousel-slide video{max-height:70vh}.v6-actions{flex-direction:column}.v6-request{grid-template-columns:42px 1fr}.v6-request-actions{grid-column:1/-1}.v6-request-actions button{flex:1}}
`;document.head.appendChild(s)}

async function directory(){if(directoryPromise)return directoryPromise;directoryPromise=(async()=>{try{const s=await getDocs(collection(db,"perfis")),profiles=s.docs.map(d=>({uid:d.id,...d.data()})),byHandle=new Map();profiles.forEach(p=>byHandle.set(handleOf(p).toLowerCase(),p));return{profiles,byHandle}}catch{return{profiles:[],byHandle:new Map()}}})();return directoryPromise}
async function profileOf(uid){if(profileCache.has(uid))return profileCache.get(uid);try{const s=await getDoc(doc(db,"perfis",uid)),p=s.exists()?{uid,...s.data()}:{uid,nome:"Atleta",fotoUrl:fallback};p.fotoUrl=p.fotoUrl||fallback;profileCache.set(uid,p);return p}catch{return{uid,nome:"Atleta",fotoUrl:fallback}}}
async function privacyOf(uid){if(privacyCache.has(uid))return privacyCache.get(uid);try{const s=await getDoc(doc(db,"config_perfis",uid)),p=s.exists()?{uid,...s.data()}:{uid,privado:false};privacyCache.set(uid,p);return p}catch{return{uid,privado:false}}}
async function blockedByMe(uid){if(!user||!uid)return false;const key=`${user.uid}:${uid}`;if(blockCache.has(key))return blockCache.get(key);try{const v=(await getDoc(doc(db,"bloqueios",user.uid,"usuarios",uid))).exists();blockCache.set(key,v);return v}catch{return false}}
async function follows(uid){if(!user||!uid)return false;const key=`${user.uid}:${uid}`;if(followCache.has(key))return followCache.get(key);try{const v=(await getDoc(doc(db,"seguidores",uid,"usuarios",user.uid))).exists();followCache.set(key,v);return v}catch{return false}}
async function contentAllowed(ownerUid){if(!ownerUid)return true;if(user?.uid===ownerUid)return true;if(user&&await blockedByMe(ownerUid))return false;const p=await privacyOf(ownerUid);return !p.privado||await follows(ownerUid)}
function tagsOf(text){return[...new Set((String(text||"").match(/#[\p{L}\p{N}_-]+/gu)||[]).map(x=>x.slice(1).toLowerCase()))].slice(0,30)}
function mentionsOf(text){return[...new Set((String(text||"").match(/@[a-z0-9_-]+/gi)||[]).map(x=>x.slice(1).toLowerCase()))].slice(0,20)}

async function richen(el){if(!(el instanceof HTMLElement)||el.dataset.v6Rich==="1")return;const raw=el.textContent||"";if(!/[#@]/.test(raw)){el.dataset.v6Rich="1";return}const {byHandle}=await directory();el.dataset.v6Rich="1";el.classList.add("v6-rich");const parts=raw.split(/(#[\p{L}\p{N}_-]+|@[a-z0-9_-]+)/giu);el.textContent="";parts.forEach(part=>{if(!part)return;if(part[0]==="#"){const a=document.createElement("a");a.href=`hashtags.html?tag=${encodeURIComponent(part.slice(1).toLowerCase())}`;a.textContent=part;el.appendChild(a);return}if(part[0]==="@"){const p=byHandle.get(part.slice(1).toLowerCase());if(p){const a=document.createElement("a");a.href=`perfil-social.html?uid=${encodeURIComponent(p.uid)}`;a.textContent=part;el.appendChild(a);return}}el.appendChild(document.createTextNode(part))})}
function scanRich(root=document){root.querySelectorAll?.(".social-text,.post-text,.social-comment span,.comment-item p,.pp-content-side p,.reel-caption,.saved-caption,.explore-caption").forEach(richen)}

function carouselHtml(midias,heart=false){return `<div class="v6-carousel" data-v6-index="0"${heart?' data-double-like':''}><div class="v6-carousel-track">${midias.map((m,i)=>`<div class="v6-carousel-slide" data-slide="${i}">${String(m.tipo||m.type||"").startsWith("video")?`<video src="${esc(m.url||"")}" controls playsinline preload="metadata"></video>`:`<img src="${esc(m.url||"")}" alt="Mídia ${i+1} do carrossel" loading="lazy" decoding="async">`}</div>`).join("")}</div><button class="v6-carousel-nav v6-carousel-prev" type="button">‹</button><button class="v6-carousel-nav v6-carousel-next" type="button">›</button><span class="v6-carousel-count">1/${midias.length}</span><span class="v6-carousel-dots">${midias.map((_,i)=>`<i class="${i===0?"active":""}"></i>`).join("")}</span>${heart?'<span class="feed-heart-pop">❤</span>':""}</div>`}
function syncCarousel(box){const slides=box.querySelectorAll(".v6-carousel-slide"),max=slides.length-1,index=Math.max(0,Math.min(Number(box.dataset.v6Index||0),max));box.dataset.v6Index=String(index);box.querySelector(".v6-carousel-track").style.transform=`translateX(${-100*index}%)`;box.querySelector(".v6-carousel-count").textContent=`${index+1}/${slides.length}`;box.querySelectorAll(".v6-carousel-dots i").forEach((d,i)=>d.classList.toggle("active",i===index));box.querySelector(".v6-carousel-prev").disabled=index===0;box.querySelector(".v6-carousel-next").disabled=index===max}
function bindCarousel(box){if(!box||box.dataset.v6Bound)return;box.dataset.v6Bound="1";box.addEventListener("click",e=>{const b=e.target.closest(".v6-carousel-nav");if(!b)return;e.preventDefault();e.stopPropagation();box.dataset.v6Index=String(Number(box.dataset.v6Index||0)+(b.classList.contains("v6-carousel-next")?1:-1));syncCarousel(box)});syncCarousel(box)}
async function carouselData(id){if(carouselCache.has(id))return carouselCache.get(id);try{const s=await getDoc(doc(db,"publicacoes",id)),x=s.exists()?s.data():null,r=x&&Array.isArray(x.midias)&&x.midias.length>1?x:null;carouselCache.set(id,r);return r}catch{return null}}
async function enhanceCarousels(root=document){const cards=[...root.querySelectorAll?.(".social-post[data-post-id],.post-card[data-post-id]")||[]].filter(c=>!c.dataset.v6CarouselChecked);for(const card of cards){card.dataset.v6CarouselChecked="1";const data=await carouselData(card.dataset.postId);if(!data)continue;const frame=card.querySelector(".social-media-frame");if(frame){frame.outerHTML=carouselHtml(data.midias,true);bindCarousel(card.querySelector(".v6-carousel"));continue}const image=card.querySelector(".post-image");if(image){const temp=document.createElement("div");temp.innerHTML=carouselHtml(data.midias);image.replaceWith(temp.firstElementChild);bindCarousel(card.querySelector(".v6-carousel"))}}}
async function enhanceProfileCarousel(){if(!/perfil-social\.html$/i.test(location.pathname))return;const target=new URLSearchParams(location.search).get("uid");if(!target)return;let docs=[];try{const s=await getDocs(query(collection(db,"publicacoes"),where("ownerUid","==",target),where("aprovado","==",true),limit(100)));docs=s.docs.map(d=>({id:d.id,...d.data()})).filter(x=>Array.isArray(x.midias)&&x.midias.length>1)}catch{}if(!docs.length)return;const byCover=new Map(docs.map(x=>[String(x.imagemUrl||x.imagem||""),x]));document.querySelectorAll("#gallery .pp-grid-item").forEach(item=>{const media=item.querySelector("img,video"),data=byCover.get(media?.currentSrc||media?.src||"");if(data&&!item.querySelector(".v6-carousel-badge"))item.insertAdjacentHTML("beforeend",'<span class="v6-carousel-badge">▦</span>')});const mediaBox=$("ppContentModal")?.querySelector(".pp-content-media");if(mediaBox&&!mediaBox.dataset.v6CarouselWatcher){mediaBox.dataset.v6CarouselWatcher="1";new MutationObserver(()=>{if(mediaBox.querySelector(".v6-carousel"))return;const m=mediaBox.querySelector("img,video"),data=byCover.get(m?.currentSrc||m?.src||"");if(data){mediaBox.innerHTML=carouselHtml(data.midias);bindCarousel(mediaBox.querySelector(".v6-carousel"))}}).observe(mediaBox,{childList:true,subtree:true})}}

function ensureCarouselModal(){if($("v6CarouselModal"))return;document.body.insertAdjacentHTML("beforeend",`<div id="v6CarouselModal" class="v6-modal"><div class="v6-modal-card"><div class="v6-modal-head"><div><span class="v6-kicker">NOVA PUBLICAÇÃO</span><h2>Carrossel</h2><small>Selecione de 2 a 10 fotos/vídeos. Inclua pelo menos uma foto para a capa.</small></div><button class="v6-close">×</button></div><label class="v6-field"><span>MÍDIAS</span><input id="v6CarouselFiles" type="file" multiple accept="image/jpeg,image/png,image/webp,video/mp4,video/webm,video/quicktime"></label><div id="v6CarouselPreview" class="v6-preview-grid"></div><label class="v6-field"><span>LEGENDA</span><textarea id="v6CarouselCaption" maxlength="2200" placeholder="Use #hashtags e @menções..."></textarea></label><div class="v6-actions"><button class="v6-cancel">CANCELAR</button><button id="v6CarouselPublish" class="primary">PUBLICAR CARROSSEL</button></div><div id="v6CarouselStatus" class="v6-status"></div></div></div>`);const m=$("v6CarouselModal"),files=$("v6CarouselFiles"),preview=$("v6CarouselPreview"),close=()=>{m.classList.remove("open");files.value="";preview.innerHTML="";$("v6CarouselCaption").value="";$("v6CarouselStatus").textContent=""};m.querySelector(".v6-close").onclick=close;m.querySelector(".v6-cancel").onclick=close;m.onclick=e=>{if(e.target===m)close()};files.onchange=()=>{[...files.files].slice(0,10).forEach(()=>{});preview.innerHTML=[...files.files].slice(0,10).map((f,i)=>{const url=URL.createObjectURL(f);return `<div class="v6-preview"><b>${i+1}</b>${f.type.startsWith("video/")?`<video src="${url}" muted></video>`:`<img src="${url}" alt="Prévia">`}</div>`}).join("")};$("v6CarouselPublish").onclick=publishCarousel}
function openCarousel(){if(!user){location.href=`conta.html?tab=login&return=${encodeURIComponent(location.pathname+location.search)}`;return}ensureCarouselModal();$("v6CarouselModal").classList.add("open")}
async function notifyMentions(caption,sourceId){const handles=mentionsOf(caption);if(!user||!handles.length)return;const {byHandle}=await directory(),me=await profileOf(user.uid);for(const h of handles){const p=byHandle.get(h);if(p&&p.uid!==user.uid)await createNotification(p.uid,"mention",{sourceId,text:`mencionou você: @${h}`}).catch(()=>{})}}
async function publishCarousel(){const files=[...($("v6CarouselFiles")?.files||[])].slice(0,10),caption=String($("v6CarouselCaption")?.value||"").trim().slice(0,2200),st=$("v6CarouselStatus"),btn=$("v6CarouselPublish");if(files.length<2){st.className="v6-status error";st.textContent="Selecione pelo menos 2 mídias.";return}if(!files.some(f=>f.type.startsWith("image/"))){st.className="v6-status error";st.textContent="Inclua pelo menos uma foto para servir de capa.";return}for(const f of files){if(!f.type.startsWith("image/")&&!f.type.startsWith("video/")){st.className="v6-status error";st.textContent="Arquivo incompatível.";return}if(f.type.startsWith("image/")&&f.size>25*1024*1024){st.className="v6-status error";st.textContent="Cada foto pode ter até 25 MB.";return}if(f.type.startsWith("video/")&&f.size>45*1024*1024){st.className="v6-status error";st.textContent="Cada vídeo pode ter até 45 MB.";return}}btn.disabled=true;try{const midias=[];for(let i=0;i<files.length;i++){st.textContent=`Enviando ${i+1}/${files.length}...`;const f=files[i],up=await uploadCloudinary(f,{maxBytes:f.type.startsWith("video/")?45*1024*1024:25*1024*1024,allowImage:true,allowVideo:true,tags:["cadastro-de-atletas","carrossel"]});midias.push({url:up.url,path:up.path,tipo:f.type.startsWith("video/")?"video":"image",mime:up.mime||f.type,tamanho:Number(up.size||f.size||0)})}const cover=midias.find(x=>x.tipo==="image"),me=await profileOf(user.uid),ref=doc(collection(db,"publicacoes"));await setDoc(ref,{ownerUid:user.uid,ownerEmail:user.email||"",nome:me.nome||"Atleta",texto:caption,imagem:cover.url,imagemUrl:cover.url,imagemPath:cover.path||"",imagemMime:cover.mime||"image/jpeg",imagemTamanho:Number(cover.tamanho||0),legenda:caption,tipo:"carrossel",midias,hashtags:tagsOf(caption),mencoes:mentionsOf(caption),armazenamento:"cloudinary",aprovado:true,status:"publicado",criadoEm:Timestamp.now()});await notifyMentions(caption,ref.id);st.className="v6-status ok";st.textContent="Carrossel publicado!";setTimeout(()=>location.reload(),650)}catch(e){console.error(e);st.className="v6-status error";st.textContent=e?.message||"Não foi possível publicar."}finally{btn.disabled=false}}
function installCarouselLaunchers(){const choices=document.querySelector("#publishModal .publish-options");if(choices&&!choices.querySelector(".v6-carousel-launch")){const b=document.createElement("button");b.type="button";b.className="pp-btn v6-carousel-launch";b.textContent="▦ POSTAR CARROSSEL";b.onclick=e=>{e.preventDefault();e.stopPropagation();$("publishModal")?.classList.remove("open");openCarousel()};choices.appendChild(b)}const form=$("publishForm");if(form&&!form.querySelector(".v6-carousel-launch")){const b=document.createElement("button");b.type="button";b.className="community-gold-button v6-carousel-launch";b.innerHTML="<span>▦ CRIAR CARROSSEL</span><strong>＋</strong>";b.onclick=e=>{e.preventDefault();openCarousel()};form.querySelector(".publish-form-footer")?.appendChild(b)}}

async function pendingRequest(target){if(!user)return false;try{return(await getDoc(doc(db,"solicitacoes_seguir",target,"usuarios",user.uid))).exists()}catch{return false}}
function ensurePrivacyModal(){if($("v6PrivacyModal"))return;document.body.insertAdjacentHTML("beforeend",`<div id="v6PrivacyModal" class="v6-modal"><div class="v6-modal-card"><div class="v6-modal-head"><div><span class="v6-kicker">CONTROLE DO PERFIL</span><h2>Privacidade</h2><small>Perfis privados exigem aprovação de novos seguidores dentro do site.</small></div><button class="v6-close">×</button></div><label class="v6-field"><span>VISIBILIDADE</span><select id="v6PrivacySelect"><option value="publico">Perfil público</option><option value="privado">Perfil privado</option></select></label><div class="v6-actions"><button class="v6-cancel">CANCELAR</button><button id="v6PrivacySave" class="primary">SALVAR</button></div><div id="v6PrivacyStatus" class="v6-status"></div></div></div>`);const m=$("v6PrivacyModal"),close=()=>m.classList.remove("open");m.querySelector(".v6-close").onclick=close;m.querySelector(".v6-cancel").onclick=close;m.onclick=e=>{if(e.target===m)close()};$("v6PrivacySave").onclick=async()=>{const btn=$("v6PrivacySave"),st=$("v6PrivacyStatus"),privado=$("v6PrivacySelect").value==="privado";btn.disabled=true;try{await setDoc(doc(db,"config_perfis",user.uid),{uid:user.uid,privado,atualizadoEm:Timestamp.now()},{merge:true});privacyCache.set(user.uid,{uid:user.uid,privado});st.className="v6-status ok";st.textContent=privado?"Perfil privado ativado.":"Perfil público ativado.";setTimeout(()=>location.reload(),450)}catch(e){console.error(e);st.className="v6-status error";st.textContent="Não foi possível salvar."}finally{btn.disabled=false}}}
function ensureRequestsModal(){if($("v6RequestsModal"))return;document.body.insertAdjacentHTML("beforeend",`<div id="v6RequestsModal" class="v6-modal"><div class="v6-modal-card"><div class="v6-modal-head"><div><span class="v6-kicker">PERFIL PRIVADO</span><h2>Solicitações para seguir</h2></div><button class="v6-close">×</button></div><div id="v6RequestsList" class="v6-status">Carregando...</div></div></div>`);const m=$("v6RequestsModal"),close=()=>m.classList.remove("open");m.querySelector(".v6-close").onclick=close;m.onclick=e=>{if(e.target===m)close()}}
async function openRequests(){ensureRequestsModal();const m=$("v6RequestsModal"),box=$("v6RequestsList");m.classList.add("open");box.innerHTML="Carregando...";try{const snap=await getDocs(collection(db,"solicitacoes_seguir",user.uid,"usuarios")),rows=[];for(const d of snap.docs){const p=await profileOf(d.id);rows.push(`<div class="v6-request" data-request="${esc(d.id)}"><img src="${esc(p.fotoUrl||fallback)}" alt=""><div><strong>${esc(p.nome||"Atleta")}</strong><small>@${esc(handleOf(p))}</small></div><div class="v6-request-actions"><button class="accept">ACEITAR</button><button class="reject">RECUSAR</button></div></div>`)}box.className="";box.innerHTML=rows.join("")||'<div class="v6-status">Nenhuma solicitação pendente.</div>';box.querySelectorAll("[data-request]").forEach(row=>{row.querySelector(".accept").onclick=()=>acceptRequest(row.dataset.request,row);row.querySelector(".reject").onclick=()=>rejectRequest(row.dataset.request,row)})}catch(e){box.className="v6-status error";box.textContent="Não foi possível carregar."}}
async function acceptRequest(uid,row){try{await setDoc(doc(db,"seguidores",user.uid,"usuarios",uid),{uid,criadoEm:Timestamp.now()});await setDoc(doc(db,"seguindo",uid,"usuarios",user.uid),{uid:user.uid,criadoEm:Timestamp.now()});await deleteDoc(doc(db,"solicitacoes_seguir",user.uid,"usuarios",uid));row.remove()}catch(e){console.error(e);alert("Não foi possível aceitar.")}}
async function rejectRequest(uid,row){try{await deleteDoc(doc(db,"solicitacoes_seguir",user.uid,"usuarios",uid));row.remove()}catch{}}
async function toggleBlock(target,button){const blocked=await blockedByMe(target);button.disabled=true;try{if(blocked){await deleteDoc(doc(db,"bloqueios",user.uid,"usuarios",target));blockCache.set(`${user.uid}:${target}`,false);button.textContent="⊘ BLOQUEAR";location.reload()}else{if(!confirm("Bloquear este perfil? Novas curtidas, follows e mensagens entre vocês serão impedidas."))return;await setDoc(doc(db,"bloqueios",user.uid,"usuarios",target),{uid:target,criadoEm:Timestamp.now()});blockCache.set(`${user.uid}:${target}`,true);await Promise.allSettled([deleteDoc(doc(db,"seguindo",user.uid,"usuarios",target)),deleteDoc(doc(db,"seguidores",target,"usuarios",user.uid)),deleteDoc(doc(db,"seguindo",target,"usuarios",user.uid)),deleteDoc(doc(db,"seguidores",user.uid,"usuarios",target)),deleteDoc(doc(db,"solicitacoes_seguir",target,"usuarios",user.uid)),deleteDoc(doc(db,"solicitacoes_seguir",user.uid,"usuarios",target))]);location.reload()}}catch(e){console.error(e);alert("Não foi possível atualizar o bloqueio.")}finally{button.disabled=false}}

async function installProfilePrivacy(){if(!/perfil-social\.html$/i.test(location.pathname))return;const target=new URLSearchParams(location.search).get("uid"),actions=$("actions"),info=document.querySelector(".pp-info");if(!target||!actions||!info)return;const p=await profileOf(target),privacy=await privacyOf(target),owner=user?.uid===target,followed=owner?true:await follows(target),blocked=owner?false:await blockedByMe(target);if(!info.querySelector(".v6-handle")){const h=document.createElement("span");h.className="v6-handle";h.innerHTML=`<button type="button">@${esc(handleOf(p))}</button>`;h.querySelector("button").onclick=async()=>{try{await navigator.clipboard.writeText(`@${handleOf(p)}`);h.querySelector("button").textContent="✓ copiado";setTimeout(()=>h.querySelector("button").textContent=`@${handleOf(p)}`,1000)}catch{}};$("meta")?.before(h)}if(privacy.privado&&!$("name")?.querySelector(".v6-private-chip"))$("name")?.insertAdjacentHTML("beforeend",'<span class="v6-private-chip">🔒 PRIVADO</span>');if(owner){if(!$("v6PrivacyButton")){const b=document.createElement("button");b.id="v6PrivacyButton";b.type="button";b.className="pp-btn";b.textContent="🔒 PRIVACIDADE";b.onclick=()=>{ensurePrivacyModal();$("v6PrivacySelect").value=privacy.privado?"privado":"publico";$("v6PrivacyModal").classList.add("open")};actions.appendChild(b)}if(privacy.privado&&!$("v6RequestsButton")){const b=document.createElement("button");b.id="v6RequestsButton";b.type="button";b.className="pp-btn";b.textContent="👤 SOLICITAÇÕES";b.onclick=openRequests;actions.appendChild(b)}return}if(!user)return;if(!$("v6BlockButton")){const b=document.createElement("button");b.id="v6BlockButton";b.type="button";b.className="pp-btn";b.textContent=blocked?"↺ DESBLOQUEAR":"⊘ BLOQUEAR";b.onclick=()=>toggleBlock(target,b);actions.appendChild(b)}if(blocked){document.querySelector(".pp-section")?.setAttribute("hidden","");$("snProfileMessageBtn")?.setAttribute("hidden","");return}const section=document.querySelector(".pp-section");if(privacy.privado&&!followed){if(section)section.hidden=true;if(!$("v6PrivacyLock"))section?.insertAdjacentHTML("afterend",'<div id="v6PrivacyLock" class="v6-lock"><div class="ico">🔒</div><h3>Este perfil é privado</h3><p>Envie uma solicitação para seguir. Após a aprovação, publicações, Stories e Destaques ficam disponíveis dentro da plataforma.</p></div>');const follow=$("followButton");if(follow&&!follow.dataset.v6Private){follow.dataset.v6Private="1";follow.textContent=await pendingRequest(target)?"✓ SOLICITADO":"SOLICITAR PARA SEGUIR"}}else{$("v6PrivacyLock")?.remove();if(section)section.hidden=false}}

document.addEventListener("click",async e=>{const b=e.target.closest?.("#followButton");if(!b||!user||!/perfil-social\.html$/i.test(location.pathname))return;const target=new URLSearchParams(location.search).get("uid");if(!target||target===user.uid)return;const privacy=await privacyOf(target);if(!privacy.privado||await follows(target))return;e.preventDefault();e.stopImmediatePropagation();b.disabled=true;try{const ref=doc(db,"solicitacoes_seguir",target,"usuarios",user.uid),pending=(await getDoc(ref)).exists();if(pending){await deleteDoc(ref);b.textContent="SOLICITAR PARA SEGUIR"}else{await setDoc(ref,{uid:user.uid,status:"pendente",criadoEm:Timestamp.now()});b.textContent="✓ SOLICITADO"}}catch(error){console.error(error);alert("Não foi possível atualizar a solicitação.")}finally{b.disabled=false}},true);

async function loadHighlights(uid){if(highlightCache.has(uid))return highlightCache.get(uid);try{const s=await getDocs(collection(db,"destaques",uid,"itens")),arr=s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>ms(a.criadoEm)-ms(b.criadoEm));highlightCache.set(uid,arr);return arr}catch{return[]}}
async function storiesOfHighlight(h){const arr=[];for(const id of (h.storyIds||[]).slice(0,20)){try{const s=await getDoc(doc(db,"stories",id));if(s.exists())arr.push({id,...s.data()})}catch{}}return arr}
function ensureHighlightSection(){if($("v6Highlights"))return $("v6Highlights");const profile=document.querySelector(".pp-profile");if(!profile)return null;profile.insertAdjacentHTML("afterend",'<section id="v6Highlights" class="v6-highlights"><div class="v6-highlights-head">DESTAQUES</div><div id="v6HighlightsRow" class="v6-highlights-row"></div></section>');return $("v6Highlights")}
async function renderHighlights(force=false){if(!/perfil-social\.html$/i.test(location.pathname))return;const target=new URLSearchParams(location.search).get("uid");if(!target||!await contentAllowed(target))return;const section=ensureHighlightSection();if(!section)return;const arr=await loadHighlights(target),owner=user?.uid===target,row=$("v6HighlightsRow"),signature=JSON.stringify([owner,arr.map(x=>[x.id,x.titulo,x.capaUrl,(x.storyIds||[]).join(",")])]);if(!force&&row.dataset.signature===signature)return;row.dataset.signature=signature;row.innerHTML=`${owner?'<div class="v6-highlight v6-highlight-add"><div class="v6-highlight-ring">＋</div><span>Novo</span></div>':""}${arr.map((h,i)=>`<div class="v6-highlight" data-hi="${i}"><div class="v6-highlight-ring"><img src="${esc(h.capaUrl||fallback)}" alt=""></div><span>${esc(h.titulo||"Destaque")}</span></div>`).join("")}`;row.querySelector(".v6-highlight-add")?.addEventListener("click",openHighlightEditor);row.querySelectorAll("[data-hi]").forEach(el=>el.onclick=async()=>{const stories=await storiesOfHighlight(arr[Number(el.dataset.hi)]);if(stories.length)openStoryViewer(stories,0)})}
function ensureHighlightModal(){if($("v6HighlightModal"))return;document.body.insertAdjacentHTML("beforeend",`<div id="v6HighlightModal" class="v6-modal"><div class="v6-modal-card"><div class="v6-modal-head"><div><span class="v6-kicker">STORIES PERMANENTES</span><h2>Destaques</h2><small>Escolha Stories do arquivo para manter no topo do perfil.</small></div><button class="v6-close">×</button></div><div id="v6ExistingHighlights"></div><label class="v6-field"><span>TÍTULO</span><input id="v6HighlightTitle" maxlength="30" placeholder="Ex.: Campeonatos"></label><div id="v6HighlightStories" class="v6-story-grid"></div><div class="v6-actions"><button class="v6-cancel">CANCELAR</button><button id="v6HighlightSave" class="primary">CRIAR DESTAQUE</button></div><div id="v6HighlightStatus" class="v6-status"></div></div></div>`);const m=$("v6HighlightModal"),close=()=>m.classList.remove("open");m.querySelector(".v6-close").onclick=close;m.querySelector(".v6-cancel").onclick=close;m.onclick=e=>{if(e.target===m)close()};$("v6HighlightSave").onclick=createHighlight}
async function openHighlightEditor(){ensureHighlightModal();const m=$("v6HighlightModal");m.classList.add("open");const [stories,highlights]=await Promise.all([getDocs(query(collection(db,"stories"),where("ownerUid","==",user.uid),where("aprovado","==",true),limit(120))).then(s=>s.docs.map(d=>({id:d.id,...d.data()}))).catch(()=>[]),loadHighlights(user.uid)]);$("v6HighlightStories").innerHTML=stories.sort((a,b)=>ms(b.criadoEm)-ms(a.criadoEm)).map(s=>`<label class="v6-story-option"><input type="checkbox" value="${esc(s.id)}">${(s.mediaType||s.tipo)==="video"?`<video src="${esc(s.mediaUrl||"")}" muted></video>`:`<img src="${esc(s.mediaUrl||"")}" alt="Story">`}</label>`).join("")||'<div class="v6-status">Publique Stories primeiro.</div>';$("v6ExistingHighlights").innerHTML=highlights.map(h=>`<div class="v6-existing-highlight" data-highlight="${esc(h.id)}"><img src="${esc(h.capaUrl||fallback)}"><strong>${esc(h.titulo||"Destaque")}</strong><button>EXCLUIR</button></div>`).join("");$("v6ExistingHighlights").querySelectorAll("[data-highlight]").forEach(row=>row.querySelector("button").onclick=async()=>{if(!confirm("Excluir este Destaque? Os Stories originais continuam no arquivo."))return;await deleteDoc(doc(db,"destaques",user.uid,"itens",row.dataset.highlight));highlightCache.delete(user.uid);row.remove();await renderHighlights(true)})}
async function createHighlight(){const title=String($("v6HighlightTitle")?.value||"").trim().slice(0,30),ids=[...$("v6HighlightStories").querySelectorAll("input:checked")].map(x=>x.value).slice(0,20),st=$("v6HighlightStatus"),btn=$("v6HighlightSave");if(!title||!ids.length){st.className="v6-status error";st.textContent="Informe um título e selecione pelo menos um Story.";return}btn.disabled=true;try{const first=await getDoc(doc(db,"stories",ids[0])),cover=first.exists()?first.data().mediaUrl||"":"";await addDoc(collection(db,"destaques",user.uid,"itens"),{ownerUid:user.uid,titulo:title,capaUrl:cover,storyIds:ids,criadoEm:Timestamp.now(),atualizadoEm:Timestamp.now()});highlightCache.delete(user.uid);st.className="v6-status ok";st.textContent="Destaque criado!";await renderHighlights(true);setTimeout(()=>$("v6HighlightModal").classList.remove("open"),450)}catch(e){console.error(e);st.className="v6-status error";st.textContent="Não foi possível criar."}finally{btn.disabled=false}}

async function renderPrivateStories(){const box=$("homeStories");if(!box||box.dataset.v6Rendering==="1")return;box.dataset.v6Rendering="1";try{const snap=await getDocs(query(collection(db,"stories"),where("aprovado","==",true),limit(100))),now=Date.now(),groups=new Map();for(const d of snap.docs){const s={id:d.id,...d.data()};if(ms(s.expiraEm)&&ms(s.expiraEm)<=now)continue;if(!await contentAllowed(s.ownerUid))continue;if(!groups.has(s.ownerUid))groups.set(s.ownerUid,[]);groups.get(s.ownerUid).push(s)}const rows=[];for(const [uid,stories] of groups){const p=await profileOf(uid);stories.sort((a,b)=>ms(a.criadoEm)-ms(b.criadoEm));rows.push({uid,p,stories})}rows.sort((a,b)=>ms(b.stories[b.stories.length-1]?.criadoEm)-ms(a.stories[a.stories.length-1]?.criadoEm));const signature=rows.map(r=>`${r.uid}:${r.stories.map(s=>s.id).join(",")}`).join("|");if(box.dataset.v6Signature!==signature){box.dataset.v6Signature=signature;box.innerHTML=rows.length?rows.map((r,i)=>`<article class="story-item" data-v6-story="${i}"><div class="story-ring"><img src="${esc(r.p.fotoUrl||fallback)}" alt=""></div><span>${esc((r.p.nome||"Atleta").split(" ")[0])}</span></article>`).join(""):'<div class="sn-empty">Nenhum Story ativo agora.</div>';box.querySelectorAll("[data-v6-story]").forEach(el=>el.onclick=()=>openStoryViewer(rows[Number(el.dataset.v6Story)].stories,0))}}catch(e){console.warn("Stories privados:",e)}finally{box.dataset.v6Rendering="0"}}

function conversationId(a,b){return[a,b].sort().join("__")}
function installDirectAttach(){const form=$("snChatForm");if(!form||form.querySelector(".v6-direct-attach"))return;const b=document.createElement("button"),input=document.createElement("input");b.type="button";b.className="v6-direct-attach";b.title="Enviar foto ou vídeo";b.textContent="＋";input.type="file";input.hidden=true;input.accept="image/jpeg,image/png,image/webp,video/mp4,video/webm,video/quicktime";b.onclick=()=>input.click();input.onchange=()=>{const f=input.files?.[0];if(f)sendDirectMedia(f,b);input.value=""};form.prepend(b,input)}
async function sendDirectMedia(file,button){if(!user)return;let other=activeDirectOtherUid;if(!other&&/perfil-social\.html$/i.test(location.pathname))other=new URLSearchParams(location.search).get("uid")||"";if(!other||other===user.uid){alert("Abra uma conversa antes de anexar mídia.");return}if(await blockedByMe(other)){alert("Desbloqueie este perfil para enviar mídia.");return}const video=file.type.startsWith("video/");if(!file.type.startsWith("image/")&&!video){alert("Escolha uma foto ou vídeo.");return}if(!video&&file.size>25*1024*1024){alert("A foto pode ter até 25 MB.");return}if(video&&file.size>45*1024*1024){alert("O vídeo pode ter até 45 MB.");return}button.disabled=true;try{const up=await uploadCloudinary(file,{maxBytes:video?45*1024*1024:25*1024*1024,allowImage:true,allowVideo:true,tags:["cadastro-de-atletas","direct"]}),cid=conversationId(user.uid,other),conv=doc(db,"conversas",cid),existing=await getDoc(conv),label=video?"🎥 Vídeo":"📷 Foto";if(!existing.exists())await setDoc(conv,{participants:[user.uid,other].sort(),lastMessage:"",lastSenderUid:"",lastMessageAt:Timestamp.now(),lastReadBy:[user.uid],createdAt:Timestamp.now()});await addDoc(collection(db,"conversas",cid,"mensagens"),{senderUid:user.uid,text:"",type:video?"video":"image",mediaUrl:up.url,mediaPath:up.path,mediaMime:up.mime||file.type,mediaSize:Number(up.size||file.size||0),createdAt:Timestamp.now()});await setDoc(conv,{lastMessage:label,lastSenderUid:user.uid,lastMessageAt:Timestamp.now(),lastReadBy:[user.uid]},{merge:true});await createNotification(other,"message",{sourceId:cid,text:label})}catch(e){console.error(e);alert("Não foi possível enviar a mídia.")}finally{button.disabled=false}}
async function decorateDirect(){if(directDecorating)return;const list=$("snChatMessages"),other=activeDirectOtherUid||(/perfil-social\.html$/i.test(location.pathname)?new URLSearchParams(location.search).get("uid")||"":"");if(!list||!user||!other)return;directDecorating=true;try{const cid=conversationId(user.uid,other),snap=await getDocs(query(collection(db,"conversas",cid,"mensagens"),orderBy("createdAt","asc"),limit(200))),nodes=[...list.querySelectorAll(".sn-msg")];if(nodes.length!==snap.docs.length)return;snap.docs.forEach((d,i)=>{const x=d.data(),node=nodes[i];if(!node||!["image","video"].includes(x.type)||node.dataset.v6Media)return;node.dataset.v6Media="1";node.classList.add("v6-media");[...node.childNodes].filter(n=>n.nodeType===Node.TEXT_NODE).forEach(n=>n.remove());const time=node.querySelector("small"),media=document.createElement(x.type==="video"?"video":"img");media.className="v6-direct-media";media.src=x.mediaUrl||"";if(x.type==="video"){media.controls=true;media.playsInline=true}node.insertBefore(media,node.firstChild);if(x.text){const cap=document.createElement("span");cap.textContent=x.text;node.insertBefore(cap,time)}})}catch(e){console.warn("Direct mídia:",e)}finally{directDecorating=false}}

document.addEventListener("click",e=>{const row=e.target.closest?.("[data-sn-other]");if(row?.dataset.snOther)activeDirectOtherUid=row.dataset.snOther;const msg=e.target.closest?.("#snProfileMessageBtn");if(msg){const target=new URLSearchParams(location.search).get("uid");if(target)activeDirectOtherUid=target}},true);

async function filterCards(){if(!user)return;const cards=[...document.querySelectorAll(".social-post[data-owner],.social-post[data-post-id],.post-card[data-post-id],[data-owner].explore-item,[data-owner].reel-item")].filter(c=>!c.dataset.v6PrivacyChecked);for(const card of cards){card.dataset.v6PrivacyChecked="1";let owner=card.dataset.owner||"";if(!owner&&card.dataset.postId){try{const s=await getDoc(doc(db,"publicacoes",card.dataset.postId));owner=s.exists()?s.data().ownerUid||"":"";if(owner)card.dataset.owner=owner}catch{}}if(owner&&!await contentAllowed(owner))card.remove()}}
function installHashtagNav(){document.querySelectorAll(".site-menu-nav,.pp-nav").forEach(nav=>{if(nav.querySelector('[data-v6-link="hashtags"]'))return;const a=document.createElement("a");a.href="hashtags.html";a.dataset.v6Link="hashtags";a.innerHTML="<span>＃</span><span>HASHTAGS</span>";nav.appendChild(a)})}

async function run(){installStyles();ensureCarouselModal();installCarouselLaunchers();scanRich();await enhanceCarousels();await enhanceProfileCarousel();await installProfilePrivacy();await renderHighlights();installDirectAttach();await decorateDirect();installHashtagNav();await filterCards();await renderPrivateStories()}
function schedule(){clearTimeout(scheduleTimer);scheduleTimer=setTimeout(()=>run().catch(e=>console.warn("V6:",e)),120)}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",schedule,{once:true});else schedule();
new MutationObserver(mutations=>{let relevant=false;for(const m of mutations){for(const n of m.addedNodes){if(n instanceof Element&&(n.matches?.(".social-post,.post-card,.pp-grid-item,.sn-msg,.story-item,#actions,#snChatForm")||n.querySelector?.(".social-post,.post-card,.pp-grid-item,.sn-msg,.story-item,#actions,#snChatForm"))){relevant=true;break}}if(relevant)break}if(relevant)schedule()}).observe(document.documentElement,{childList:true,subtree:true});
onAuthStateChanged(auth,u=>{user=u;privacyCache.clear();blockCache.clear();followCache.clear();schedule()});
window.addEventListener("sn:story-deleted",()=>{highlightCache.clear();schedule()});
