import { getApp, getApps, initializeApp } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import { getAuth, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import {
  addDoc, collection, deleteDoc, doc, getDoc, getDocs, getFirestore,
  limit, orderBy, query, setDoc, Timestamp, where
} from "https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
import { uploadCloudinary } from "./cloudinary-upload.js?v=20260831-2";
import { openStoryViewer } from "./social-network.js?v=20260901-2";

const cfg={apiKey:"AIzaSyBMsuR0320Nz3asVRj5axXFvKJ5Ftz9COQ",authDomain:"jogadores-de-volei.firebaseapp.com",projectId:"jogadores-de-volei",storageBucket:"jogadores-de-volei.firebasestorage.app",messagingSenderId:"48728914064",appId:"1:48728914064:web:1dd7aeb705319886f74015"};
const app=getApps().length?getApp():initializeApp(cfg),auth=getAuth(app),db=getFirestore(app);
let currentUser=auth.currentUser;
let profileDirectoryPromise=null;
let activeDirectOtherUid="";
const carouselCache=new Map();
const privacyCache=new Map();
const blockCache=new Map();
const highlightsCache=new Map();
const $=id=>document.getElementById(id);
const esc=v=>{const d=document.createElement("div");d.textContent=v==null?"":String(v);return d.innerHTML};
const ms=v=>v?.toMillis?.()??(v?.seconds?Number(v.seconds)*1000:new Date(v||0).getTime()||0);
const slug=v=>String(v||"").trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,28)||"atleta";
const handleOf=p=>`${slug(p?.nome||"atleta")}-${String(p?.uid||p?.id||"").slice(0,4).toLowerCase()}`;
const mediaUrl=m=>String(m?.url||m?.mediaUrl||m?.imagemUrl||m?.videoUrl||"");
const mediaType=m=>String(m?.tipo||m?.type||m?.mediaType||"").startsWith("video")?"video":"image";
const clampText=(v,n)=>String(v||"").trim().slice(0,n);

function installStyles(){
  if($("socialV6Styles"))return;
  const s=document.createElement("style");s.id="socialV6Styles";s.textContent=`
  .v6-handle{display:block;margin:-1px 0 7px;color:#7f8982;font:700 9px Arial;letter-spacing:.2px}.v6-handle button{border:0;background:transparent;color:#aab2ac;padding:0;font:inherit;cursor:pointer}.v6-handle button:hover{color:#f2cc72}
  .v6-rich a{color:#f2cc72;text-decoration:none;font-weight:800}.v6-rich a:hover{text-decoration:underline}
  .v6-carousel{position:relative;width:100%;background:#020302;overflow:hidden}.v6-carousel-track{display:flex;width:100%;transition:transform .25s ease}.v6-carousel-slide{flex:0 0 100%;width:100%;min-height:260px;display:grid;place-items:center;background:#000}.v6-carousel-slide img,.v6-carousel-slide video{display:block;max-width:100%;max-height:760px;width:auto;height:auto;object-fit:contain;background:#000}.v6-carousel-slide video{width:100%;max-height:760px}.v6-carousel-btn{position:absolute;top:50%;translate:0 -50%;z-index:3;width:34px;height:34px;min-height:34px!important;padding:0!important;border:0!important;border-radius:50%!important;background:rgba(0,0,0,.55)!important;color:#fff!important;font-size:20px!important}.v6-carousel-prev{left:10px}.v6-carousel-next{right:10px}.v6-carousel-count{position:absolute;right:10px;top:10px;z-index:3;padding:5px 8px;border-radius:20px;background:rgba(0,0,0,.6);color:#fff;font:800 9px Arial}.v6-carousel-dots{position:absolute;left:50%;bottom:10px;translate:-50% 0;display:flex;gap:4px;z-index:3}.v6-carousel-dots i{width:5px;height:5px;border-radius:50%;background:rgba(255,255,255,.45)}.v6-carousel-dots i.active{background:#f2cc72}.v6-carousel-badge{position:absolute;right:6px;top:6px;z-index:4;padding:4px 6px;border-radius:999px;background:rgba(0,0,0,.72);color:#fff;font:900 9px Arial}
  .v6-modal{position:fixed;inset:0;z-index:30000;display:none;place-items:center;padding:18px;background:rgba(0,0,0,.82);backdrop-filter:blur(6px)}.v6-modal.open{display:grid}.v6-modal-card{width:min(650px,100%);max-height:90vh;overflow:auto;padding:22px;border:1px solid rgba(217,169,63,.28);border-radius:20px;background:#0b100d;color:#eee;box-shadow:0 30px 100px rgba(0,0,0,.55)}.v6-modal-head{display:flex;align-items:start;justify-content:space-between;gap:12px}.v6-modal-head h2{margin:4px 0 5px;color:#fff}.v6-kicker{color:#f2cc72;font:900 8px Arial;letter-spacing:2px}.v6-close{width:36px;height:36px;min-height:36px!important;padding:0!important;border:1px solid rgba(217,169,63,.25)!important;border-radius:50%!important;background:#111713!important;color:#f2cc72!important;font-size:22px!important}.v6-field{display:grid;gap:7px;margin-top:14px}.v6-field>span{color:#f2cc72;font:900 8px Arial;letter-spacing:1.3px}.v6-field input,.v6-field textarea{width:100%;border:1px solid rgba(217,169,63,.22);border-radius:11px;background:#111713;color:#fff;padding:11px}.v6-field textarea{min-height:100px;resize:vertical}.v6-preview-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:7px;margin-top:10px}.v6-preview{position:relative;aspect-ratio:1;border:1px solid rgba(217,169,63,.16);border-radius:10px;overflow:hidden;background:#030403}.v6-preview img,.v6-preview video{width:100%;height:100%;object-fit:cover}.v6-preview b{position:absolute;left:5px;top:5px;padding:3px 5px;border-radius:30px;background:#000a;color:#fff;font:800 7px Arial}.v6-actions{display:flex;gap:8px;margin-top:16px}.v6-actions button{flex:1;min-height:44px;border-radius:10px;border:1px solid rgba(217,169,63,.3);background:#111713;color:#f2cc72;font-weight:900}.v6-actions .primary{background:linear-gradient(135deg,#f2cc72,#bd8425);color:#111}.v6-status{min-height:18px;margin-top:10px;color:#9da59f;font-size:10px}.v6-status.error{color:#ff9a8b}.v6-status.ok{color:#9be3aa}
  .v6-privacy-lock{margin-top:15px;padding:44px 22px;border:1px solid rgba(217,169,63,.18);border-radius:16px;background:#0b100d;text-align:center}.v6-privacy-lock .ico{font-size:40px}.v6-privacy-lock h3{margin:10px 0 5px;color:#fff}.v6-privacy-lock p{margin:0 auto;max-width:440px;color:#939c95;font-size:11px;line-height:1.5}.v6-private-chip{display:inline-flex;align-items:center;gap:5px;margin-left:6px;padding:3px 7px;border-radius:20px;background:#17211a;color:#f2cc72;font:800 7px Arial;vertical-align:middle}
  .v6-highlights{margin-top:15px;padding:13px;border:1px solid rgba(217,169,63,.16);border-radius:15px;background:#0b100d}.v6-highlights-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:9px}.v6-highlights-head strong{font-size:10px;color:#fff}.v6-highlights-row{display:flex;gap:12px;overflow-x:auto;padding:3px 1px 5px;scrollbar-width:none}.v6-highlight{flex:0 0 72px;text-align:center;cursor:pointer}.v6-highlight-ring{width:66px;height:66px;padding:3px;margin:auto;border-radius:50%;background:linear-gradient(135deg,#f2cc72,#8d6925)}.v6-highlight-ring img{width:100%;height:100%;object-fit:cover;border:3px solid #0b100d;border-radius:50%}.v6-highlight span{display:block;margin-top:5px;color:#ddd;font:800 8px Arial;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.v6-highlight-add .v6-highlight-ring{display:grid;place-items:center;border:1px dashed rgba(217,169,63,.5);background:#111713;color:#f2cc72;font-size:24px}
  .v6-story-select{display:grid;grid-template-columns:repeat(4,1fr);gap:7px;max-height:45vh;overflow:auto;margin-top:10px}.v6-story-option{position:relative;aspect-ratio:9/14;border:1px solid rgba(217,169,63,.15);border-radius:9px;overflow:hidden;background:#030403;cursor:pointer}.v6-story-option img,.v6-story-option video{width:100%;height:100%;object-fit:cover}.v6-story-option input{position:absolute;left:6px;top:6px;width:18px;height:18px;accent-color:#d9a93f}.v6-existing-highlight{display:flex;align-items:center;gap:9px;padding:9px;margin-top:7px;border:1px solid rgba(217,169,63,.12);border-radius:10px;background:#111713}.v6-existing-highlight img{width:42px;height:42px;border-radius:50%;object-fit:cover}.v6-existing-highlight strong{flex:1}.v6-existing-highlight button{border:1px solid rgba(255,100,80,.3);background:#271411;color:#ff9a8b;border-radius:8px;padding:7px 9px}
  .v6-direct-attach{display:inline-flex!important;align-items:center;justify-content:center;width:38px!important;min-width:38px!important;padding:0!important;border-radius:50%!important;background:#111713!important;color:#f2cc72!important}.v6-direct-media{display:block;max-width:240px;max-height:280px;border-radius:10px;margin-bottom:5px;object-fit:contain;background:#000}.v6-direct-caption{display:block;margin-top:4px}.sn-msg.media{padding:6px!important;background:#111713!important}.sn-msg.mine.media{background:#1a1912!important;color:#eee!important}
  .v6-request-row{display:grid;grid-template-columns:45px 1fr auto;gap:9px;align-items:center;padding:9px;border:1px solid rgba(217,169,63,.13);border-radius:10px;background:#111713;margin-top:7px}.v6-request-row img{width:45px;height:45px;border-radius:50%;object-fit:cover}.v6-request-row small{display:block;color:#89918b;margin-top:3px}.v6-request-actions{display:flex;gap:5px}.v6-request-actions button{padding:7px 9px;border-radius:8px;border:1px solid rgba(217,169,63,.2);background:#172019;color:#f2cc72;font-size:8px}.v6-request-actions .accept{background:#d9a93f;color:#111}
  @media(max-width:700px){.v6-preview-grid,.v6-story-select{grid-template-columns:repeat(3,1fr)}.v6-carousel-slide{min-height:220px}.v6-carousel-slide img,.v6-carousel-slide video{max-height:70vh}.v6-actions{flex-direction:column}.v6-request-row{grid-template-columns:42px 1fr}.v6-request-actions{grid-column:1/-1}.v6-request-actions button{flex:1}}
  `;document.head.appendChild(s)
}

async function directory(){
  if(profileDirectoryPromise)return profileDirectoryPromise;
  profileDirectoryPromise=(async()=>{
    try{const snap=await getDocs(collection(db,"perfis"));const profiles=snap.docs.map(d=>({uid:d.id,...d.data()}));const byHandle=new Map();profiles.forEach(p=>byHandle.set(handleOf(p).toLowerCase(),p));return{profiles,byHandle}}
    catch(error){console.warn("Diretório V6:",error);return{profiles:[],byHandle:new Map()}}
  })();
  return profileDirectoryPromise
}

function hashtagsOf(text){return[...new Set((String(text||"").match(/#[\p{L}\p{N}_-]+/gu)||[]).map(x=>x.slice(1).toLowerCase()).filter(Boolean))].slice(0,30)}
function mentionHandlesOf(text){return[...new Set((String(text||"").match(/@[a-z0-9_-]+/gi)||[]).map(x=>x.slice(1).toLowerCase()).filter(Boolean))].slice(0,20)}

async function richen(el){
  if(!(el instanceof HTMLElement)||el.dataset.v6Rich==="1")return;
  const raw=el.textContent||"";if(!/[#@]/.test(raw))return;
  el.dataset.v6Rich="1";el.classList.add("v6-rich");
  const {byHandle}=await directory();
  const parts=raw.split(/(#[\p{L}\p{N}_-]+|@[a-z0-9_-]+)/giu);el.textContent="";
  for(const part of parts){
    if(!part)continue;
    if(part.startsWith("#")&&part.length>1){const a=document.createElement("a");a.href=`hashtags.html?tag=${encodeURIComponent(part.slice(1).toLowerCase())}`;a.textContent=part;el.appendChild(a);continue}
    if(part.startsWith("@")&&part.length>1){const p=byHandle.get(part.slice(1).toLowerCase());if(p){const a=document.createElement("a");a.href=`perfil-social.html?uid=${encodeURIComponent(p.uid)}`;a.textContent=part;el.appendChild(a);continue}}
    el.appendChild(document.createTextNode(part))
  }
}

function scanRichText(root=document){root.querySelectorAll?.(".social-text,.post-text,.social-comment span,.comment-item p,.pp-content-side p,.reel-caption,.saved-caption,.explore-caption").forEach(richen)}

function carouselMarkup(midias,{heart=false}={}){
  const slides=midias.map((m,i)=>`<div class="v6-carousel-slide" data-v6-slide="${i}">${mediaType(m)==="video"?`<video src="${esc(mediaUrl(m))}" controls playsinline preload="metadata"></video>`:`<img src="${esc(mediaUrl(m))}" alt="Mídia ${i+1} do carrossel" loading="lazy" decoding="async">`}</div>`).join("");
  return `<div class="v6-carousel" data-v6-index="0"><div class="v6-carousel-track">${slides}</div><button class="v6-carousel-btn v6-carousel-prev" type="button" aria-label="Mídia anterior">‹</button><button class="v6-carousel-btn v6-carousel-next" type="button" aria-label="Próxima mídia">›</button><span class="v6-carousel-count">1/${midias.length}</span><span class="v6-carousel-dots">${midias.map((_,i)=>`<i class="${i===0?"active":""}"></i>`).join("")}</span>${heart?'<span class="feed-heart-pop">❤</span>':""}</div>`
}
function syncCarousel(box){const total=box.querySelectorAll(".v6-carousel-slide").length,index=Math.max(0,Math.min(Number(box.dataset.v6Index||0),total-1));box.dataset.v6Index=String(index);const track=box.querySelector(".v6-carousel-track");if(track)track.style.transform=`translateX(${-100*index}%)`;const count=box.querySelector(".v6-carousel-count");if(count)count.textContent=`${index+1}/${total}`;box.querySelectorAll(".v6-carousel-dots i").forEach((d,i)=>d.classList.toggle("active",i===index));box.querySelector(".v6-carousel-prev")?.toggleAttribute("disabled",index<=0);box.querySelector(".v6-carousel-next")?.toggleAttribute("disabled",index>=total-1)}
function bindCarousel(box){if(!box||box.dataset.v6Bound==="1")return;box.dataset.v6Bound="1";box.addEventListener("click",e=>{const b=e.target.closest(".v6-carousel-btn");if(!b)return;e.preventDefault();e.stopPropagation();const delta=b.classList.contains("v6-carousel-next")?1:-1;box.dataset.v6Index=String(Number(box.dataset.v6Index||0)+delta);syncCarousel(box)});syncCarousel(box)}

async function postCarouselData(id){
  if(carouselCache.has(id))return carouselCache.get(id);
  try{const snap=await getDoc(doc(db,"publicacoes",id)),data=snap.exists()?snap.data():null;const out=data&&Array.isArray(data.midias)&&data.midias.length>1?data:null;carouselCache.set(id,out);return out}catch{return null}
}
async function enhanceFeedCarousels(root=document){
  const cards=[...root.querySelectorAll?.(".social-post[data-post-id],.post-card[data-post-id]")||[]].filter(x=>x.dataset.v6CarouselChecked!=="1");
  for(const card of cards){card.dataset.v6CarouselChecked="1";const data=await postCarouselData(card.dataset.postId);if(!data)continue;let frame=card.querySelector(".social-media-frame");if(frame){frame.outerHTML=carouselMarkup(data.midias,{heart:true});const box=card.querySelector(".v6-carousel");box?.setAttribute("data-double-like","");bindCarousel(box);continue}const old=card.querySelector(".post-image");if(old){const wrap=document.createElement("div");wrap.innerHTML=carouselMarkup(data.midias);const box=wrap.firstElementChild;old.replaceWith(box);bindCarousel(box)}}
}

async function profileCarouselDocs(){
  const uid=new URLSearchParams(location.search).get("uid");if(!uid)return[];
  try{const snap=await getDocs(query(collection(db,"publicacoes"),where("ownerUid","==",uid),where("aprovado","==",true),limit(100)));return snap.docs.map(d=>({id:d.id,...d.data()})).filter(x=>Array.isArray(x.midias)&&x.midias.length>1)}catch{return[]}
}
async function enhanceProfileCarousels(){
  if(!/perfil-social\.html$/i.test(location.pathname))return;const docs=await profileCarouselDocs();if(!docs.length)return;
  const byCover=new Map(docs.map(x=>[String(x.imagemUrl||x.imagem||""),x]));
  document.querySelectorAll("#gallery .pp-grid-item").forEach(item=>{const media=item.querySelector("img,video"),src=media?.currentSrc||media?.src||"",data=byCover.get(src);if(data&&!item.querySelector(".v6-carousel-badge"))item.insertAdjacentHTML("beforeend",'<span class="v6-carousel-badge">▦</span>')});
  const modal=$("ppContentModal");const mediaBox=modal?.querySelector(".pp-content-media");if(mediaBox&&!mediaBox.dataset.v6Watch){mediaBox.dataset.v6Watch="1";const observer=new MutationObserver(async()=>{const first=mediaBox.querySelector("img,video"),src=first?.currentSrc||first?.src||"",data=byCover.get(src);if(!data||mediaBox.querySelector(".v6-carousel"))return;mediaBox.innerHTML=carouselMarkup(data.midias);bindCarousel(mediaBox.querySelector(".v6-carousel"))});observer.observe(mediaBox,{childList:true,subtree:true})}
}

function ensureCarouselModal(){
  if($("v6CarouselModal"))return;
  document.body.insertAdjacentHTML("beforeend",`<div id="v6CarouselModal" class="v6-modal" aria-hidden="true"><div class="v6-modal-card"><div class="v6-modal-head"><div><span class="v6-kicker">NOVA PUBLICAÇÃO</span><h2>Carrossel</h2><small>Selecione de 2 a 10 fotos/vídeos. Para compatibilidade com todo o site, inclua ao menos uma foto.</small></div><button class="v6-close" type="button">×</button></div><label class="v6-field"><span>MÍDIAS</span><input id="v6CarouselFiles" type="file" accept="image/jpeg,image/png,image/webp,video/mp4,video/webm,video/quicktime" multiple></label><div id="v6CarouselPreview" class="v6-preview-grid"></div><label class="v6-field"><span>LEGENDA</span><textarea id="v6CarouselCaption" maxlength="2200" placeholder="Use #hashtags e mencione atletas pelo @identificador do perfil..."></textarea></label><div class="v6-actions"><button type="button" class="v6-cancel">CANCELAR</button><button type="button" class="primary" id="v6CarouselPublish">PUBLICAR CARROSSEL</button></div><div id="v6CarouselStatus" class="v6-status"></div></div></div>`);
  const modal=$("v6CarouselModal"),files=$("v6CarouselFiles"),preview=$("v6CarouselPreview");
  const close=()=>{modal.classList.remove("open");modal.setAttribute("aria-hidden","true");files.value="";preview.innerHTML="";$("v6CarouselCaption").value="";$("v6CarouselStatus").textContent=""};
  modal.querySelector(".v6-close").onclick=close;modal.querySelector(".v6-cancel").onclick=close;modal.onclick=e=>{if(e.target===modal)close()};
  files.onchange=()=>{const arr=[...files.files].slice(0,10);preview.innerHTML=arr.map((f,i)=>`<div class="v6-preview"><b>${i+1}</b>${f.type.startsWith("video/")?`<video src="${URL.createObjectURL(f)}" muted></video>`:`<img src="${URL.createObjectURL(f)}" alt="Prévia">`}</div>`).join("")};
  $("v6CarouselPublish").onclick=publishCarousel
}
function openCarouselModal(){if(!currentUser){location.href=`conta.html?tab=login&return=${encodeURIComponent(location.pathname+location.search)}`;return}ensureCarouselModal();const m=$("v6CarouselModal");m.classList.add("open");m.setAttribute("aria-hidden","false")}

async function notifyMentions(caption,sourceId){
  if(!currentUser)return;const handles=mentionHandlesOf(caption);if(!handles.length)return;const {byHandle}=await directory();let me={nome:currentUser.displayName||"Atleta",fotoUrl:""};try{const p=await getDoc(doc(db,"perfis",currentUser.uid));if(p.exists())me={...me,...p.data()}}catch{}
  for(const h of handles){const target=byHandle.get(h);if(!target||target.uid===currentUser.uid)continue;try{await addDoc(collection(db,"notificacoes",target.uid,"itens"),{targetUid:target.uid,actorUid:currentUser.uid,actorNome:me.nome||"Atleta",actorFoto:me.fotoUrl||"",type:"mention",sourceId:String(sourceId).slice(0,200),text:`mencionou você: @${h}`,lida:false,createdAt:Timestamp.now()})}catch(error){console.warn("Menção:",error)}}
}

async function publishCarousel(){
  const files=[...($("v6CarouselFiles")?.files||[])].slice(0,10),caption=clampText($("v6CarouselCaption")?.value,2200),status=$("v6CarouselStatus"),button=$("v6CarouselPublish");if(!currentUser)return;if(files.length<2){status.textContent="Selecione pelo menos 2 mídias.";status.className="v6-status error";return}if(!files.some(f=>f.type.startsWith("image/"))){status.textContent="Inclua pelo menos uma foto no carrossel.";status.className="v6-status error";return}for(const f of files){const ok=f.type.startsWith("image/")||f.type.startsWith("video/");if(!ok){status.textContent="Há um arquivo incompatível.";status.className="v6-status error";return}if(f.type.startsWith("image/")&&f.size>25*1024*1024){status.textContent="Cada foto pode ter até 25 MB.";status.className="v6-status error";return}if(f.type.startsWith("video/")&&f.size>45*1024*1024){status.textContent="Cada vídeo pode ter até 45 MB.";status.className="v6-status error";return}}
  button.disabled=true;status.className="v6-status";try{let profile={nome:currentUser.displayName||"Atleta"};try{const p=await getDoc(doc(db,"perfis",currentUser.uid));if(p.exists())profile={...profile,...p.data()}}catch{}const midias=[];for(let i=0;i<files.length;i++){status.textContent=`Enviando ${i+1}/${files.length}...`;const f=files[i],up=await uploadCloudinary(f,{maxBytes:f.type.startsWith("video/")?45*1024*1024:25*1024*1024,allowImage:true,allowVideo:true,tags:["cadastro-de-atletas","carrossel"]});midias.push({url:up.url,path:up.path,tipo:f.type.startsWith("video/")?"video":"image",mime:up.mime||f.type,tamanho:Number(up.size||f.size||0)})}const cover=midias.find(m=>m.tipo==="image");status.textContent="Publicando carrossel...";const ref=doc(collection(db,"publicacoes"));await setDoc(ref,{ownerUid:currentUser.uid,ownerEmail:currentUser.email||"",nome:profile.nome||"Atleta",texto:caption,imagem:cover.url,imagemUrl:cover.url,imagemPath:cover.path||"",imagemMime:cover.mime||"image/jpeg",imagemTamanho:Number(cover.tamanho||0),legenda:caption,tipo:"carrossel",midias,hashtags:hashtagsOf(caption),mencoes:mentionHandlesOf(caption),armazenamento:"cloudinary",aprovado:true,status:"publicado",criadoEm:Timestamp.now()});await notifyMentions(caption,ref.id);status.className="v6-status ok";status.textContent="Carrossel publicado!";setTimeout(()=>location.reload(),650)}catch(error){console.error("Carrossel:",error);status.className="v6-status error";status.textContent=error?.message||"Não foi possível publicar o carrossel."}finally{button.disabled=false}}

function installCarouselLaunchers(){
  const options=document.querySelector(".publish-options");if(options&&!options.querySelector(".v6-carousel-launch")){const b=document.createElement("button");b.type="button";b.className="pp-btn v6-carousel-launch";b.textContent="▦ POSTAR CARROSSEL";b.onclick=e=>{e.preventDefault();$("publishModal")?.classList.remove("open");openCarouselModal()};options.appendChild(b)}
  const form=$("publishForm");if(form&&!form.querySelector(".v6-carousel-launch")){const b=document.createElement("button");b.type="button";b.className="community-gold-button v6-carousel-launch";b.innerHTML="<span>▦ CRIAR CARROSSEL</span><strong>＋</strong>";b.onclick=openCarouselModal;const footer=form.querySelector(".publish-form-footer");footer?.appendChild(b)}
}

async function privacyOf(uid){if(!uid)return{privado:false};if(privacyCache.has(uid))return privacyCache.get(uid);try{const snap=await getDoc(doc(db,"config_perfis",uid)),data=snap.exists()?snap.data():{uid,privado:false};privacyCache.set(uid,data);return data}catch{return{uid,privado:false}}}
async function ownBlockOf(targetUid){if(!currentUser||!targetUid)return false;const key=`${currentUser.uid}:${targetUid}`;if(blockCache.has(key))return blockCache.get(key);try{const exists=(await getDoc(doc(db,"bloqueios",currentUser.uid,"usuarios",targetUid))).exists();blockCache.set(key,exists);return exists}catch{return false}}
async function follows(targetUid){if(!currentUser||!targetUid)return false;try{return(await getDoc(doc(db,"seguidores",targetUid,"usuarios",currentUser.uid))).exists()}catch{return false}}
async function requestPending(targetUid){if(!currentUser||!targetUid)return false;try{return(await getDoc(doc(db,"solicitacoes_seguir",targetUid,"usuarios",currentUser.uid))).exists()}catch{return false}}

function ensurePrivacyModal(){if($("v6PrivacyModal"))return;document.body.insertAdjacentHTML("beforeend",`<div id="v6PrivacyModal" class="v6-modal"><div class="v6-modal-card"><div class="v6-modal-head"><div><span class="v6-kicker">CONTROLE DO PERFIL</span><h2>Privacidade</h2><small>Perfis privados exigem aprovação para novos seguidores dentro da plataforma.</small></div><button class="v6-close" type="button">×</button></div><label class="v6-field"><span>VISIBILIDADE</span><select id="v6PrivacySelect"><option value="publico">Perfil público</option><option value="privado">Perfil privado</option></select></label><div class="v6-actions"><button class="v6-cancel" type="button">CANCELAR</button><button id="v6PrivacySave" class="primary" type="button">SALVAR</button></div><div id="v6PrivacyStatus" class="v6-status"></div></div></div>`);const m=$("v6PrivacyModal"),close=()=>m.classList.remove("open");m.querySelector(".v6-close").onclick=close;m.querySelector(".v6-cancel").onclick=close;m.onclick=e=>{if(e.target===m)close()};$("v6PrivacySave").onclick=savePrivacy}
async function savePrivacy(){if(!currentUser)return;const value=$("v6PrivacySelect").value==="privado",st=$("v6PrivacyStatus"),btn=$("v6PrivacySave");btn.disabled=true;try{await setDoc(doc(db,"config_perfis",currentUser.uid),{uid:currentUser.uid,privado:value,atualizadoEm:Timestamp.now()},{merge:true});privacyCache.set(currentUser.uid,{uid:currentUser.uid,privado:value});st.className="v6-status ok";st.textContent=value?"Perfil configurado como privado.":"Perfil configurado como público.";setTimeout(()=>location.reload(),500)}catch(e){console.error(e);st.className="v6-status error";st.textContent="Não foi possível salvar a privacidade."}finally{btn.disabled=false}}

function ensureRequestsModal(){if($("v6RequestsModal"))return;document.body.insertAdjacentHTML("beforeend",`<div id="v6RequestsModal" class="v6-modal"><div class="v6-modal-card"><div class="v6-modal-head"><div><span class="v6-kicker">PERFIL PRIVADO</span><h2>Solicitações para seguir</h2></div><button class="v6-close" type="button">×</button></div><div id="v6RequestsList"><div class="v6-status">Carregando...</div></div></div></div>`);const m=$("v6RequestsModal"),close=()=>m.classList.remove("open");m.querySelector(".v6-close").onclick=close;m.onclick=e=>{if(e.target===m)close()}}
async function openRequests(){if(!currentUser)return;ensureRequestsModal();const m=$("v6RequestsModal"),box=$("v6RequestsList");m.classList.add("open");box.innerHTML='<div class="v6-status">Carregando...</div>';try{const snap=await getDocs(collection(db,"solicitacoes_seguir",currentUser.uid,"usuarios")),rows=[];for(const d of snap.docs){const p=await getDoc(doc(db,"perfis",d.id));const data=p.exists()?{uid:d.id,...p.data()}:{uid:d.id,nome:"Atleta"};rows.push(`<div class="v6-request-row" data-request-uid="${esc(d.id)}"><img src="${esc(data.fotoUrl||"")}" alt=""><div><strong>${esc(data.nome||"Atleta")}</strong><small>@${esc(handleOf(data))}</small></div><div class="v6-request-actions"><button class="accept" data-accept>ACEITAR</button><button data-reject>RECUSAR</button></div></div>`)}box.innerHTML=rows.join("")||'<div class="v6-status">Nenhuma solicitação pendente.</div>';box.querySelectorAll("[data-request-uid]").forEach(row=>{row.querySelector("[data-accept]").onclick=()=>acceptRequest(row.dataset.requestUid,row);row.querySelector("[data-reject]").onclick=()=>rejectRequest(row.dataset.requestUid,row)})}catch(e){console.error(e);box.innerHTML='<div class="v6-status error">Não foi possível carregar as solicitações.</div>'}}
async function acceptRequest(requesterUid,row){if(!currentUser)return;try{await setDoc(doc(db,"seguidores",currentUser.uid,"usuarios",requesterUid),{uid:requesterUid,criadoEm:Timestamp.now()});await setDoc(doc(db,"seguindo",requesterUid,"usuarios",currentUser.uid),{uid:currentUser.uid,criadoEm:Timestamp.now()});await deleteDoc(doc(db,"solicitacoes_seguir",currentUser.uid,"usuarios",requesterUid));row.remove()}catch(e){console.error(e);alert("Não foi possível aceitar a solicitação.")}}
async function rejectRequest(requesterUid,row){try{await deleteDoc(doc(db,"solicitacoes_seguir",currentUser.uid,"usuarios",requesterUid));row.remove()}catch(e){console.error(e)}}

async function toggleBlock(targetUid,button){if(!currentUser||!targetUid)return;const ref=doc(db,"bloqueios",currentUser.uid,"usuarios",targetUid),blocked=await ownBlockOf(targetUid);button.disabled=true;try{if(blocked){await deleteDoc(ref);blockCache.set(`${currentUser.uid}:${targetUid}`,false);button.textContent="⊘ BLOQUEAR"}else{if(!confirm("Bloquear este perfil? Ele deixará de aparecer para você e novas interações serão impedidas."))return;await setDoc(ref,{uid:targetUid,criadoEm:Timestamp.now()});blockCache.set(`${currentUser.uid}:${targetUid}`,true);await deleteDoc(doc(db,"seguindo",currentUser.uid,"usuarios",targetUid)).catch(()=>{});await deleteDoc(doc(db,"seguidores",targetUid,"usuarios",currentUser.uid)).catch(()=>{});await deleteDoc(doc(db,"solicitacoes_seguir",targetUid,"usuarios",currentUser.uid)).catch(()=>{});button.textContent="↺ DESBLOQUEAR";document.querySelector(".pp-section")?.setAttribute("hidden","")}}catch(e){console.error(e);alert("Não foi possível atualizar o bloqueio.")}finally{button.disabled=false}}

async function installProfilePrivacy(){
  if(!/perfil-social\.html$/i.test(location.pathname))return;const targetUid=new URLSearchParams(location.search).get("uid");if(!targetUid)return;const info=document.querySelector(".pp-info"),actions=$("actions");if(!info||!actions)return;
  const p=await privacyOf(targetUid);const isOwner=currentUser?.uid===targetUid,followed=await follows(targetUid),blocked=isOwner?false:await ownBlockOf(targetUid);if(p.privado&&!info.querySelector(".v6-private-chip"))$("name")?.insertAdjacentHTML("beforeend",'<span class="v6-private-chip">🔒 PRIVADO</span>');
  let profileData={uid:targetUid,nome:$("name")?.childNodes?.[0]?.textContent?.trim()||"Atleta"};try{const snap=await getDoc(doc(db,"perfis",targetUid));if(snap.exists())profileData={uid:targetUid,...snap.data()}}catch{}
  if(!info.querySelector(".v6-handle")){const wrap=document.createElement("span");wrap.className="v6-handle";wrap.innerHTML=`<button type="button" title="Copiar identificador">@${esc(handleOf(profileData))}</button>`;wrap.querySelector("button").onclick=async()=>{try{await navigator.clipboard.writeText(`@${handleOf(profileData)}`);wrap.querySelector("button").textContent="✓ copiado";setTimeout(()=>wrap.querySelector("button").textContent=`@${handleOf(profileData)}`,1200)}catch{}};$("meta")?.before(wrap)}
  if(isOwner){if(!$("v6PrivacyButton")){const b=document.createElement("button");b.id="v6PrivacyButton";b.type="button";b.className="pp-btn";b.textContent=p.privado?"🔒 PRIVACIDADE":"🔓 PRIVACIDADE";b.onclick=()=>{ensurePrivacyModal();$("v6PrivacySelect").value=p.privado?"privado":"publico";$("v6PrivacyModal").classList.add("open")};actions.appendChild(b)}if(p.privado&&!$("v6RequestsButton")){const b=document.createElement("button");b.id="v6RequestsButton";b.type="button";b.className="pp-btn";b.textContent="👤 SOLICITAÇÕES";b.onclick=openRequests;actions.appendChild(b)}return}
  if(!$("v6BlockButton")){const b=document.createElement("button");b.id="v6BlockButton";b.type="button";b.className="pp-btn";b.textContent=blocked?"↺ DESBLOQUEAR":"⊘ BLOQUEAR";b.onclick=()=>toggleBlock(targetUid,b);actions.appendChild(b)}
  if(blocked){document.querySelector(".pp-section")?.setAttribute("hidden","");return}
  if(p.privado&&!followed){const section=document.querySelector(".pp-section");if(section){section.hidden=true;if(!$("v6PrivacyLock"))section.insertAdjacentHTML("afterend",'<div id="v6PrivacyLock" class="v6-privacy-lock"><div class="ico">🔒</div><h3>Este perfil é privado</h3><p>Envie uma solicitação para seguir. Depois da aprovação, publicações, Stories e Destaques ficam visíveis dentro da plataforma.</p></div>')}
    const follow=$("followButton");if(follow){const pending=await requestPending(targetUid);follow.textContent=pending?"✓ SOLICITADO":"SOLICITAR PARA SEGUIR";follow.classList.toggle("following",pending);follow.onclick=null;follow.addEventListener("click",async e=>{e.preventDefault();e.stopImmediatePropagation();const exists=await requestPending(targetUid);follow.disabled=true;try{const ref=doc(db,"solicitacoes_seguir",targetUid,"usuarios",currentUser.uid);if(exists){await deleteDoc(ref);follow.textContent="SOLICITAR PARA SEGUIR";follow.classList.remove("following")}else{await setDoc(ref,{uid:currentUser.uid,status:"pendente",criadoEm:Timestamp.now()});follow.textContent="✓ SOLICITADO";follow.classList.add("following")}}catch(error){console.error(error);alert("Não foi possível atualizar a solicitação.")}finally{follow.disabled=false}},true)}}
}

async function loadHighlights(uid){if(highlightsCache.has(uid))return highlightsCache.get(uid);try{const snap=await getDocs(collection(db,"destaques",uid,"itens")),arr=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>ms(a.criadoEm)-ms(b.criadoEm));highlightsCache.set(uid,arr);return arr}catch{return[]}}
async function highlightStories(item){const out=[];for(const id of (item.storyIds||[]).slice(0,20)){try{const snap=await getDoc(doc(db,"stories",id));if(snap.exists())out.push({id,...snap.data()})}catch{}}return out}
function ensureHighlightsSection(){if($("v6Highlights"))return $("v6Highlights");const profile=document.querySelector(".pp-profile");if(!profile)return null;profile.insertAdjacentHTML("afterend",'<section id="v6Highlights" class="v6-highlights"><div class="v6-highlights-head"><strong>DESTAQUES</strong></div><div id="v6HighlightsRow" class="v6-highlights-row"></div></section>');return $("v6Highlights")}
async function renderHighlights(){if(!/perfil-social\.html$/i.test(location.pathname))return;const uid=new URLSearchParams(location.search).get("uid");if(!uid)return;const p=await privacyOf(uid),allowed=currentUser?.uid===uid||!p.privado||await follows(uid);if(!allowed)return;const section=ensureHighlightsSection();if(!section)return;const arr=await loadHighlights(uid),row=$("v6HighlightsRow"),owner=currentUser?.uid===uid;row.innerHTML=`${owner?'<div class="v6-highlight v6-highlight-add" data-add-highlight><div class="v6-highlight-ring">＋</div><span>Novo</span></div>':""}${arr.map((h,i)=>`<div class="v6-highlight" data-highlight-index="${i}"><div class="v6-highlight-ring"><img src="${esc(h.capaUrl||"")}" alt=""></div><span>${esc(h.titulo||"Destaque")}</span></div>`).join("")}`;row.querySelector("[data-add-highlight]")?.addEventListener("click",openHighlightsEditor);row.querySelectorAll("[data-highlight-index]").forEach(el=>el.onclick=async()=>{const stories=await highlightStories(arr[Number(el.dataset.highlightIndex)]);if(stories.length)openStoryViewer(stories,0)})}

function ensureHighlightsModal(){if($("v6HighlightsModal"))return;document.body.insertAdjacentHTML("beforeend",`<div id="v6HighlightsModal" class="v6-modal"><div class="v6-modal-card"><div class="v6-modal-head"><div><span class="v6-kicker">STORIES PERMANENTES</span><h2>Destaques</h2><small>Escolha Stories do seu arquivo para manter no topo do perfil.</small></div><button class="v6-close" type="button">×</button></div><div id="v6ExistingHighlights"></div><label class="v6-field"><span>TÍTULO</span><input id="v6HighlightTitle" maxlength="30" placeholder="Ex.: Campeonatos"></label><div id="v6HighlightStories" class="v6-story-select"></div><div class="v6-actions"><button class="v6-cancel" type="button">CANCELAR</button><button id="v6HighlightSave" class="primary" type="button">CRIAR DESTAQUE</button></div><div id="v6HighlightStatus" class="v6-status"></div></div></div>`);const m=$("v6HighlightsModal"),close=()=>m.classList.remove("open");m.querySelector(".v6-close").onclick=close;m.querySelector(".v6-cancel").onclick=close;m.onclick=e=>{if(e.target===m)close()};$("v6HighlightSave").onclick=createHighlight}
async function openHighlightsEditor(){if(!currentUser)return;ensureHighlightsModal();const m=$("v6HighlightsModal");m.classList.add("open");const [stories,highlights]=await Promise.all([getDocs(query(collection(db,"stories"),where("ownerUid","==",currentUser.uid),where("aprovado","==",true),limit(120))).then(s=>s.docs.map(d=>({id:d.id,...d.data()}))).catch(()=>[]),loadHighlights(currentUser.uid)]);$("v6HighlightStories").innerHTML=stories.sort((a,b)=>ms(b.criadoEm)-ms(a.criadoEm)).map(s=>`<label class="v6-story-option"><input type="checkbox" value="${esc(s.id)}">${(s.mediaType||s.tipo)==="video"?`<video src="${esc(s.mediaUrl||"")}" muted></video>`:`<img src="${esc(s.mediaUrl||"")}" alt="Story">`}</label>`).join("")||'<div class="v6-status">Publique Stories primeiro para criar um Destaque.</div>';$("v6ExistingHighlights").innerHTML=highlights.map(h=>`<div class="v6-existing-highlight" data-highlight-id="${esc(h.id)}"><img src="${esc(h.capaUrl||"")}" alt=""><strong>${esc(h.titulo||"Destaque")}</strong><button type="button">EXCLUIR</button></div>`).join("");$("v6ExistingHighlights").querySelectorAll("[data-highlight-id]").forEach(row=>row.querySelector("button").onclick=async()=>{if(!confirm("Excluir este Destaque? Os Stories originais continuam no arquivo."))return;try{await deleteDoc(doc(db,"destaques",currentUser.uid,"itens",row.dataset.highlightId));highlightsCache.delete(currentUser.uid);row.remove();await renderHighlights()}catch(e){console.error(e)}})}
async function createHighlight(){if(!currentUser)return;const title=clampText($("v6HighlightTitle")?.value,30),ids=[...$("v6HighlightStories").querySelectorAll("input:checked")].map(x=>x.value).slice(0,20),st=$("v6HighlightStatus"),btn=$("v6HighlightSave");if(title.length<1||!ids.length){st.className="v6-status error";st.textContent="Informe um título e selecione pelo menos um Story.";return}btn.disabled=true;try{const first=await getDoc(doc(db,"stories",ids[0])),cover=first.exists()?first.data().mediaUrl||"":"";await addDoc(collection(db,"destaques",currentUser.uid,"itens"),{ownerUid:currentUser.uid,titulo:title,capaUrl:cover,storyIds:ids,criadoEm:Timestamp.now(),atualizadoEm:Timestamp.now()});highlightsCache.delete(currentUser.uid);st.className="v6-status ok";st.textContent="Destaque criado!";await renderHighlights();setTimeout(()=>$("v6HighlightsModal").classList.remove("open"),500)}catch(e){console.error(e);st.className="v6-status error";st.textContent="Não foi possível criar o Destaque."}finally{btn.disabled=false}}

function conversationId(a,b){return[a,b].sort().join("__")}
function installDirectAttachment(){const form=$("snChatForm");if(!form||form.querySelector(".v6-direct-attach"))return;const b=document.createElement("button");b.type="button";b.className="v6-direct-attach";b.title="Enviar foto ou vídeo";b.textContent="＋";const input=document.createElement("input");input.type="file";input.accept="image/jpeg,image/png,image/webp,video/mp4,video/webm,video/quicktime";input.hidden=true;b.onclick=()=>input.click();input.onchange=()=>{const f=input.files?.[0];if(f)sendDirectMedia(f,b);input.value=""};form.prepend(b,input)}
async function sendDirectMedia(file,button){if(!currentUser)return;let other=activeDirectOtherUid;if(!other&&/perfil-social\.html$/i.test(location.pathname))other=new URLSearchParams(location.search).get("uid")||"";if(!other||other===currentUser.uid){alert("Abra uma conversa antes de anexar mídia.");return}if(await ownBlockOf(other)){alert("Desbloqueie este perfil para enviar mídia.");return}const isVideo=file.type.startsWith("video/");if(!file.type.startsWith("image/")&&!isVideo){alert("Escolha uma foto ou vídeo.");return}if(!isVideo&&file.size>25*1024*1024){alert("A foto pode ter até 25 MB.");return}if(isVideo&&file.size>45*1024*1024){alert("O vídeo pode ter até 45 MB.");return}button.disabled=true;try{const up=await uploadCloudinary(file,{maxBytes:isVideo?45*1024*1024:25*1024*1024,allowImage:true,allowVideo:true,tags:["cadastro-de-atletas","direct"]}),chatId=conversationId(currentUser.uid,other),type=isVideo?"video":"image",label=isVideo?"🎥 Vídeo":"📷 Foto";await addDoc(collection(db,"conversas",chatId,"mensagens"),{senderUid:currentUser.uid,text:"",type,mediaUrl:up.url,mediaPath:up.path,mediaMime:up.mime||file.type,mediaSize:Number(up.size||file.size||0),createdAt:Timestamp.now()});const convo=doc(db,"conversas",chatId),snap=await getDoc(convo);if(!snap.exists())await setDoc(convo,{participants:[currentUser.uid,other].sort(),lastMessage:label,lastSenderUid:currentUser.uid,lastMessageAt:Timestamp.now(),lastReadBy:[currentUser.uid],createdAt:Timestamp.now()});else await setDoc(convo,{lastMessage:label,lastSenderUid:currentUser.uid,lastMessageAt:Timestamp.now(),lastReadBy:[currentUser.uid]},{merge:true})}catch(e){console.error("Direct mídia:",e);alert("Não foi possível enviar a mídia.")}finally{button.disabled=false}}
async function decorateDirectMedia(){const list=$("snChatMessages"),user=currentUser,other=activeDirectOtherUid||(/perfil-social\.html$/i.test(location.pathname)?new URLSearchParams(location.search).get("uid")||"":"");if(!list||!user||!other)return;const chatId=conversationId(user.uid,other);try{const snap=await getDocs(query(collection(db,"conversas",chatId,"mensagens"),orderBy("createdAt","asc"),limit(200))),nodes=[...list.querySelectorAll(".sn-msg")];if(nodes.length!==snap.docs.length)return;snap.docs.forEach((d,i)=>{const x=d.data(),node=nodes[i];if(!node||!(["image","video"].includes(x.type))||node.querySelector(".v6-direct-media"))return;node.classList.add("media");const time=node.querySelector("small");[...node.childNodes].filter(n=>n.nodeType===Node.TEXT_NODE).forEach(n=>n.remove());const media=document.createElement(x.type==="video"?"video":"img");media.className="v6-direct-media";media.src=x.mediaUrl||"";if(x.type==="video"){media.controls=true;media.playsInline=true}if(x.text){const cap=document.createElement("span");cap.className="v6-direct-caption";cap.textContent=x.text;node.insertBefore(cap,time)}node.insertBefore(media,node.firstChild)})}catch(e){console.warn("Render Direct mídia:",e)}}

function watchDirectContext(){document.addEventListener("click",e=>{const row=e.target.closest?.("[data-sn-other]");if(row?.dataset.snOther)activeDirectOtherUid=row.dataset.snOther;if(e.target.closest?.("#snProfileMessageBtn")){const uid=new URLSearchParams(location.search).get("uid")||"";if(uid)activeDirectOtherUid=uid}},true)}

function ensureHashtagNav(){document.querySelectorAll(".site-menu-nav,.pp-nav").forEach(nav=>{if(nav.querySelector('[data-v6-link="hashtags"]'))return;const a=document.createElement("a");a.href="hashtags.html";a.dataset.v6Link="hashtags";a.innerHTML="<span>＃</span><span>HASHTAGS</span>";nav.appendChild(a)})}

async function filterBlockedFeed(root=document){if(!currentUser)return;const cards=[...root.querySelectorAll?.("[data-owner]")||[]];for(const card of cards){const target=card.dataset.owner;if(target&&target!==currentUser.uid&&await ownBlockOf(target))card.remove()}}

function runEnhancements(){installStyles();ensureCarouselModal();installCarouselLaunchers();scanRichText();enhanceFeedCarousels();enhanceProfileCarousels();installProfilePrivacy();renderHighlights();installDirectAttachment();decorateDirectMedia();ensureHashtagNav();filterBlockedFeed()}
let timer=0;function schedule(){clearTimeout(timer);timer=setTimeout(runEnhancements,90)}
const observer=new MutationObserver(()=>schedule());
observer.observe(document.documentElement,{subtree:true,childList:true});
watchDirectContext();
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",runEnhancements,{once:true});else runEnhancements();
onAuthStateChanged(auth,u=>{currentUser=u;privacyCache.clear();blockCache.clear();schedule()});
